import {zipSync,strToU8} from 'fflate';
import {text,type Locale} from '../core';
import {reportTable,type ReportOutput} from '../core/report-output';
import type {ExcelSheetSpec} from '../core/reporting';
const xml=(v:unknown)=>String(v??'').replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'').replace(/_x[0-9a-f]{4}_/gi,m=>'_x005F_'+m.slice(1)).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;');
const letter=(index:number):string=>{let out='';for(let n=index+1;n>0;n=Math.floor((n-1)/26))out=String.fromCharCode(65+(n-1)%26)+out;return out;};
const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main',rel='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
/** Real OOXML workbook. Text uses inline strings; authored values can never become formulas. */
export function reportXlsx(result:ReportOutput,locale:Locale='ru'):Uint8Array<ArrayBuffer>{
  const table=reportTable(result),sheets:readonly ExcelSheetSpec[]=table.excel?.sheets??[{name:'Report',columns:table.columns,freezeRows:1,autoFilter:true}];
  const formats:string[]=[],format=(value:string)=>{let i=formats.indexOf(value);if(i<0){i=formats.length;formats.push(value);}return i+2;};
  const files:Record<string,Uint8Array>={},put=(path:string,value:string)=>{files[path]=strToU8('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'+value);};
  for(const [index,sheet] of sheets.entries()){
    const styles=sheet.columns.map(c=>c.format?format(c.format):table.schema[c.key]?.type==='datetime'?format('yyyy-mm-dd hh:mm:ss'):0);
    const rows=[...table.rows].sort((a,b)=>{for(const s of sheet.sort??[]){const av=a[s.key]??null,bv=b[s.key]??null;if(av===bv)continue;if(av===null)return 1;if(bv===null)return -1;const delta=av<bv?-1:1;return s.direction==='asc'?delta:-delta;}return 0;});
    const cell=(value:unknown,address:string,style=0,type?:string)=>{
      if(value===null||value===undefined)return `<c r="${address}" s="${style}"/>`;
      if(type==='datetime'){const ms=Date.parse(String(value));if(!Number.isFinite(ms))throw new Error('Invalid XLSX datetime');const serial=ms/86400000+25569;if(serial<1)throw new Error('XLSX dates must be on/after 1900-01-01');return `<c r="${address}" s="${style}"><v>${serial<61?serial-1:serial}</v></c>`;}
      if(typeof value==='number'){if(!Number.isFinite(value))throw new Error('Non-finite XLSX value');return `<c r="${address}" s="${style}"><v>${value}</v></c>`;}
      if(typeof value==='boolean')return `<c r="${address}" t="b" s="${style}"><v>${Number(value)}</v></c>`;
      if(String(value).length>32767)throw new Error('XLSX text exceeds 32767 characters');
      return `<c r="${address}" t="inlineStr" s="${style}"><is><t xml:space="preserve">${xml(value)}</t></is></c>`;
    };
    const end=letter(sheet.columns.length-1)+(rows.length+1),freeze=sheet.freezeRows??0;
    put(`xl/worksheets/sheet${index+1}.xml`,`<worksheet xmlns="${ns}"><dimension ref="A1:${end}"/><sheetViews><sheetView workbookViewId="0">${freeze?`<pane ySplit="${freeze}" topLeftCell="A${freeze+1}" activePane="bottomLeft" state="frozen"/><selection pane="bottomLeft" activeCell="A${freeze+1}" sqref="A${freeze+1}"/>`:''}</sheetView></sheetViews><sheetFormatPr defaultRowHeight="18"/><cols>${sheet.columns.map((c,i)=>`<col min="${i+1}" max="${i+1}" width="${c.width??(table.schema[c.key]?.type==='datetime'?25:22)}" customWidth="1"/>`).join('')}</cols><sheetData><row r="1" ht="30" customHeight="1">${sheet.columns.map((c,i)=>cell(text(c.title,locale)+(c.unit?` (${c.unit})`:''),letter(i)+'1',1)).join('')}</row>${rows.map((r,n)=>`<row r="${n+2}">${sheet.columns.map((c,i)=>cell(r[c.key],letter(i)+(n+2),styles[i],table.schema[c.key]?.type)).join('')}</row>`).join('')}</sheetData>${sheet.autoFilter?`<autoFilter ref="A1:${end}"/>`:''}<pageMargins left="0.3" right="0.3" top="0.5" bottom="0.5" header="0.2" footer="0.2"/><pageSetup orientation="landscape" paperSize="9"/><headerFooter><oddFooter>${xml('&L'+'Saturn · '+result.revision+' · '+(result.snapshotHash??''))}</oddFooter></headerFooter></worksheet>`);
  }
  put('xl/styles.xml',`<styleSheet xmlns="${ns}"><numFmts count="${formats.length}">${formats.map((f,i)=>`<numFmt numFmtId="${164+i}" formatCode="${xml(f)}"/>`).join('')}</numFmts><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF087F8C"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="${2+formats.length}"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyAlignment="1"><alignment wrapText="1" vertical="center"/></xf>${formats.map((_,i)=>`<xf numFmtId="${164+i}" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/>`).join('')}</cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`);
  put('xl/workbook.xml',`<workbook xmlns="${ns}" xmlns:r="${rel}"><bookViews><workbookView/></bookViews><sheets>${sheets.map((s,i)=>`<sheet name="${xml(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`);
  const relations='http://schemas.openxmlformats.org/package/2006/relationships';
  put('xl/_rels/workbook.xml.rels',`<Relationships xmlns="${relations}">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="${rel}/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="styles" Type="${rel}/styles" Target="styles.xml"/></Relationships>`);
  put('_rels/.rels',`<Relationships xmlns="${relations}"><Relationship Id="workbook" Type="${rel}/officeDocument" Target="xl/workbook.xml"/><Relationship Id="core" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/></Relationships>`);
  put('docProps/core.xml',`<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>${xml(text(result.label,locale))}</dc:title><dc:creator>Saturn</dc:creator><dc:description>${xml(JSON.stringify({revision:result.revision,snapshot:result.snapshotHash,artifact:result.artifactId,from:result.from,to:result.to,generatedAt:result.generatedAt,run:result.runId,actor:result.actor,trigger:result.trigger,inputs:'kind' in result?result.inputs:undefined}))}</dc:description></cp:coreProperties>`);
  put('[Content_Types].xml',`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`);
  // Fixed ZIP timestamps make repeated downloads byte-for-byte reproducible.
  return new Uint8Array(zipSync(Object.fromEntries(Object.entries(files).map(([key,bytes])=>[key,[bytes,{mtime:new Date('2000-01-01T00:00:00Z')}]])),{level:6}));
}
