import {test,expect} from 'bun:test';
import {unzipSync,strFromU8} from 'fflate';
import {signal,report,project,reportSchema,reportField,numberField,textField,booleanField,dateTimeField,reportColumn,excelColumn,excelSheet,workbook,asc,desc,validateProject} from '../src/core';
import {canonical} from '../src/core/artifact';
import {decodeProject} from '../src/runtime/decode-project';
import {Store} from '../src/runtime/store';
import {runReport,loadReport,reportCapsule} from '../src/runtime/report';
import {executeQuery,type QueryTask} from '../src/runtime/report-query';
import {reportXlsx} from '../src/runtime/report-xlsx';
import {reportHtml} from '../src/core/report-output';
import {reportResponse} from '../src/host/report-api';
const flow=signal('flow',{initial:0,staleAfter:2000,unit:'m³/h'});
const schema=reportSchema({average:reportField(flow),coverage:numberField('%'),name:textField(),enabled:booleanField(),time:dateTimeField()});
export const migratedReport=report('balance',{label:'Тепловой баланс',description:'Достоверность и пропуски',signals:[flow],schema,window:5000,inputs:{scale:{type:'number',default:1,min:.1,max:10}},
 sql:`SELECT SUM(CASE WHEN quality='good' THEN value*(end-start) END)/NULLIF(SUM(CASE WHEN quality='good' THEN end-start END),0)*:scale AS average,100.0*SUM(CASE WHEN quality='good' THEN end-start ELSE 0 END)/(:to-:from) AS coverage,'=1+1' AS name,1 AS enabled,:from AS time FROM segments`,
 columns:Object.values(schema).map(f=>reportColumn(f.key,f)),summary:[{key:'average',label:'Среднее',aggregate:'avg'}],chart:{x:'time',y:'average',title:'Среднее'},
 excel:workbook([excelSheet('Данные',schema,{columns:[excelColumn('Время UTC',schema.time,{format:'yyyy-mm-dd hh:mm:ss',width:25}),excelColumn('Среднее',schema.average,{format:'0.000'}),excelColumn('Покрытие',schema.coverage),excelColumn('Текст',schema.name),excelColumn('Включён',schema.enabled)],sort:[asc(schema.time)],freezeRows:1,autoFilter:true}),excelSheet('Рейтинг',schema,{columns:[excelColumn('Среднее',schema.average)],sort:[desc(schema.average)]})])});
const model=()=>project({id:'reports',label:'Reports',equipment:[],pipes:[],reports:[migratedReport]});
const from=Date.UTC(2026,0,1),to=from+5000;
const task=():QueryTask=>({definition:migratedReport,revision:'test',from,to,inputs:{scale:1},data:{samples:[],segments:[{signal:'flow',start:from,end:from+1000,value:10,quality:'good'},{signal:'flow',start:from+1000,end:from+3000,value:20,quality:'good'},{signal:'flow',start:from+3000,end:from+4000,value:null,quality:'offline'},{signal:'flow',start:from+4000,end:to,value:20,quality:'good'}]}});
test('old weighted SQL capsule gives 17.5 and 80%, typed booleans/dates survive artifact roundtrip',()=>{const p=decodeProject(canonical(model()));expect(p.reports![0]).toEqual(migratedReport);expect(p.signals.flow).toBe((p.reports![0] as typeof migratedReport).signals[0]);const r=executeQuery(task());expect(r.rows[0]).toEqual({average:17.5,coverage:80,name:'=1+1',enabled:true,time:new Date(from).toISOString()});expect(reportHtml(r,'ru')).toContain('17,5');});
test('schema rejects absent aliases, bad types/dates, operational SQL and writes; null remains null',()=>{
 for(const sql of ['SELECT * FROM users','DELETE FROM samples','SELECT 1; SELECT 2','SELECT load_extension(1)','SELECT 1 AS nope'])expect(()=>executeQuery({...task(),definition:{...migratedReport,sql}})).toThrow();
 for(const value of ["'bad' AS average",'2 AS enabled',"'2026-01-01' AS time"]){const key=value.split(' AS ')[1]!,s=migratedReport.sql.replace(key==='average'?/SUM\(CASE WHEN quality='good' THEN value\*\(end-start\) END\)\/NULLIF\(SUM\(CASE WHEN quality='good' THEN end-start END\),0\)\*:scale AS average/:key==='enabled'?/1 AS enabled/:/:from AS time/,value);expect(()=>executeQuery({...task(),definition:{...migratedReport,sql:s}})).toThrow();}
 const r=executeQuery({...task(),data:{samples:[],segments:[]}});expect(r.rows[0]?.average).toBeNull();
});
test('capsule accounts for every missing/stale interval, preserving strings/booleans',()=>{const data=reportCapsule([flow],new Map([['flow',[{signal:'flow',value:0,quality:'good' as const,at:from+1000}]]]),from,to);expect(data.segments).toEqual([{signal:'flow',start:from,end:from+1000,value:null,quality:'missing'},{signal:'flow',start:from+1000,end:from+3000,value:0,quality:'good'},{signal:'flow',start:from+3000,end:to,value:null,quality:'stale'}]);});
test('workbook validates duplicate names, types, widths, field references',()=>{for(const patch of [{name:'bad/name'},{name:'Данные',columns:[{key:'unknown',title:'X'}]},{name:'Данные',columns:[{key:'name',title:'X',format:'0'}]},{name:'Данные',columns:[{key:'average',title:'X',width:0}]}])expect(()=>validateProject({...model(),reports:[{...migratedReport,excel:{sheets:[{...migratedReport.excel!.sheets[0]!,...patch}]}}]})).toThrow();expect(()=>validateProject({...model(),reports:[{...migratedReport,excel:{sheets:[migratedReport.excel!.sheets[0]!,migratedReport.excel!.sheets[0]!]}}]})).toThrow();});
test('real XLSX ZIP contains dates, boolean, safe text, formats, sorting, blanks, filter, panes; deterministic',async()=>{const r=executeQuery(task());r.rows.push({...r.rows[0],average:null,enabled:false,time:new Date(from-1000).toISOString()} as typeof r.rows[number]);const bytes=reportXlsx(r),zip=unzipSync(bytes);expect(bytes.slice(0,2)).toEqual(new Uint8Array([80,75]));expect(reportXlsx(r)).toEqual(bytes);const sheet=strFromU8(zip['xl/worksheets/sheet1.xml']!);expect(sheet).toContain('autoFilter');expect(sheet).toContain('state="frozen"');expect(sheet).toContain('t="b"');expect(sheet).toContain('=1+1');expect(sheet).not.toContain('<f>');expect(sheet).toContain('<c r="B2" s="3"/>');expect(strFromU8(zip['xl/styles.xml']!)).toContain('0.000');await Bun.write('artifacts/report-migration.xlsx',bytes);});
test('runtime snapshot artifact remains identical after archive changes; unknown inputs fail',async()=>{const store=new Store(':memory:');await store.init();try{await store.append([{signal:'flow',at:from,value:10,quality:'good'}]);const p=model(),r=await runReport(store,p,'revision',migratedReport.id,from,to,{inputs:{scale:2}});expect('kind' in r&&r.rows[0]?.average).toBe(20);await store.append([{signal:'flow',at:from+1000,value:90,quality:'good'}]);expect(await loadReport(store,r.artifactId!)).toEqual(r);const snapshots:{dataset:string}[]=await store.sql`SELECT dataset FROM report_snapshots WHERE hash=${r.snapshotHash!}`;expect(JSON.parse(snapshots[0]!.dataset).inputs).toEqual({scale:2});expect(JSON.parse(snapshots[0]!.dataset).series[0][1]).toHaveLength(1);const url=new URL(`http://localhost/api/report?artifact=${r.artifactId}&format=xlsx`);const response=await reportResponse(store,p,'another-build',url);expect(new Uint8Array(await response.arrayBuffer())).toEqual(reportXlsx(r));await expect(runReport(store,p,'r','balance',from,to,{inputs:{scale:0}})).rejects.toThrow('range');await expect(runReport(store,p,'r','balance',from,to,{inputs:{surprise:1}})).rejects.toThrow('Unknown report input');}finally{await store.close();}});
test('capsule preserves numeric-looking text and boolean values without coercing signal types',()=>{
 const typed=reportSchema({value:textField()}),t=task();t.definition={...migratedReport,schema:typed,columns:[reportColumn('Text',typed.value)],sql:'SELECT value FROM samples'};t.data={segments:[],samples:[{signal:'text',time:from,value:'00123',quality:'good'}]};expect(executeQuery(t).rows[0]?.value).toBe('00123');
});
test('SQL runaway is killed at the process boundary and the host remains responsive',async()=>{const store=new Store(':memory:');await store.init();try{await store.append(Array.from({length:100},(_,i)=>({signal:'flow',at:from+i,value:i,quality:'good' as const})));const fields=reportSchema({n:numberField()}),r=report('slow',{label:'Slow',signals:[flow],schema:fields,columns:[reportColumn('Count',fields.n)],window:5000,sql:'SELECT count(*) AS n FROM samples a,samples b,samples c,samples d,samples e,samples f'}),p=project({id:'slow',label:'Slow',equipment:[],pipes:[],reports:[r]});let responsive=false;const timer=setTimeout(()=>{responsive=true;},50);await expect(runReport(store,p,'r','slow',from,to)).rejects.toThrow('5 seconds');clearTimeout(timer);expect(responsive).toBe(true);}finally{await store.close();}},10000);
test('SQL quoted text is not parsed as bindings or statements',()=>{const schema=reportSchema({value:textField()}),t=task();t.definition={...migratedReport,schema,columns:[reportColumn('Text',schema.value)],sql:"SELECT ':unknown; update' AS value -- :not_a_parameter"};expect(executeQuery(t).rows[0]?.value).toBe(':unknown; update');});
