import type {GitState} from '../core/git';
import { useEffect, useRef, useState } from 'react';
import type { TelemetryRun, VersionComparison } from '../core/telemetry-run';
import type { Locale } from '../core';
import { api } from './api';
export function CompareHistory({signal,locale,expand}:{signal:string;locale:Locale;expand:()=>void}){
  const request=useRef<AbortController|null>(null);
  const ru=locale==='ru',[runs,setRuns]=useState<TelemetryRun[]>([]),[refs,setRefs]=useState<Record<string,string>>({}),[a,setA]=useState(''),[b,setB]=useState(''),[minutes,setMinutes]=useState(10),[result,setResult]=useState<VersionComparison|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(false);
  useEffect(()=>{request.current?.abort();setBusy(false);setResult(null);setError('');return()=>request.current?.abort();},[signal,a,b,minutes]);
  useEffect(()=>{if(!open)return;let live=true;void api<GitState>('git').then(g=>{if(live)setRefs(Object.fromEntries(g.commits.map(c=>[c.hash,c.refs])));}).catch(()=>{});void api<TelemetryRun[]>('telemetry/runs').then(list=>{if(live){setRuns(list);setA(v=>v||list[1]?.id||'');setB(v=>v||list[0]?.id||'');}},e=>{if(live)setError(String(e));});return()=>{live=false;};},[open]);
  const compare=async()=>{request.current?.abort();const abort=request.current=new AbortController();setBusy(true);try{const duration=minutes*60000;const next=await api<VersionComparison>(`telemetry/compare?${new URLSearchParams({a,b,signal,duration:String(duration),bucket:String(Math.max(1000,Math.ceil(duration/120/1000)*1000))})}`,undefined,abort.signal);if(!abort.signal.aborted){setResult(next);setError('');}}catch(e){if(!abort.signal.aborted)setError(String(e));}finally{if(!abort.signal.aborted)setBusy(false);}};
  const label=(run:TelemetryRun)=>`${refs[run.sourceRevision??'']?refs[run.sourceRevision??'']+' · ':''}${run.sourceRevision?.slice(0,7)??'draft'} · ${run.build.slice(7,14)} · ${run.mode} · ${new Date(run.startedAt).toLocaleString()}`;
  const values=result?.rows.flatMap(r=>[r.a,r.b].filter((v):v is number=>v!==null))??[],min=Math.min(...values),max=Math.max(...values);
  const path=(key:'a'|'b')=>{let connected=false;return result?.rows.map((row,i)=>{const value=row[key];if(value===null){connected=false;return '';}const point=`${connected?'L':'M'}${24+i/Math.max(1,result.rows.length-1)*920},${112-(value-min)/Math.max(.01,max-min)*90}`;connected=true;return point;}).join(' ');};
  return <details className="version-comparison" open={open} onToggle={e=>{setOpen(e.currentTarget.open);if(e.currentTarget.open)expand();}}><summary>{ru?'Сравнить версии по измерениям':'Compare versions using observations'}</summary>{open&&<><p className="muted">{ru?'A / B — отдельные запуски применённых сборок. Ось X: время от старта. Средние значения учитывают свежесть; пробелы не заполняются нулями.':'A / B are separate runs of applied builds. X: elapsed time. Means respect freshness; gaps remain missing.'}</p><div className="git-controls">{(['a','b'] as const).map(key=><label key={key}>{key.toUpperCase()} <select aria-label={ru?`Запуск ${key.toUpperCase()}`:`Run ${key.toUpperCase()}`} value={key==='a'?a:b} onChange={e=>(key==='a'?setA:setB)(e.target.value)}><option value="">—</option>{runs.map(run=><option key={run.id} value={run.id}>{label(run)}</option>)}</select></label>)}<label>{ru?'Минуты':'Minutes'} <input type="number" min="1" max="1440" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><button disabled={busy||!a||!b||a===b||minutes<1||minutes>1440} onClick={()=>void compare()}>{ru?'Сопоставить':'Compare'}</button></div>{error&&<p role="alert">{error}</p>}{!runs.length&&<p>{ru?'Нет записанных запусков. Старые измерения без provenance не привязываются к текущей ветке.':'No recorded runs. Legacy observations without provenance are not attributed to the current branch.'}</p>}{result&&<><p><span style={{color:'var(--accent)'}}>A</span> / <span style={{color:'var(--warning,#d49649)'}}>B</span> · {result.signal} {result.unit} · Δ = B − A</p>{values.length>0&&<svg className="trend" viewBox="0 0 970 142" preserveAspectRatio="none" aria-label={ru?'Сравнение версий A и B':'Version comparison A and B'}><path d="M24 12V119H944" fill="none" stroke="var(--border)"/>{(['a','b'] as const).map(key=><path key={key} d={path(key)} fill="none" stroke={key==='a'?'var(--accent)':'var(--warning,#d49649)'} strokeWidth={2}/>)}<text x="24" y="138">0</text><text x="944" y="138" textAnchor="end">{minutes} min</text></svg>}<div style={{maxHeight:220,overflow:'auto'}}><table><thead><tr><th>t, s</th><th>A</th><th>B</th><th>Δ</th><th>{ru?'Покрытие A / B':'Coverage A / B'}</th></tr></thead><tbody>{result.rows.map(r=><tr key={r.elapsed}><td>{r.elapsed/1000}</td><td>{r.a?.toFixed(3)??'—'}</td><td>{r.b?.toFixed(3)??'—'}</td><td>{r.delta?.toFixed(3)??'—'}</td><td>{Math.round(r.coverageA*100)}% / {Math.round(r.coverageB*100)}%</td></tr>)}</tbody></table></div></>}</>}</details>;
}
