import { useState } from 'react';
import type { Locale } from '../core';
import type { ProjectResource, ResourceCatalog } from '../core/resources';
import { ResourceIcon } from './icons';
import { api } from './api';
export interface PluginStatus {name:string;repository:string;ref:string;directory?:string;revision:string;latest?:string;update:boolean;modified:boolean;error?:string}
export function Dependencies({locale,plugins,changed,catalog,openSource}:{locale:Locale;plugins:PluginStatus[];changed:(plugins:PluginStatus[])=>void;catalog?:ResourceCatalog;openSource?:(resource:ProjectResource)=>void}){
  const ru=locale==='ru',[name,setName]=useState(''),[repository,setRepository]=useState(''),[ref,setRef]=useState('main'),[directory,setDirectory]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [search,setSearch]=useState(''),[adding,setAdding]=useState(false),[tab,setTab]=useState<'project'|'updates'>('project');
  const matches=(value:string)=>value.toLocaleLowerCase().includes(search.toLocaleLowerCase());
  const visible=plugins.filter(plugin=>matches(plugin.name+' '+plugin.repository)&&(tab==='project'||plugin.update||plugin.error));
  const copied=(catalog?.resources??[]).filter(resource=>resource.kind==='plugin'&&!catalog?.resources.some(owner=>owner.kind==='plugin'&&owner.uri===resource.parent)&&!plugins.some(plugin=>resource.source?.path.startsWith('plugins/'+plugin.name+'/'))&&(matches(resource.name[locale]+' '+resource.source?.path)||catalog?.resources.some(child=>child.parent===resource.uri&&matches(child.source?.path??''))));
  const run=async(path:string,body:unknown)=>{setBusy(true);setError('');try{changed(await api<PluginStatus[]>(path,body));}catch(e){setError(String(e));}finally{setBusy(false);}};
  return <section className="dependencies-surface plugin-catalog" aria-label={ru?'Плагины проекта':'Project plugins'}><header><div><h1>{ru?'Плагины':'Plugins'}</h1><p className="muted">{ru?'Расширения инженерного проекта':'Engineering project extensions'}</p></div><div className="plugin-toolbar"><label className="plugin-search"><ResourceIcon icon="search"/><input aria-label={ru?'Поиск плагинов':'Search plugins'} placeholder={ru?'Найти плагин…':'Search plugins…'} value={search} onChange={event=>setSearch(event.target.value)}/></label><button className="icon-button" disabled={busy} aria-label={ru?'Проверить обновления':'Check for updates'} title={ru?'Проверить обновления':'Check for updates'} onClick={()=>void run('plugins/check',{})}><ResourceIcon icon="refresh"/></button><button aria-expanded={adding} onClick={()=>setAdding(value=>!value)}><ResourceIcon icon="plus"/>{ru?'Добавить':'Add'}</button></div></header><nav className="plugin-filters" aria-label={ru?'Каталог плагинов':'Plugin catalog'}><button aria-pressed={tab==='project'} onClick={()=>setTab('project')}>{ru?'В проекте':'In project'}</button><button aria-pressed={tab==='updates'} onClick={()=>setTab('updates')}>{ru?'Обновления':'Updates'} {plugins.filter(plugin=>plugin.update).length||''}</button></nav><p className="muted">{ru?'Исходники копируются в plugins/ и фиксируются в Git проекта. Подключение выполняется явным import. Обновление никогда не заменяет локальные изменения.':'Sources are copied to plugins/ and versioned in project Git. Use an explicit import. Updates never replace locally modified files.'}</p>
  {adding&&<form className="dependency-add" onSubmit={event=>{event.preventDefault();void run('plugins/install',{name,repository,ref,directory});}}><label>{ru?'Папка плагина':'Plugin folder'}<input required pattern="[a-z][a-z0-9-]{0,63}" value={name} onChange={e=>setName(e.target.value)} placeholder="controller-profile"/></label><label>GitHub HTTPS<input required type="url" value={repository} onChange={e=>setRepository(e.target.value)} placeholder="https://github.com/owner/repository"/></label><label>{ru?'Ветка / тег':'Branch / tag'}<input required value={ref} onChange={e=>setRef(e.target.value)}/></label><label>{ru?'Каталог в репозитории':'Repository directory'}<input value={directory} onChange={e=>setDirectory(e.target.value)} placeholder="extensions/controller-profile"/></label><button disabled={busy}>{busy?'…':ru?'Добавить плагин':'Add plugin'}</button></form>}
  {error&&<p role="alert" className="error-text">{error}</p>}{visible.map(plugin=><article className="dependency-card" key={plugin.name}><header><strong><ResourceIcon icon="plugin"/>{plugin.name}</strong><span className={plugin.update?'warning':'muted'}>{plugin.update?(ru?'Доступно обновление':'Update available'):ru?'Закреплена ревизия':'Pinned revision'}</span></header><a href={plugin.repository} target="_blank" rel="noreferrer">{plugin.repository}</a><p><code>{plugin.ref} · {plugin.revision.slice(0,12)}</code></p>{openSource&&catalog?.resources.find(resource=>resource.source?.path.startsWith('plugins/'+plugin.name+'/'))&&<button onClick={()=>{const resource=catalog?.resources.find(item=>item.source?.path.startsWith('plugins/'+plugin.name+'/'));if(resource)openSource(resource);}}>{ru?'Открыть исходники':'Open source'}</button>}{plugin.modified&&<p className="warning">{ru?'Есть локальные изменения':'Locally modified'}</p>}{plugin.error&&<p className="error-text">{plugin.error}</p>}{plugin.update&&<button disabled={busy||plugin.modified} onClick={()=>void run('plugins/update',{name:plugin.name,repository:plugin.repository,ref:plugin.ref,expected:plugin.revision,directory:plugin.directory})}>{ru?'Обновить исходники до ':'Update sources to '}{plugin.latest?.slice(0,12)}</button>}</article>)}{tab==='project'&&copied.map(resource=><article className="dependency-card" key={resource.uri}><header><strong><ResourceIcon icon="plugin"/>{resource.name[locale]}</strong><span className="muted">{ru?'Исходник проекта':'Project source'}</span></header><code>{resource.source?.path}</code>{openSource&&<button onClick={()=>openSource(resource)}>{ru?'Открыть исходник':'Open source'}</button>}</article>)}{!visible.length&&(tab==='updates'||!copied.length)&&<div className="plugin-empty"><ResourceIcon icon="plugin" size={36}/><h2>{search?(ru?'Совпадений нет':'No matches'):tab==='updates'?(ru?'Обновлений нет':'No updates'):(ru?'Добавьте расширение проекта':'Add a project extension')}</h2><p className="muted">{ru?'Добавьте исходники из GitHub или скопируйте файлы в plugins/. Оборудование, драйверы и цели используют обычные импорты TypeScript.':'Add source from GitHub or copy files to plugins/. Equipment, drivers and targets use ordinary TypeScript imports.'}</p>{!adding&&tab==='project'&&!search&&<button onClick={()=>setAdding(true)}>{ru?'Добавить из GitHub':'Add from GitHub'}</button>}</div>}</section>;
}
