import { useState } from 'react';
import type { Locale } from '../core';
import { api } from './api';
export interface PluginStatus {name:string;repository:string;ref:string;directory?:string;revision:string;latest?:string;update:boolean;modified:boolean;error?:string}
export function Dependencies({locale,plugins,changed}:{locale:Locale;plugins:PluginStatus[];changed:(plugins:PluginStatus[])=>void}){
  const ru=locale==='ru',[name,setName]=useState(''),[repository,setRepository]=useState(''),[ref,setRef]=useState('main'),[directory,setDirectory]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const run=async(path:string,body:unknown)=>{setBusy(true);setError('');try{changed(await api<PluginStatus[]>(path,body));}catch(e){setError(String(e));}finally{setBusy(false);}};
  return <section className="dependencies-surface"><header><h2>{ru?'Зависимости проекта':'Project dependencies'}</h2><button disabled={busy} onClick={()=>void run('plugins/check',{})}>{ru?'Проверить обновления':'Check for updates'}</button></header><p className="muted">{ru?'Исходники копируются в plugins/ и фиксируются в Git проекта. Подключение выполняется явным import. Обновление никогда не заменяет локальные изменения.':'Sources are copied to plugins/ and versioned in project Git. Use an explicit import. Updates never replace locally modified files.'}</p>
  <form className="dependency-add" onSubmit={event=>{event.preventDefault();void run('plugins/install',{name,repository,ref,directory});}}><label>{ru?'Папка плагина':'Plugin folder'}<input required pattern="[a-z][a-z0-9-]{0,63}" value={name} onChange={e=>setName(e.target.value)} placeholder="controller-profile"/></label><label>GitHub HTTPS<input required type="url" value={repository} onChange={e=>setRepository(e.target.value)} placeholder="https://github.com/owner/repository"/></label><label>{ru?'Ветка / тег':'Branch / tag'}<input required value={ref} onChange={e=>setRef(e.target.value)}/></label><label>{ru?'Каталог в репозитории':'Repository directory'}<input value={directory} onChange={e=>setDirectory(e.target.value)} placeholder="extensions/controller-profile"/></label><button disabled={busy}>{busy?'…':ru?'Добавить плагин':'Add plugin'}</button></form>
  {error&&<p role="alert" className="error-text">{error}</p>}{plugins.map(plugin=><article className="dependency-card" key={plugin.name}><header><strong>{plugin.name}</strong><span className={plugin.update?'warning':'muted'}>{plugin.update?(ru?'Доступно обновление':'Update available'):ru?'Закреплена ревизия':'Pinned revision'}</span></header><a href={plugin.repository} target="_blank" rel="noreferrer">{plugin.repository}</a><p><code>{plugin.ref} · {plugin.revision.slice(0,12)}</code></p>{plugin.modified&&<p className="warning">{ru?'Есть локальные изменения':'Locally modified'}</p>}{plugin.error&&<p className="error-text">{plugin.error}</p>}{plugin.update&&<button disabled={busy||plugin.modified} onClick={()=>void run('plugins/update',{name:plugin.name,repository:plugin.repository,ref:plugin.ref,expected:plugin.revision,directory:plugin.directory})}>{ru?'Обновить исходники до ':'Update sources to '}{plugin.latest?.slice(0,12)}</button>}</article>)}{!plugins.length&&<p className="muted">{ru?'Нет зависимостей с закреплённой Git-ревизией. Ранее скопированные плагины доступны в проводнике.':'No Git-pinned dependencies. Previously copied plugins remain in the explorer.'}</p>}</section>;
}
