import { useEffect, useState } from 'react';
import type { DeploymentPlan as Plan } from '../core/deployment';
import type { Locale } from '../core';
import { api } from './api';
export function DeploymentPlan({locale,openCode}:{locale:Locale;openCode:()=>Promise<void>}){
 const ru=locale==='ru',[plan,setPlan]=useState<Plan|null>(null),[exists,setExists]=useState(false),[workflow,setWorkflow]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{void api<{plan:Plan;exists:boolean}>('deployment/template').then(r=>{setPlan(r.plan);setExists(r.exists);}).catch(e=>setError(String(e)));},[]);
 const act=async(create=false)=>{setBusy(true);setError('');try{const result=await api<{workflow:string}>(create?'deployment/create':'deployment/preview',{plan});setWorkflow(result.workflow);if(create){setExists(true);await openCode();}}catch(e){setError(String(e));}finally{setBusy(false);}};
 const download=()=>{const url=URL.createObjectURL(new Blob([workflow],{type:'text/yaml'})),link=document.createElement('a');link.href=url;link.download='deploy.yml';link.click();URL.revokeObjectURL(url);};
 return <div className="deployment-plan"><h2>{ru?'План развёртывания':'Deployment plan'}</h2><p className="muted">{ru?'Шаги и зависимости сохраняются в targets/deployment.ts. GitHub Actions запускает проверки и симуляцию; отдельные окружения разделяют публикацию runtime и загрузку контроллера.':'Steps and dependencies live in targets/deployment.ts. GitHub Actions runs checks and simulation; separate environments isolate runtime publication from controller deployment.'}</p>{exists?<button onClick={()=>void openCode()}>{ru?'Показать план в коде':'Show plan in code'}</button>:plan&&<><div className="deployment-steps">{plan.steps.map((step,index)=><article key={step.id}><header><span>{index+1}</span><strong>{step.label}</strong><small>{step.target}</small></header><label>{ru?'После шагов (через запятую)':'After steps (comma separated)'}<input value={step.needs.join(', ')} onChange={event=>{setWorkflow('');setPlan({...plan,steps:plan.steps.map(s=>s.id===step.id?{...s,needs:event.target.value.split(',').map(v=>v.trim()).filter(Boolean)}:s)});}}/></label><label>{ru?'Команда (JSON argv)':'Command (JSON argv)'}<input defaultValue={JSON.stringify(step.command)} onBlur={event=>{try{const command:unknown=JSON.parse(event.target.value);if(!Array.isArray(command)||!command.every(v=>typeof v==='string'))throw new Error('Expected string array');setWorkflow('');setPlan({...plan,steps:plan.steps.map(s=>s.id===step.id?{...s,command}:s)});setError('');}catch(e){setError(String(e));}}}/></label></article>)}</div><button disabled={busy||!!error} onClick={()=>void act()}>{ru?'Предпросмотр workflow':'Preview workflow'}</button>{workflow&&<button disabled={busy} onClick={()=>void act(true)}>{ru?'Создать план в проекте':'Create project plan'}</button>}</>}{workflow&&<><pre className="creation-preview">{workflow}</pre><button onClick={download}>{ru?'Скачать deploy.yml':'Download deploy.yml'}</button></>}{error&&<p role="alert" className="error-text">{error}</p>}<p className="muted">{ru?'Перед запуском нужны сценарии tests/scenarios, команды deploy:scada и deploy:controller в package.json и runner с доступом к целевому контроллеру. План не означает, что прошивка уже собрана или загружена.':'Before running: provide tests/scenarios, deploy:scada and deploy:controller scripts, and a runner with target-controller access. A plan does not mean firmware has been built or flashed.'}</p></div>;
}
