import {useEffect,useState} from 'react';
import type {DeploymentPlan as Plan} from '../core/deployment';
import type {Locale} from '../core';
import {api} from './api';
export function DeploymentPlan({locale,openCode}:{locale:Locale;openCode:()=>Promise<void>}){
 const ru=locale==='ru',[plan,setPlan]=useState<Plan|null>(null),[exists,setExists]=useState(false),[workflow,setWorkflow]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 useEffect(()=>{const abort=new AbortController();void api<{plan:Plan|null;exists:boolean;notice?:string}>('deployment/template',undefined,abort.signal).then(r=>{setPlan(r.plan);setExists(r.exists);setNotice(r.notice??'');}).catch(e=>{if(!abort.signal.aborted)setError(String(e));}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[]);
 const act=async(create=false)=>{setBusy(true);setError('');try{const result=await api<{workflow:string}>(create?'deployment/create':'deployment/preview',{plan});setWorkflow(result.workflow);if(create){setExists(true);await openCode();}}catch(e){setError(String(e));}finally{setBusy(false);}};
 const download=()=>{const url=URL.createObjectURL(new Blob([workflow],{type:'text/yaml'})),link=document.createElement('a');link.href=url;link.download='deploy.yml';link.click();URL.revokeObjectURL(url);};
 return <div className="deployment-plan"><header className="deployment-heading"><div><h2>{ru?'План развёртывания':'Deployment plan'}</h2><p className="muted">{exists?'targets/deployment.ts':ru?'Новый план проекта':'New project plan'}{plan?' · '+plan.steps.length+(ru?' шага':' steps'):''}</p></div>{exists&&<button onClick={()=>void openCode()}>{ru?'Изменить в коде':'Edit source'}</button>}</header>{loading&&<p role="status">{ru?'Чтение плана…':'Reading plan…'}</p>}{notice&&<p className="detail-note">{notice.split(' / ')[ru?0:1]}</p>}
 {plan&&<><div className="deployment-steps">{plan.steps.map((step,index)=><article key={step.id}><header><span>{index+1}</span><strong>{step.label}</strong><small>{step.target}</small></header>{exists?<dl className="detail-fields"><div><dt>ID</dt><dd><code>{step.id}</code></dd></div><div><dt>{ru?'После':'After'}</dt><dd>{step.needs.join(', ')||(ru?'Начальный шаг':'Initial step')}</dd></div><div><dt>{ru?'Окружение':'Environment'}</dt><dd>{step.environment??'—'}</dd></div><div><dt>{ru?'Команда':'Command'}</dt><dd><code>{step.command.map(x=>/\s/.test(x)?JSON.stringify(x):x).join(' ')}</code></dd></div></dl>:<><label>{ru?'После шагов (через запятую)':'After steps (comma separated)'}<input value={step.needs.join(', ')} onChange={e=>{setWorkflow('');setPlan({...plan,steps:plan.steps.map(s=>s.id===step.id?{...s,needs:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)}:s)});}}/></label><label>{ru?'Команда (JSON argv)':'Command (JSON argv)'}<input defaultValue={JSON.stringify(step.command)} onBlur={e=>{try{const command:unknown=JSON.parse(e.target.value);if(!Array.isArray(command)||!command.every(v=>typeof v==='string'))throw new Error('Expected string array');setWorkflow('');setPlan({...plan,steps:plan.steps.map(s=>s.id===step.id?{...s,command}:s)});setError('');}catch(e){setError(String(e));}}}/></label></>}</article>)}</div><div className="deployment-actions"><button disabled={busy||!!error} onClick={()=>void act()}>{busy?'…':ru?'Предпросмотр workflow':'Preview workflow'}</button>{workflow&&!exists&&<button disabled={busy} onClick={()=>void act(true)}>{ru?'Создать план в проекте':'Create project plan'}</button>}</div></>}
 {workflow&&<details className="detail-disclosure" open><summary>GitHub Actions · deploy.yml</summary><pre className="creation-preview">{workflow}</pre><button onClick={download}>{ru?'Скачать deploy.yml':'Download deploy.yml'}</button></details>}{error&&<p role="alert" className="error-text">{error}</p>}<p className="muted">{ru?'Открытие и экспорт плана не запускают его. Для исполнения нужны runner, команды проекта и доступ к выбранному окружению.':'Opening or exporting the plan does not run it. Execution requires a runner, project commands and access to the selected environment.'}</p></div>;>>>>>>> a4652ce (Add command shell, delivery jobs, typed reports, and IDE distribution)
}
