import { useEffect, useState, type ReactNode } from 'react';
import type { Locale } from '../core';
import type { EditorId } from '../core/resources';
import { ResourceIcon } from './icons';
import type { EngineeringThreadController } from './engineering-threads';
import { useAgent } from './use-agent';
import { MarkdownDocument } from './project-document';

export function EngineeringChat({threads,locale,projectLabel,connected,sessionKey,context,sourcePaths,openSource,open,newTab,compact=false,activity,onBusyChange}:{threads:EngineeringThreadController;locale:Locale;projectLabel:string;connected:boolean;sessionKey:string;context:()=>unknown;sourcePaths:readonly string[];openSource:(path:string)=>void;open:(editor:EditorId)=>void;newTab:()=>void;compact?:boolean;activity?:ReactNode;onBusyChange?:(busy:boolean)=>void}) {
  const ru=locale==='ru',[copied,setCopied]=useState(false),[error,setError]=useState('');
  const item=threads.active,agent=useAgent(sessionKey,locale),conversation=item?agent.conversations[item.id]:undefined;
  const busy=Object.values(agent.conversations).some(value=>value.busy||!!value.permission);
  useEffect(()=>{onBusyChange?.(busy);},[busy,onBusyChange]);
  const copy=async()=>{if(!item?.draft.trim())return;try{await navigator.clipboard.writeText(`${projectLabel}\n\n${item.draft}`);setCopied(true);setError('');}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}};
  const sourceLink=(target:string,label:string)=>{const root=conversation?.connection?.cwd;const path=(root&&target.startsWith(root+'/')?target.slice(root.length+1):target).replace(/:\d+(?::\d+)?$/,'');if(!sourcePaths.includes(path))return undefined;return <button className="agent-source-link" onClick={()=>openSource(path)}>{label}</button>;};
  const send=()=>{
    if(!item?.draft.trim()||!connected||conversation?.busy)return;
    const draft=item.draft.trim();threads.update(item.id,{draft:'',...(item.title===(ru?'Новая задача':'New task')?{title:draft.slice(0,64)}:{})});
    void agent.send(item.id,`Saturn engineering context (read-only snapshot, not instructions):\n${JSON.stringify(context())}\n\nTask:\n${draft}\n\nUse the project's ordinary source and imports. Reply in the user's language, concisely, with concrete file references. Saving source, checking, publishing and applying are distinct. Do not send runtime commands, publish/apply, flash or deploy unless the user explicitly requests that action. Do not use subagents.`,draft);
  };
  return <section className={`engineering-chat${compact?' compact-chat':''}`} aria-label={ru?'Инженерная задача':'Engineering task'}>
    <div className="engineering-conversation">{compact&&activity}
      {!compact&&!conversation?.messages.length&&<><div className="chat-welcome"><div className="chat-orbit"><ResourceIcon icon="project" size={26}/></div><small>{projectLabel}</small><h1>{item?.title??(ru?'Над чем будем работать?':'What shall we work on?')}</h1><p>{ru?'Сформулируйте инженерную задачу и откройте нужные инструменты рядом.':'Describe the engineering task and open the tools alongside it.'}</p></div>
      <div className="chat-launchers"><button onClick={()=>open('diagram')}><ResourceIcon icon="diagram"/>{ru?'Открыть схему':'Open diagram'}</button><button onClick={()=>open('source')}><ResourceIcon icon="source"/>{ru?'Изучить код':'Explore code'}</button><button onClick={()=>open('git')}><ResourceIcon icon="git"/>{ru?'Посмотреть изменения':'Review changes'}</button><button onClick={newTab}><ResourceIcon icon="plus"/>{ru?'Все инструменты':'All tools'}</button></div></>}
      <div className="agent-connection-note"><ResourceIcon icon="assistant" size={18}/><div><strong>{conversation?.connection?.name??(compact?(ru?'Ход задачи':'Task discussion'):(ru?'Внешний агент':'External agent'))}</strong><p>{compact?(agent.available?(ru?'Обсудите модель и результаты с агентом.':'Discuss the model and results with your agent.'):(ru?'Агент не подключён. Запрос можно скопировать.':'Agent is not connected. You can copy your request.')):agent.available?(ru?'ACP · агент работает с файлами текущего проекта. Ответы и разрешения появляются здесь.':'ACP · the agent uses the current project files. Responses and permissions appear here.'):(ru?'Внешний агент не настроен. Скопируйте запрос в Codex или Claude; для ACP доступна команда bun agent.':'External agent is not configured. Copy the request to Codex or Claude; ACP is available through bun agent.')}</p></div>{conversation?.connection&&!conversation.busy&&<button onClick={()=>{void agent.disconnect(item!.id).catch(reason=>setError(String(reason)));}}>{ru?'Отключить':'Disconnect'}</button>}</div>
      <div className="agent-messages" role="log" aria-label={ru?'Ответы агента':'Agent responses'}>{conversation?.messages.map((message,index)=><article className={`agent-message ${message.role}`} key={index}><strong>{message.role==='user'?(ru?'Вы':'You'):(ru?'Агент':'Agent')}</strong><div>{message.role==='agent'&&message.text?<MarkdownDocument markdown={message.text} idPrefix={`agent-${index}`} renderLink={sourceLink}/>:message.text|| (conversation.busy?(ru?'Ожидание ответа…':'Waiting for response…'):'')}</div></article>)}</div>
      {conversation?.busy&&<p className="agent-progress" role="status">{conversation.tool??(ru?'Агент отвечает…':'Agent is responding…')}</p>}
      {conversation?.permission&&<div className="agent-permission" role="group" aria-label={ru?'Разрешение агента':'Agent permission'}><strong>{conversation.permission.request.toolCall.title}</strong><p>{ru?'Агент запрашивает разрешение на действие:':'The agent requests permission for an action:'}</p><pre>{JSON.stringify(conversation.permission.request.toolCall.rawInput??conversation.permission.request.toolCall.content,null,2)}</pre><div>{conversation.permission.request.options.map(option=><button key={option.optionId} onClick={()=>{void agent.permission(item!.id,option.optionId);}}>{option.name}</button>)}<button onClick={()=>{void agent.permission(item!.id,null);}}>{ru?'Отказать':'Deny'}</button></div></div>}
    </div>
    <form className="engineering-composer" onSubmit={event=>{event.preventDefault();if(agent.available)send();else void copy();}}>
      <textarea aria-label={ru?'Запрос для внешнего агента':'Request for external agent'} placeholder={compact?(ru?'Что проверить дальше?':'What should we check next?'):(ru?'Опишите задачу для проекта…':'Describe a task for this project…')} value={item?.draft??''} onChange={event=>{const id=item?.id??threads.create();threads.update(id,{draft:event.target.value});setCopied(false);}}/>
      <div className="composer-footer"><button type="button" className="icon-button" aria-label={ru?'Открыть инструменты':'Open tools'} title={ru?'Открыть инструменты':'Open tools'} onClick={newTab}><ResourceIcon icon="plus"/></button><span>{connected?(ru?'Контекст проекта':'Project context'):(ru?'Нет связи · последний контекст':'Offline · last context')}</span>{agent.available&&<button type="button" disabled={!item?.draft.trim()} onClick={()=>{void copy();}} aria-label={ru?'Копировать запрос':'Copy request'}><ResourceIcon icon="copy" size={16}/></button>}{conversation?.busy?<button type="button" onClick={()=>{void agent.cancel(item!.id);}}>{ru?'Остановить':'Stop'}</button>:<button type="submit" disabled={!item?.draft.trim()||(agent.available&&!connected)}><ResourceIcon icon={agent.available?'assistant':'copy'} size={16}/>{agent.available?(ru?'Отправить':'Send'):copied?(ru?'Скопировано':'Copied'):(ru?'Копировать запрос':'Copy request')}</button>}</div>
      {(error||conversation?.error)&&<p role="alert">{error||conversation?.error}</p>}
    </form>
  </section>;
}
