import { useEffect, useState } from 'react';
import type { Locale } from '../core';
import type { ProjectResource, ResourceCatalog } from '../core/resources';
import { api } from './api';
import { ResourceIcon } from './icons';
import type { CreationTemplate } from './entity-palette';
import './workspace-library.css';
type Template = CreationTemplate;
export function EquipmentCatalog({locale,catalog,open,create,plugins,operator,compact=false}:{locale:Locale;catalog:ResourceCatalog;open:(resource:ProjectResource,editor:'diagram'|'source')=>void;create:(template:CreationTemplate)=>void;plugins:()=>void;operator:boolean;compact?:boolean}) {
  const ru=locale==='ru',[templates,setTemplates]=useState<Template[]>([]),[error,setError]=useState(''),[query,setQuery]=useState(''),[tab,setTab]=useState<'project'|'templates'>(compact?'templates':'project');
  useEffect(()=>{void api<Template[]>('templates').then(setTemplates).catch(e=>setError(String(e)));},[]);
  const equipment=catalog.resources.filter(item=>item.kind==='device'),match=(text:string)=>text.toLocaleLowerCase().includes(query.toLocaleLowerCase());
  const visible=equipment.filter(item=>match(`${item.name.ru} ${item.name.en} ${item.entityId} ${item.source?.path??''}`));
  return <section className={`workspace-library equipment-catalog${compact?' compact':''}`} aria-label={ru?'Каталог оборудования':'Equipment catalog'}><header><div><h1>{ru?'Каталог оборудования':'Equipment catalog'}</h1><p>{ru?'Оборудование объекта и исходные шаблоны для новых устройств.':'Project equipment and source templates for new devices.'}</p></div>{!operator&&<button onClick={plugins}><ResourceIcon icon="plugin" size={17}/>{ru?'Расширения':'Extensions'}</button>}</header>
    <div className="library-controls"><div className="library-tabs" role="tablist" aria-label={ru?'Разделы каталога':'Catalog sections'}><button role="tab" aria-selected={tab==='project'} onClick={()=>setTab('project')}>{ru?'В проекте':'In project'} · {equipment.length}</button>{!operator&&<button role="tab" aria-selected={tab==='templates'} onClick={()=>setTab('templates')}>{ru?'Шаблоны':'Templates'}</button>}</div><label className="library-search"><ResourceIcon icon="search"/><input aria-label={ru?'Поиск оборудования':'Search equipment'} placeholder={ru?'Найти оборудование…':'Find equipment…'} value={query} onChange={event=>setQuery(event.target.value)}/></label></div>
    {error&&<p role="alert" className="error-text">{error}</p>}
    <div className="library-list">{tab==='project'?visible.map(item=><article className="catalog-item" key={item.uri}><ResourceIcon icon={item.icon} size={28}/><div><strong>{item.name[locale]}</strong><small>{item.entityId}</small><small>{item.source?.path??(ru?'Объявлено фабрикой проекта':'Defined by a project factory')}</small></div><button aria-label={(ru?'На схеме: ':'Show in diagram: ')+item.name[locale]} onClick={()=>open(item,'diagram')}><ResourceIcon icon="diagram" size={16}/>{ru?'На схеме':'Diagram'}</button>{!operator&&item.source&&<button aria-label={(ru?'Код: ':'Code: ')+item.name[locale]} onClick={()=>open(item,'source')}><ResourceIcon icon="source" size={16}/>{ru?'Код':'Code'}</button>}</article>):templates.filter(item=>match(item.label[locale])).map(item=><article className="catalog-item" key={item.id}><ResourceIcon icon={item.icon} size={28}/><div><strong>{item.label[locale]}</strong><small>{item.id==='custom'?(ru?'Свой device() с 2D-заглушкой, без выдуманных портов':'Your own device() with a 2D placeholder, no invented ports'):(ru?'Базовый шаблон · требует адаптации под реальное устройство':'Starter template · adapt to the actual device')}</small></div><button aria-label={(ru?'Добавить: ':'Add: ')+item.label[locale]} onClick={()=>create(item)}><ResourceIcon icon="plus" size={17}/>{ru?'Добавить':'Add'}</button></article>)}</div>
    {compact&&!operator&&<button className="catalog-extensions-link" onClick={plugins}><ResourceIcon icon="plugin" size={17}/>{ru?'Исходные наборы оборудования':'Equipment source kits'}</button>}
    {tab==='project'&&!visible.length&&<p role="status">{ru?'Оборудование не найдено':'No equipment found'}</p>}
    {tab==='templates'&&<p className="library-notice">{ru?'Создание сначала показывает TypeScript. После подтверждения файл копируется в equipment/ и подключается явным импортом в project.ts. Дополнительные исходные наборы доступны через «Расширения».':'Creation previews TypeScript first, then writes a file in equipment/ with an explicit import in project.ts. Additional source kits are available through Extensions.'}</p>}
  </section>;
}
