import { useEffect, useMemo, useState } from 'react';
import {GitDiff} from './git-diff';
import type { GitReview,GitMeaning } from '../core/git';
import type { GitState } from '../core/git';
import type { Locale } from '../core';
import { api } from './api';
import './git-surface.css';
export function GitSurface({state,busy,dirty,locale,action}:{state:GitState|null;busy:boolean;dirty:boolean;locale:Locale;action:(action:string,message?:string,commit?:string)=>Promise<boolean>}){
  const ru=locale==='ru',[message,setMessage]=useState(''),[selected,setSelected]=useState(''),[preview,setPreview]=useState(''),[error,setError]=useState(''),[reviewed,setReviewed]=useState(false),[review,setReview]=useState<GitReview|null>(null),[reviewError,setReviewError]=useState(''),[restore,setRestore]=useState(false);
  useEffect(()=>{setRestore(false);setReview(null);setReviewError('');if(!state?.available)return;const abort=new AbortController();void api<GitReview>('git/review'+(selected?'?commit='+selected:''),undefined,abort.signal).then(setReview,e=>{if(!abort.signal.aborted)setReviewError(String(e));});return()=>abort.abort();},[selected,state]);
  useEffect(()=>{setPreview('');setReviewed(false);setError('');if(!selected||!restore)return;let live=true;api<{diff:string}>('git/preview?commit='+selected).then(r=>{if(live){setPreview(r.diff);setReviewed(true);}},e=>{if(live)setError(String(e));});return()=>{live=false;};},[selected,state?.head,restore]);
  const graph=useMemo(()=>{const slots:string[]=[],points=new Map<string,{x:number;y:number}>();let width=1;for(const [i,c] of (state?.commits??[]).entries()){let lane=slots.indexOf(c.hash);if(lane<0){lane=slots.indexOf('');if(lane<0)lane=slots.length;}points.set(c.hash,{x:12+lane*16,y:i*64+32});slots[lane]='';for(const [p,parent] of c.parents.entries()){if(slots.includes(parent))continue;let next=p===0?lane:slots.indexOf('');if(next<0)next=slots.length;slots[next]=parent;}width=Math.max(width,slots.length);}return {points,width:Math.max(36,width*16+14)};},[state?.commits]);
  if(!state)return <section className="git-surface">{ru?'Загрузка Git…':'Loading Git…'}</section>;
  if(!state.available)return <section className="git-surface"><button onClick={()=>void action('init')}>{ru?'Создать Git-репозиторий':'Initialize Git repository'}</button></section>;
  return <section className="git-surface git-workbench">
    <header><div><h1><span aria-hidden="true">⑂</span> {state.branch}</h1><p>{ru?'История исходников проекта':'Project source history'} · <code>{state.head.slice(0,9)||'—'}</code></p></div><div className="git-controls"><button disabled={busy} onClick={()=>void action('fetch')}>{ru?'Проверить изменения':'Fetch'}</button><button disabled={busy||dirty||!!state.status.trim()||!state.mainRef||state.behind===0||state.ahead>0} onClick={()=>void action('pull-main')}>Pull main {state.behind?`↓${state.behind}`:''}</button><button disabled={busy||!state.remotes} onClick={()=>void action('push')}>Push</button></div></header>
    <div className="git-sync" role="status">{state.mainRef?`${state.mainRef.replace('refs/remotes/','')} · ↑ ${state.ahead} / ↓ ${state.behind}`:(ru?'Удалённая main пока не найдена':'Remote main not found')}{state.ahead>0&&state.behind>0&&<span> · {ru?'Ветки разошлись — требуется merge в CLI':'Branches diverged — merge in CLI'}</span>}<small>{state.fetchedAt?new Date(state.fetchedAt).toLocaleString():(ru?'Состояние локальных refs; нажмите «Проверить изменения»':'Cached refs; Fetch to check the remote')}</small></div>
    <div className="git-columns"><div><div className="git-controls"><input aria-label={ru?'Описание коммита':'Commit message'} placeholder={ru?'Что изменено?':'What changed?'} value={message} onChange={e=>setMessage(e.target.value)}/><button disabled={busy||dirty||!message.trim()||!state.status.trim()} onClick={()=>void action('commit',message).then(ok=>{if(ok)setMessage('');})}>{ru?'Коммит':'Commit'}</button></div>
    {dirty&&<p className="muted">{ru?'Сначала сохраните открытые документы.':'Save open documents first.'}</p>}<div className="git-review-heading"><h3>{selected?(ru?'Изменения коммита':'Commit changes'):(ru?'Изменения проекта':'Project changes')}</h3>{selected&&<button onClick={()=>setSelected('')}>{ru?'Рабочая копия':'Working tree'}</button>}</div>
    {selected&&<p className="muted"><code>{review?(review.from?.slice(0,9)??'∅'):'…'} → {selected.slice(0,9)}</code> · {ru?'относительно первого родителя':'relative to first parent'}</p>}
    {reviewError?<p role="alert">{reviewError}</p>:!review?<p role="status">{ru?'Чтение изменений…':'Reading changes…'}</p>:<>
      <Meaning changes={review.changes} ru={ru}/>
      <p className="git-summary-note">{ru?'Сводка AST описывает явные объявления. Вычисляемая логика, импорты и остальные изменения доступны в diff.':'AST summary describes explicit declarations. Computed logic, imports and other changes remain in the diff.'}{review.limited&&<strong> {ru?'Объём предпросмотра ограничен.':'Preview size is limited.'}</strong>}</p>
      <details className="git-files" open={!review.changes.length}><summary>{ru?'Файлы':'Files'} · {review.files.length}</summary>{review.files.map(path=><code key={path}>{path}</code>)}</details>
      {review.diff?<GitDiff diff={review.diff} label={ru?'Изменения исходников':'Source diff'}/>:<p className="muted">{review.files.length?(ru?'Новые или двоичные файлы перечислены выше.':'New or binary files are listed above.'):(ru?'Изменений нет':'No changes')}</p>}
    </>}
    {selected&&selected!==state.head&&!restore&&<button className="git-restore-start" onClick={()=>setRestore(true)}>{ru?'Сравнить с текущей для восстановления…':'Compare with current for restore…'}</button>}
    {selected&&restore&&<div className="git-restore"><h3>{ru?'Восстановить версию':'Restore version'} <code>{selected.slice(0,9)}</code></h3><p>{ru?'Ниже изменения от текущей HEAD к выбранной версии. Они будут сохранены новым коммитом; применение сборки выполняется отдельно.':'Below are changes from current HEAD to the selected version. They become a new commit; applying a build is separate.'}</p>{error?<p role="alert">{error}</p>:preview?<GitDiff diff={preview} label={ru?'Изменения восстановления':'Restore diff'}/>:<p>{reviewed?(ru?'Изменений нет':'No changes'):'…'}</p>}<button disabled={busy||dirty||!!state.status.trim()||!reviewed||!preview} onClick={()=>void action('restore',undefined,selected)}>{ru?'Восстановить новым коммитом':'Restore as a new commit'}</button></div>}</div>
    <div><h3>{ru?'Граф коммитов':'Commit graph'} <small>{state.commits.length} / 60</small></h3><div className="git-graph" style={{paddingLeft:graph.width}}><svg aria-hidden="true" width={graph.width} height={state.commits.length*64}>
      {state.commits.map(c=>{const a=graph.points.get(c.hash)!;return <g key={c.hash}>{c.parents.map(parent=>{const b=graph.points.get(parent)??{x:a.x,y:state.commits.length*64};return <path key={parent} d={`M${a.x},${a.y} C${a.x},${a.y+24} ${b.x},${b.y-24} ${b.x},${b.y}`} fill="none" stroke="var(--accent)" opacity=".5"/>;})}<circle cx={a.x} cy={a.y} r={4} fill={c.hash===state.head?'var(--accent)':'var(--panel)'} stroke="var(--accent)"/></g>;})}</svg>
      {state.commits.map(c=><button key={c.hash} className={`git-commit${selected===c.hash?' selected':''}`} onClick={()=>setSelected(c.hash)} title={c.hash} aria-pressed={selected===c.hash}><span className="git-avatar" title={`${c.name} <${c.email}>`} style={{background:`hsl(${[...c.email].reduce((n,c)=>n+c.charCodeAt(0)*13,0)%360} 28% 35%)`}}>{c.name.split(/\s+/).map(w=>w[0]).slice(0,2).join('').toUpperCase()}</span><span><strong>{c.subject}</strong><small>{c.name} · {new Date(c.date).toLocaleDateString()} · {c.hash.slice(0,7)}</small>{c.refs&&<em>{c.refs}</em>}</span></button>)}
    </div><p className="muted">{ru?'Все ветки репозитория. Линии внизу продолжаются за пределами последних 60 коммитов. Аватары — инициалы авторов.':'All repository branches. Bottom edges continue beyond the latest 60 commits. Avatars show author initials.'}</p></div></div>
  </section>;
}

function Meaning({changes,ru}:{changes:GitMeaning[];ru:boolean}){
 const kinds:Record<GitMeaning['kind'],[string,string]>={equipment:['Оборудование','Equipment'],signal:['Сигнал','Signal'],connection:['Соединение','Connection'],alarm:['Тревога','Alarm'],report:['Отчёт','Report'],hmi:['Экран HMI','HMI screen'],project:['Проект','Project']};
 const verbs={added:ru?'Добавлено':'Added',removed:ru?'Удалено':'Removed',changed:ru?'Изменено':'Changed',renamed:ru?'Переименовано':'Renamed'};
 const fields:Record<string,[string,string]>={x:['Положение X','Position X'],y:['Положение Y','Position Y'],above:['Порог','Threshold'],hysteresis:['Гистерезис','Hysteresis'],from:['Откуда','From'],to:['Куда','To'],label:['Название','Name'],bucketMs:['Интервал, мс','Interval, ms'],window:['Окно, мс','Window, ms'],'$factory':['Тип объявления','Declaration type'],'$file':['Файл','File'],initial:['Начальное значение','Initial value'],writable:['Разрешение команд','Commands allowed']};
 return <div className="git-meaning" aria-label={ru?'Смысл изменений':'Meaning of changes'}>{changes.map((change,index)=><article key={index} className={change.type}><header><span>{verbs[change.type]}</span><strong>{kinds[change.kind][ru?0:1]} · {change.id}</strong></header>{change.fields.map(field=><div className="git-field-change" key={field.name}><span>{fields[field.name]?.[ru?0:1]??field.name}</span><del>{field.before??'—'}</del><span aria-hidden="true">→</span><ins>{field.after??'—'}</ins></div>)}<small>{change.path}</small></article>)}</div>;
}
