import type {ReactNode} from 'react';
import { useState } from 'react';
import { text, type Project, type Locale } from '../core';
import { api } from './api';
export function HmiSurface({renderScreen,project,authoringProject,appliedRevision,locale,refresh,inspect}:{renderScreen?:(id:string)=>ReactNode;project:Project;authoringProject?:Project;appliedRevision?:string;locale:Locale;refresh:()=>Promise<void>;inspect:(id:string)=>void}) {
  const authoringDevices=authoringProject?.equipment??project.equipment;
  const ru=locale==='ru',[creating,setCreating]=useState(false),[id,setId]=useState('operator'),[label,setLabel]=useState(ru?'Пульт оператора':'Operator panel'),[width,setWidth]=useState(1280),[height,setHeight]=useState(720),[ids,setIds]=useState(authoringDevices.map(e=>e.id)),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<{path:string;source:string;projectSource:string;projectVersion:string}|null>(null);
  const screens=appliedRevision===''?[]:[...(project.hmi?[{...project.hmi,id:'default',label:ru?'Экран контроллера':'Controller screen'}]:[]),...(project.hmis??[])];
  const create=async()=>{setBusy(true);setError('');try{const body={id,label,width,height,devices:ids};if(!preview)setPreview(await api('hmi/create',body));else{await api('hmi/create',{...body,apply:true,projectVersion:preview.projectVersion});await refresh();setCreating(false);setPreview(null);}}catch(e){setError(String(e));setPreview(null);}finally{setBusy(false);}};
  return <section className="hmi-surface"><div className="surface-description"><h2>{ru?'Интерфейсы оператора':'Operator interfaces'}</h2><p>{ru?'Галерея показывает применённые экраны. Новый HMI создаётся в исходниках из оборудования проверенной модели.':'The gallery shows Applied screens. A new HMI is authored from equipment in the Checked model.'}</p><button className="primary" onClick={()=>{setError('');setPreview(null);setIds(authoringDevices.map(e=>e.id));setCreating(true);}}>{ru?'Создать HMI':'Create HMI'}</button>{!screens.length&&<p className="detail-note" role="status">{ru?'В Applied пока нет экранов HMI. Создание файла само по себе не применяет экран.':'No HMI screens are Applied yet. Creating a file does not apply a screen.'}</p>}</div><div className="hmi-gallery">{screens.map(screen=><article key={screen.id}><header><button className="text-button" onClick={()=>inspect(screen.id)}>{text(screen.label??screen.id,locale)}</button><span>{screen.width} × {screen.height}</span>{!renderScreen&&<a href={`/hmi?screen=${encodeURIComponent(screen.id)}`} target="_blank" rel="noreferrer">{ru?'Открыть':'Open'} ↗</a>}</header>{renderScreen?<div className="hmi-inline-preview">{renderScreen(screen.id)}</div>:<iframe title={`HMI ${screen.id}`} src={`/hmi?screen=${encodeURIComponent(screen.id)}`} width={screen.width} height={screen.height}/>}</article>)}</div>
  {creating&&<div className="creation-backdrop"><section className="creation-dialog" role="dialog" aria-modal="true" aria-label={ru?'Создать HMI':'Create HMI'}><header><h2>{ru?'Новый экран HMI':'New HMI screen'}</h2><button type="button" aria-label={ru?'Закрыть':'Close'} disabled={busy} onClick={()=>{setCreating(false);setPreview(null);setError('');}}>×</button></header><form onSubmit={event=>{event.preventDefault();void create();}} onChange={()=>setPreview(null)}><div className="creation-fields"><label>ID<input required pattern="[A-Za-z][A-Za-z0-9_-]{0,63}" value={id} onChange={event=>setId(event.target.value)}/></label><label>{ru?'Название':'Name'}<input required maxLength={160} value={label} onChange={event=>setLabel(event.target.value)}/></label><label>{ru?'Ширина':'Width'}<input required type="number" min={1} max={8192} value={width} onChange={event=>setWidth(Number(event.target.value))}/></label><label>{ru?'Высота':'Height'}<input required type="number" min={1} max={8192} value={height} onChange={event=>setHeight(Number(event.target.value))}/></label></div><fieldset><legend>{ru?'Оборудование · Checked':'Equipment · Checked'}</legend>{authoringDevices.map(e=><label className="hmi-device-choice" key={e.id}><input type="checkbox" checked={ids.includes(e.id)} onChange={event=>setIds(previous=>event.target.checked?[...previous,e.id]:previous.filter(id=>id!==e.id))}/>{e.id} · {text(e.label,locale)}</label>)}</fieldset>{!ids.length&&<p className="error-text">{ru?'Выберите хотя бы одно устройство из проверенной модели для экрана.':'Select at least one device from the Checked model for this screen.'}</p>}{preview&&<div className="creation-preview"><strong>{ru?'Изменения в исходниках проекта':'Project source changes'}</strong><p>{ru?'Будет создан файл экрана и обновлён project.ts. Симулятор может обновить предпросмотр; применение к реальному объекту — отдельное действие.':'A screen file will be created and project.ts updated. The simulator may refresh its preview; applying to a real asset is a separate action.'}</p><details open><summary>{preview.path}</summary><pre>{preview.source}</pre></details><details><summary>project.ts</summary><pre>{preview.projectSource}</pre></details></div>}{error&&<p role="alert" className="error-text">{error}</p>}<footer><button className="primary" disabled={busy||!ids.length}>{busy?'…':preview?(ru?'Создать HMI в проекте':'Create HMI in project'):(ru?'Показать изменения':'Preview changes')}</button></footer></form></section></div>}
  </section>;
}
