import { useState } from 'react';
import { text, type Project, type Locale } from '../core';
import { api } from './api';
export function HmiSurface({project,locale,refresh}:{project:Project;locale:Locale;refresh:()=>Promise<void>}) {
  const ru=locale==='ru',[creating,setCreating]=useState(false),[id,setId]=useState('operator'),[label,setLabel]=useState(ru?'Пульт оператора':'Operator panel'),[width,setWidth]=useState(1280),[height,setHeight]=useState(720),[ids,setIds]=useState(project.equipment.map(e=>e.id)),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<{source:string;projectSource:string;projectVersion:string}|null>(null);
  const screens=[...(project.hmi?[{...project.hmi,id:'default',label:ru?'Экран контроллера':'Controller screen'}]:[]),...(project.hmis??[])];
  const create=async()=>{setBusy(true);setError('');try{const body={id,label,width,height,devices:ids};if(!preview)setPreview(await api('hmi/create',body));else{await api('hmi/create',{...body,apply:true,projectVersion:preview.projectVersion});await refresh();setCreating(false);setPreview(null);}}catch(e){setError(String(e));setPreview(null);}finally{setBusy(false);}};
  return <section className="hmi-surface"><div className="surface-description"><h2>{ru?'Интерфейсы оператора':'Operator interfaces'}</h2><p>{ru?'Каждый HMI — отдельный TS-файл с размером экрана и ссылками на оборудование проекта.':'Each HMI has its own TS file, screen size and references to project equipment.'}</p><button className="primary" onClick={()=>setCreating(true)}>{ru?'Создать HMI':'Create HMI'}</button></div><div className="hmi-gallery">{screens.map(screen=><article key={screen.id}><header><strong>{text(screen.label??screen.id,locale)}</strong><span>{screen.width} × {screen.height}</span><a href={`/hmi?screen=${encodeURIComponent(screen.id)}`} target="_blank" rel="noreferrer">{ru?'Открыть':'Open'} ↗</a></header><iframe title={`HMI ${screen.id}`} src={`/hmi?screen=${encodeURIComponent(screen.id)}`} width={screen.width} height={screen.height}/></article>)}</div>
  {creating&&<div className="creation-backdrop"><section className="creation-dialog" role="dialog" aria-modal="true" aria-label={ru?'Создать HMI':'Create HMI'}><header><h2>HMI</h2><button disabled={busy} onClick={()=>setCreating(false)}>×</button></header><form onSubmit={event=>{event.preventDefault();void create();}} onChange={()=>setPreview(null)}><div className="creation-fields"><label>ID<input value={id} onChange={event=>setId(event.target.value)}/></label><label>{ru?'Название':'Name'}<input value={label} onChange={event=>setLabel(event.target.value)}/></label><label>{ru?'Ширина':'Width'}<input type="number" value={width} onChange={event=>setWidth(Number(event.target.value))}/></label><label>{ru?'Высота':'Height'}<input type="number" value={height} onChange={event=>setHeight(Number(event.target.value))}/></label></div><fieldset><legend>{ru?'Оборудование':'Equipment'}</legend>{project.equipment.map(e=><label className="hmi-device-choice" key={e.id}><input type="checkbox" checked={ids.includes(e.id)} onChange={event=>setIds(previous=>event.target.checked?[...previous,e.id]:previous.filter(id=>id!==e.id))}/>{e.id} · {text(e.label,locale)}</label>)}</fieldset>{preview&&<pre className="creation-preview">{preview.source}</pre>}{error&&<p role="alert" className="error-text">{error}</p>}<footer><button className="primary" disabled={busy}>{busy?'…':preview?(ru?'Создать':'Create'):(ru?'Предпросмотр':'Preview')}</button></footer></form></section></div>}
  </section>;
}
