import {useState} from 'react';
import {diagnosePipeLeaks,equipmentCommands,equipmentSignals,text,type Project,type Snapshot,type Locale,type Text,type Value} from '../core';
import {Scene,type SceneProps} from './scene';
import {Symbol} from './symbols';
import {Control} from './controls';
import {PresentationView} from './presentation';
import {PipeInspection} from './pipe-inspection';
import './hmi-overview.css';
const fmt=(v:Value|null|undefined)=>v==null?'—':typeof v==='number'?Intl.NumberFormat(undefined,{maximumFractionDigits:2}).format(v):String(v);
export function HmiView({project,revision,snapshot,locale,connected,modeType,mode,modeBadge,scene,send,screenId='default',initialView=null}:{project:Project;revision:string;snapshot:Snapshot;locale:Locale;connected:boolean;modeType:string;mode:string;modeBadge:{tone:string};scene:SceneProps;send:(id:string,value:Value)=>Promise<void>;screenId?:string;initialView?:'overview'|'detail'|null}){
  const ru=locale==='ru';
  const [hmiEquipment,setHmiEquipment]=useState<string|null>(null),[hmiView,setHmiView]=useState<'overview'|'detail'|'pipes'|null>(initialView);
  const findings=diagnosePipeLeaks(project,snapshot,{now:Date.now(),connected});
  const suspected=findings.filter(finding=>finding.state==='suspected').length;
  const pipeAccess=project.pipes.length>0?<button type="button" className="hmi-pipe-nav" data-suspected={suspected>0||undefined} onClick={()=>setHmiView('pipes')}>{suspected>0?(ru?`⚠ Трубы · ${suspected} подозр.`:`⚠ Pipes · ${suspected} suspect`):(ru?'Трубопроводы':'Pipes')}</button>:null;
    if(!revision)return <main className="empty-state"><h1>HMI</h1><p>{ru?'Экран оператора ожидает применения сборки. Исходник экрана можно проверить в проекте.':'The operator screen awaits an Applied build. Its source can be reviewed in the project.'}</p></main>;
    const requested=screenId,screen=requested==='default'?project.hmi:project.hmis?.find(h=>h.id===requested);
    if(requested!=='default'&&!screen)return <main className="empty-state"><h1>HMI</h1><p>{ru?'Интерфейс не найден':'Interface not found'}</p></main>;
    if(hmiView==='pipes')return <PipeInspection project={project} scene={scene} findings={findings} locale={locale} connected={connected} mode={mode} back={()=>setHmiView(null)}/>;
    if(screen?.elements?.length){const screenLabel='label' in screen?text((screen as {label?:Text}).label??requested,locale):requested;return <main className="hmi imported-presentation"><header><strong>{screenLabel}</strong>{pipeAccess}<span className={`status ${modeBadge.tone==='faulted'?'faulted':modeType==='simulation'?'simulation':''}`}>{modeBadge.tone==='faulted'?(ru?'Ошибка исполнения':'Runtime faulted'):connected?mode:ru?'Нет связи':'Disconnected'}</span></header><PresentationView screen={screen} snapshot={snapshot} locale={locale}/></main>;}
    const devices = screen ? screen.equipment.flatMap(configured=>{const equipment=project.equipment.find(e=>e.id===configured.id);return equipment?[equipment]:[];}) : project.equipment;
    const index = Math.max(0, devices.findIndex(e => e.id === hmiEquipment)), shown = devices[index], commands = shown ? equipmentCommands(shown) : [];
    const overview = hmiView ?? (devices.length>4?'overview':'detail');
    if(overview==='overview')return <main className="hmi hmi-overview" data-hmi-view="overview"><header><strong>{screen&&'label' in screen?text((screen as {label?:Text}).label??requested,locale):project.label?text(project.label,locale):project.id}</strong>{pipeAccess}<span className={`status ${modeBadge.tone==='faulted'?'faulted':modeType==='simulation'?'simulation':''}`}>{modeBadge.tone==='faulted'?(ru?'Ошибка исполнения':'Runtime faulted'):connected?mode:ru?'Нет связи':'Disconnected'}</span></header>
      <section className="hmi-overview-body" aria-label={ru?'Состояние оборудования':'Equipment overview'}><div className="hmi-overview-heading"><div><h1>{ru?'Состояние оборудования':'Equipment status'}</h1><p>{ru?'Выберите оборудование, чтобы открыть его схему и команды.':'Select equipment to open its diagram and commands.'}</p></div><span>{devices.length} {ru?'ед. оборудования':'devices'}</span></div>
        <div className="hmi-device-grid">{devices.map(device=>{const allReadings=equipmentSignals(device).filter(item=>!item.writable),readings=allReadings.slice(0,4),diagram=device.capabilities.diagram;return <button type="button" className="hmi-device-card" data-hmi-equipment={device.id} key={device.id} onClick={()=>{setHmiEquipment(device.id);setHmiView('detail');}}><span className="hmi-device-id">{device.id}</span><strong>{text(device.label,locale)}</strong><span className="hmi-device-kind">{device.kind}</span>{device.capabilities.instrument&&diagram&&<svg className="hmi-instrument-preview" viewBox={`0 0 ${diagram.width} ${diagram.height}`} aria-label={`${device.id} · ${ru?'прибор':'instrument'}`}><Symbol equipment={device} snapshot={snapshot} locale={locale}/></svg>}{readings.length?<dl>{readings.map(item=>{const sample=snapshot.samples[item.id];const healthy=connected&&sample?.quality==='good';const quality=healthy?(ru?'Актуально':'Current'):sample?.quality==='stale'?(ru?'Устарело':'Stale'):sample?.quality==='bad'?(ru?'Ошибка':'Bad'):(ru?'Нет данных':'No data');return <div key={item.id}><dt>{text(item.label??item.id,locale)}</dt><dd className={healthy?'good':'unavailable'} title={quality}>{fmt(sample?.value??null)} <small>{item.unit??''}</small></dd></div>;})}</dl>:<span className="hmi-device-empty">{ru?'Нет измерений':'No measurements'}</span>}{allReadings.length>readings.length&&<span className="hmi-device-kind">{ru?`Ещё сигналов: ${allReadings.length-readings.length}`:`${allReadings.length-readings.length} more signals`}</span>}{equipmentCommands(device).length>0&&<span className="hmi-device-action">{ru?'Открыть команды':'Open controls'} →</span>}</button>;})}</div>
      </section><footer><span className="hmi-equipment-position">{screen&&'label' in screen?text((screen as {label?:Text}).label??requested,locale):project.id}</span></footer></main>;
    return <main className="hmi"><header><strong>{shown?.id ?? 'HMI'}</strong>{pipeAccess}<span className={`status ${modeBadge.tone==='faulted'?'faulted':modeType==='simulation'?'simulation':''}`}>{modeBadge.tone==='faulted'?(ru?'Ошибка исполнения':'Runtime faulted'):connected ? mode : ru ? 'Нет связи' : 'Disconnected'}</span></header>
      <Scene {...scene} selected={shown?.id??''} select={id=>setHmiEquipment(id)} focus={shown?.id} begin={undefined} move={undefined} end={undefined}/>
      {commands.length>0&&<section className="hmi-commands" aria-label={ru?'Команды оборудования':'Equipment commands'}>{commands.map(command=><div className="hmi-command" key={command.id} data-command={command.id} role="group" aria-label={text(command.label??command.id,locale)}><strong>{text(command.label??command.id,locale)}</strong><Control signal={command} sample={snapshot.samples[command.id]} locale={locale} enabled={connected} send={send}/></div>)}</section>}
      <footer>{devices.length>4&&<button onClick={()=>setHmiView('overview')}>{ru?'Обзор системы':'System overview'}</button>}<button aria-label={ru?'Предыдущее оборудование':'Previous equipment'} disabled={devices.length < 2} onClick={() => setHmiEquipment(devices[(index + devices.length - 1) % devices.length]!.id)}>←</button>
      <span className="hmi-equipment-position">{shown?`${text(shown.label,locale)} · ${index+1}/${devices.length}`:(ru?'Нет оборудования':'No equipment')}</span><button aria-label={ru?'Следующее оборудование':'Next equipment'} disabled={devices.length < 2} onClick={() => setHmiEquipment(devices[(index + 1) % devices.length]!.id)}>→</button></footer></main>;
}
