import { quickViews } from './model/navigation-catalog';
import { useState, type ReactNode } from 'react';
import type { Locale } from '../core';
import { ResourceIcon } from './icons';
import { IDEUpdates } from './ide-updates';
import { DemoProjects } from './preset-welcome';
import type { useInterfacePreferences } from './use-interface-preferences';

export type SettingsSection='general'|'appearance'|'notifications'|'shortcuts'|'about';
const sections:readonly {id:SettingsSection;icon:string;ru:string;en:string}[]=[
  {id:'general',icon:'settings',ru:'Основные',en:'General'},
  {id:'appearance',icon:'sun',ru:'Оформление',en:'Appearance'},
  {id:'notifications',icon:'bell',ru:'Уведомления',en:'Notifications'},
  {id:'shortcuts',icon:'keyboard',ru:'Горячие клавиши',en:'Keyboard shortcuts'},
  {id:'about',icon:'info',ru:'О Saturn',en:'About Saturn'},
];
export function SettingsNavigation({locale,section,select,plugins}:{locale:Locale;section:SettingsSection;select:(section:SettingsSection)=>void;plugins:()=>void}){
  const [query,setQuery]=useState(''),ru=locale==='ru';
  const items=sections.filter(item=>(ru?item.ru:item.en).toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  return <nav className="settings-navigation" aria-label={ru?'Разделы настроек':'Settings sections'}><h1>{ru?'Настройки':'Settings'}</h1><label className="settings-search"><ResourceIcon icon="search" size={16}/><input aria-label={ru?'Поиск настроек':'Search settings'} placeholder={ru?'Поиск':'Search'} value={query} onChange={event=>setQuery(event.target.value)}/></label><p>{ru?'Интерфейс':'Interface'}</p>{items.map(item=><button key={item.id} aria-current={section===item.id?'page':undefined} onClick={()=>select(item.id)}><ResourceIcon icon={item.icon}/>{ru?item.ru:item.en}</button>)}{!items.length&&<small>{ru?'Совпадений нет':'No matches'}</small>}<p>{ru?'Интеграции':'Integrations'}</p><button onClick={plugins}><ResourceIcon icon="plugin"/>{ru?'Плагины проекта':'Project plugins'}<ResourceIcon icon="chevron-right" size={14}/></button></nav>;
}
function Row({title,description,children}:{title:string;description?:string;children:ReactNode}){return <div className="settings-row"><div><strong>{title}</strong>{description&&<p>{description}</p>}</div>{children}</div>;}
export function InterfaceSettings({preferences,section,notify}:{preferences:ReturnType<typeof useInterfacePreferences>;section:SettingsSection;notify:()=>Promise<void>}){
  const {locale,language,setLanguage,theme,setTheme,homeIcon,setHomeIcon,homeDimension,setHomeDimension,accent,setAccent,preset,selectPreset}=preferences,ru=locale==='ru';
  const [permission,setPermission]=useState(()=>typeof Notification==='undefined'?'unavailable':Notification.permission);
  return <section className="interface-settings" aria-label={ru?'Настройки интерфейса':'Interface settings'}><h1>{sections.find(item=>item.id===section)![ru?'ru':'en']}</h1>
    {section==='general'&&<><h2>{ru?'Интерфейс':'Interface'}</h2><div className="settings-card"><Row title={ru?'Язык':'Language'} description={ru?'Язык интерфейса Saturn.':'Language used throughout Saturn.'}><select aria-label={ru?'Язык интерфейса':'Interface language'} value={language} onChange={event=>setLanguage(event.target.value as typeof language)}><option value="system">{ru?'Автоматически':'Auto detect'}</option><option value="ru">Русский</option><option value="en">English</option></select></Row><Row title={ru?'Главная страница':'Home view'} description={ru?'В каком виде открывать объект по кнопке Home.':'The object view opened by Home.'}><select aria-label={ru?'Вид Home':'Home view'} value={homeDimension} onChange={event=>setHomeDimension(event.target.value as typeof homeDimension)}><option value="3d">3D</option><option value="2d">2D</option></select></Row></div><p className="settings-note">{ru?'Настройки интерфейса сохраняются в этом браузере. Параметры объекта редактируются в проекте.':'Interface preferences are saved in this browser. Object parameters are authored in the project.'}</p></>}
    {section==='appearance'&&<><h2>{ru?'Внешний вид':'Visual style'}</h2><div className="settings-card"><Row title={ru?'Пресет интерфейса':'Interface preset'} description={ru?'Стартовое меню и быстрые переходы. Смена пресета не заменяет проект.':'Starting menu and quick links. Changing the preset does not replace the project.'}><select aria-label={ru?'Пресет интерфейса':'Interface preset'} value={preset??'business'} onChange={event=>selectPreset(event.target.value as 'home'|'business')}><option value="home">{ru?'Для дома':'For home'}</option><option value="business">{ru?'Для бизнеса':'For business'}</option></select></Row><Row title={ru?'Режим':'Mode'}><div className="theme-options">{(['system','light','dark'] as const).map(value=><button key={value} className={'theme-preview '+value} aria-pressed={theme===value} onClick={()=>setTheme(value)}><span aria-hidden="true"><i/><b/><b/><b/></span>{value==='system'?(ru?'Системный':'System'):value==='light'?(ru?'Светлый':'Light'):(ru?'Тёмный':'Dark')}</button>)}</div></Row><Row title={ru?'Цвет акцента':'Accent'} description={ru?'Цвет навигации и элементов управления. Цвета тревог и сигналов сохраняют свой смысл.':'Navigation and control color. Alarm and signal colors retain their meaning.'}><select aria-label={ru?'Цвет акцента':'Accent color'} value={accent} onChange={event=>setAccent(event.target.value as typeof accent)}><option value="blue">{ru?'Синий':'Blue'}</option><option value="teal">{ru?'Бирюзовый':'Teal'}</option><option value="orange">{ru?'Оранжевый':'Orange'}</option></select></Row><Row title={ru?'Иконка Home':'Home icon'} description={ru?'Дом или сооружение — для домашнего и промышленного объекта.':'House or site, for home and industrial projects.'}><div className="home-icon-options">{(['home','site'] as const).map(value=><button key={value} aria-pressed={homeIcon===value} onClick={()=>setHomeIcon(value)}><ResourceIcon icon={value} size={23}/>{value==='home'?(ru?'Дом':'House'):(ru?'Сооружение':'Site')}</button>)}</div></Row></div><DemoProjects locale={locale} preset={preset??'business'}/></>}
    {section==='notifications'&&<><h2>{ru?'Этот браузер':'This browser'}</h2><div className="settings-card"><Row title={ru?'Web Push':'Web Push'} description={ru?'Уведомления от подключённого сервера объекта.':'Notifications from the connected object server.'}><button onClick={async()=>{await notify();setPermission(typeof Notification==='undefined'?'unavailable':Notification.permission);}}>{ru?'Подключить':'Enable'}</button></Row><Row title={ru?'Разрешение браузера':'Browser permission'}><span>{permission==='granted'?(ru?'Разрешено':'Allowed'):permission==='denied'?(ru?'Заблокировано':'Blocked'):permission==='unavailable'?(ru?'Недоступно':'Unavailable'):(ru?'Не запрошено':'Not requested')}</span></Row></div></>}
    {section==='shortcuts'&&<div className="settings-card">{[
      ['Alt 1',ru?'Главная':'Home'],...quickViews(preset).map((view,index)=>[`Alt ${index+2}`,view.label[locale]]),
      ['⌘ / Ctrl K',ru?'Найти и открыть':'Find and open'],['⌘ / Ctrl ,',ru?'Настройки':'Settings'],['⌘ / Ctrl [',ru?'Назад':'Back'],['⌘ / Ctrl ]',ru?'Вперёд':'Forward'],['⌘ / Ctrl B',ru?'Показать проводник':'Toggle explorer'],['⌘ / Ctrl S',ru?'Сохранить исходник':'Save source'],['⌘ / Ctrl J',ru?'Нижняя панель':'Bottom panel'],['⌘ / Ctrl ⇧ T',ru?'Новая вкладка':'New tab'],['⌘ / Ctrl ⇧ B',ru?'Правая панель чата':'Chat tool pane'],['⌘ / Ctrl ⇧ F',ru?'Развернуть панель чата':'Expand chat tool pane'],
    ].map(([shortcut,title])=><Row key={shortcut} title={title!}><kbd>{shortcut}</kbd></Row>)}</div>}
    {section==='about'&&<><p className="settings-note">{ru?'Инженерное рабочее место для объекта, его модели и исполнения.':'An engineering workspace for the object, its model and execution.'}</p><IDEUpdates locale={locale}/></>}
  </section>;
}
