import {MenuButton} from './menu';
import { useEffect, useRef, useState } from 'react';
import { text, type Locale, type Project } from '../core';
import {outputCsv,reportHtml,type ReportOutput} from '../core/report-output';
import { api,browserClient } from './api';
import {ReportDocument} from './report-document';
import './reports.css';
const aggregateLabels = {
  mean: { ru: 'среднее по времени', en: 'time-weighted mean' },
  min: { ru: 'минимум', en: 'minimum' },
  max: { ru: 'максимум', en: 'maximum' },
  integral: { ru: 'интеграл', en: 'integral' },
  last: { ru: 'последнее', en: 'latest' },
} as const;
const fieldLabels = {
  number: { ru: 'число', en: 'number' }, boolean: { ru: 'логическое', en: 'boolean' },
  string: { ru: 'текст', en: 'text' }, datetime: { ru: 'дата и время', en: 'date and time' },
} as const;
const stableJson=(value:unknown):string=>JSON.stringify(value,(_key,item:unknown)=>item&&typeof item==='object'&&!Array.isArray(item)?Object.fromEntries(Object.entries(item).sort(([left],[right])=>left.localeCompare(right))):item);
export function Reports({project,authoringProject,appliedRevision,locale,selected,onSelect}:{project:Project;authoringProject?:Project;appliedRevision?:string;locale:Locale;selected:string;onSelect:(id:string)=>void}) {
  const ru=locale==='ru',definitions=authoringProject?(authoringProject.reports??[]):(project.reports??[]);
  const [hours,setHours]=useState(6),[result,setResult]=useState<ReportOutput|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [inputs,setInputs]=useState<Record<string,number>>({});const printed=useRef<HTMLIFrameElement|null>(null);
  const request=useRef<AbortController|null>(null);
  const id=selected||(definitions[0]?.id??'');
  const definition=definitions.find(report=>report.id===id);
  const appliedDefinition=project.reports?.find(report=>report.id===id);
  // Report generation belongs to runtime. A Checked definition with the same ID can
  // still differ from the one currently Applied, so ID equality is insufficient.
  const availability=!definition?'unavailable':appliedRevision===''||!appliedDefinition?'pending':stableJson(definition)===stableJson(appliedDefinition)?'ready':'changed';
  const inputsValid=!definition||!('sql' in definition)||Object.entries(definition.inputs??{}).every(([key,d])=>Number.isFinite(inputs[key]??d.default)&&(inputs[key]??d.default)>=d.min&&(inputs[key]??d.default)<=d.max);
  useEffect(()=>{request.current?.abort();setResult(null);setError('');setBusy(false);setInputs({});if(definition&&'sql' in definition)setHours(definition.window/3600000);return()=>request.current?.abort();},[id,project,authoringProject]);
  useEffect(()=>{request.current?.abort();setResult(null);setBusy(false);setError('');},[hours,inputs]);
  const run=async()=>{
    if(availability!=='ready')return;
    request.current?.abort();const controller=new AbortController();request.current=controller;setBusy(true);setError('');setResult(null);
    const to=Date.now(),from=to-hours*3600_000;
    try {const next=await api<ReportOutput>(`report?id=${encodeURIComponent(id)}&from=${from}&to=${to}&inputs=${encodeURIComponent(JSON.stringify(inputs))}`,undefined,controller.signal);if(!controller.signal.aborted)setResult(next);}
    catch(e){if(!controller.signal.aborted)setError(String(e));}finally{if(!controller.signal.aborted)setBusy(false);}
  };
  const exportFile=(format:'csv'|'xlsx'|'html')=>{if(!result)return;if(format==='csv'){download();return;}if(!result.artifactId){setError(ru?'Сохранённый артефакт отчёта отсутствует.':'Persisted report artifact is unavailable.');return;}void browserClient.exportReport(result.artifactId,format,locale).then(blob=>{const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${result.id}.${format}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}).catch(reason=>setError(String(reason)));};
  const download=()=>{if(!result)return;const url=URL.createObjectURL(new Blob([outputCsv(result,locale)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${result.id}-${new Date(result.to).toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  if(!definitions.length)return <div className="empty-state"><h2>{ru?'Отчёты проекта':'Project reports'}</h2><p>{ru?'Добавьте report() в project.reports. Колонки ссылаются на типизированные сигналы.':'Add report() to project.reports. Columns reference typed signals.'}</p></div>;
  return <section className="reports-surface">
    <div className="report-controls no-print"><label className="report-control-field">{ru?'Отчёт':'Report'}<select aria-label={ru?'Отчёт':'Report'} value={id} onChange={e=>onSelect(e.target.value)}>{!definition&&<option value={id}>{ru?'Отчёт отсутствует в Checked':'Report is absent from Checked'}</option>}{definitions.map(r=><option key={r.id} value={r.id}>{text(r.label,locale)}</option>)}</select></label><label className="report-control-field">{ru?'Период':'Period'}<select aria-label={ru?'Период':'Period'} value={hours} onChange={e=>setHours(Number(e.target.value))}>{[...new Set([...(definition&&'sql' in definition?[definition.window/3600000]:[]),1,6,12,24])].sort((a,b)=>a-b).map(h=><option key={h} value={h}>{h} {ru?'ч':'h'}</option>)}</select></label><button className="primary" disabled={busy||!inputsValid||availability!=='ready'} onClick={()=>void run()}>{busy?(ru?'Формирование…':'Generating…'):ru?'Сформировать':'Generate'}</button>{'sql' in (definition??{})&&Object.entries((definition as import('../core').QueryReport).inputs??{}).map(([key,d])=><label key={key}>{text(d.label??key,locale)} <input aria-label={key} type="number" min={d.min} max={d.max} step="any" value={inputs[key]??d.default} onChange={e=>setInputs({...inputs,[key]:Number(e.target.value)})}/></label>)}<MenuButton className="report-export" label={ru?'Экспорт отчёта':'Export report'} disabled={!result} items={[{id:'xlsx',label:'Excel (.xlsx)',icon:'report',run:()=>exportFile('xlsx')},{id:'csv',label:'CSV',icon:'file',run:()=>exportFile('csv')},{id:'html',label:'HTML',icon:'docs',run:()=>exportFile('html')},{id:'print',label:ru?'Печать':'Print',divider:true,run:()=>{if(printed.current)printed.current.contentWindow?.print();else window.print();}}]}>{ru?'Экспорт':'Export'}</MenuButton></div>
    {availability!=='ready'&&<div className="report-feedback report-pending" role="status"><strong>{availability==='pending'?(ru?'Отчёт ожидает применения':'Report awaits apply'):availability==='changed'?(ru?'Определение отчёта изменено в Checked':'Report definition changed in Checked'):(ru?'Отчёт недоступен в Checked':'Report unavailable in Checked')}</strong><p>{availability==='pending'?(ru?'Этот отчёт есть в проверенной модели, но отсутствует в применённой сборке. После публикации и применения можно сформировать его по архиву.':'This report exists in Checked but not in Applied. Publish and apply the build before generating it from the archive.'):availability==='changed'?(ru?'В Applied находится другое определение с тем же ID. Сформировать отчёт можно после применения проверенной сборки.':'Applied contains a different definition with the same ID. Apply the Checked build before generating this report.'):ru?'Выберите отчёт из проверенной модели проекта.':'Choose a report from the Checked project model.'}</p></div>}
    {!inputsValid&&<p className="error-text" role="alert">{ru?'Параметры должны быть в указанных границах.':'Parameters must be within their allowed ranges.'}</p>}
    {error&&<div className="report-feedback error-text" role="alert"><strong>{ru?'Не удалось сформировать отчёт':'Report generation failed'}</strong><details><summary>{ru?'Подробнее':'Details'}</summary><code>{error}</code></details><p>{ru?'Проверьте параметры и доступность архива, затем повторите запрос.':'Check the parameters and archive availability, then try again.'}</p></div>}
    {busy&&<div className="report-preview report-loading" role="status"><span className="report-preview-eyebrow">{ru?'АРХИВНЫЙ ОТЧЁТ':'ARCHIVE REPORT'}</span><h2>{ru?'Формирование отчёта…':'Generating report…'}</h2><p>{ru?'Читаем сохранённые измерения за выбранный период. Результат появится здесь после завершения.':'Reading persisted observations for the selected period. The result will appear here when ready.'}</p></div>}
    {!result&&!busy&&!error&&definition&&<div className="report-preview"><span className="report-preview-eyebrow">{ru?'ПОДГОТОВКА ОТЧЁТА':'REPORT SETUP'}</span><h2>{text(definition.label,locale)}</h2><p>{'sql' in definition ? (ru?`Период: последние ${hours} ч. Обработка пропусков задана в определении этого отчёта.`:`Period: last ${hours} h. Missing-data handling is defined by this report.`) : (ru?`Период: последние ${hours} ч. Отчёт использует архив измерений; пропуски не заменяются нулями.`:`Period: last ${hours} h. The report uses recorded observations; missing values are not replaced with zero.`)}</p><h3>{ru?'Колонки результата':'Result columns'}</h3><div className="report-preview-columns">{'sql' in definition?definition.columns.map(c=><div key={c.key}><strong>{text(c.title,locale)}</strong><span>{c.key} · {fieldLabels[definition.schema[c.key]?.type ?? 'string'][locale]}{c.unit?` · ${c.unit}`:''}</span></div>):Object.entries(definition.columns).map(([key,column])=><div key={key}><strong>{text(column.label,locale)}</strong><span>{column.signal.id} · {aggregateLabels[column.aggregate][locale]} · {column.unit??column.signal.unit??'—'}</span></div>)}</div></div>}
    {result&&('kind' in result?browserClient.embedded?<ReportDocument html={reportHtml(result,locale)}/>:<iframe ref={printed} className="report-document" title={ru?'Документ отчёта':'Report document'} sandbox="allow-same-origin allow-modals" srcDoc={reportHtml(result,locale)}/>:<article className="report-page"><header><div className="report-brand">Saturn <span>{text(project.label,locale)}</span></div><h1>{text(result.label,locale)}</h1><p>{new Date(result.from).toISOString().replace('T',' ').slice(0,19)} — {new Date(result.to).toISOString().replace('T',' ').slice(0,19)} UTC</p></header>
      {!result.rows.length&&<p className="report-empty-result">{ru?'За выбранный период нет строк отчёта. Уточните период или проверьте архив.':'No report rows for this period. Adjust the range or inspect the archive.'}</p>}
      <table className="report-table"><thead><tr><th>{ru?'Интервал, UTC':'Interval, UTC'}</th>{Object.entries(result.columns).map(([key,col])=><th key={key}>{text(col.label,locale)}<small>{col.unit??col.signal.unit} · {aggregateLabels[col.aggregate][locale]}</small></th>)}</tr></thead><tbody>{result.rows.map(row=><tr key={row.from}><td><time>{new Date(row.from).toISOString().slice(11,16)}</time> — <time>{new Date(row.to).toISOString().slice(11,16)}</time></td>{Object.keys(result.columns).map(key=><td key={key} data-coverage={row.coverage[key]}><strong>{row.values[key]===null?'—':typeof row.values[key]==='number'?Intl.NumberFormat(locale,{maximumFractionDigits:3}).format(row.values[key] as number):String(row.values[key])}</strong><small className={(row.coverage[key]??0)<.99?'partial':''}>{ru?'Покрытие периода':'Period covered'} {Math.round((row.coverage[key]??0)*100)}%</small></td>)}</tr>)}</tbody></table>
      <footer><p>{ru?'Для расчёта используются только достоверные интервалы в пределах времени актуальности сигнала. Пропуски не приравниваются к нулю; процент покрытия показывает долю времени с данными, а не исправность оборудования.':'Only reliable intervals within the signal freshness limit enter the calculation. Gaps are not zero; coverage is the share of time with data, not equipment health.'}</p><p>{ru?'Сформирован':'Generated'} {new Date(result.generatedAt).toISOString()} · {ru?'Сборка':'Build'} <code>{result.revision.slice(0,12)}</code></p></footer>
    </article>)}
  </section>;
}
