import {Children,isValidElement,useState,type ReactNode} from 'react';
import {endLabel,equipmentSignals,isAttached,isConnected,reportSignals,interfaceProfile,text,type Locale,type Project,type Snapshot,type Signal,type Value} from '../core';
import type {EditorId,ProjectResource,ResourceCatalog,ResourceKind} from '../core/resources';
import type {DocumentBuffer} from './model/documents';
import type {PluginStatus} from './dependencies';
import {Control} from './controls';
import {ResourceIcon} from './icons';
export interface DetailTarget {kind:ResourceKind|'signal'|'connection'|'alarm'|'screen';id:string}
interface Props {editor:EditorId;activeSource:string;target:DetailTarget;project:Project;snapshot:Snapshot;catalog:ResourceCatalog;documents:ReadonlyMap<string,DocumentBuffer>;plugins:readonly PluginStatus[];locale:Locale;connected:boolean;revision:string;operator:boolean;close:()=>void;open:(resource:ProjectResource,editor?:EditorId)=>void;signal:(id:string)=>void;send:(id:string,value:Value)=>Promise<void>;deviceEdit?:ReactNode;deviceEditId?:string}
const labels:Record<DetailTarget['kind'],[string,string]>={project:['Проект','Project'],device:['Оборудование','Equipment'],signal:['Сигнал','Signal'],connection:['Соединение','Connection'],alarm:['Тревога','Alarm'],report:['Отчёт','Report'],screen:['Экран HMI','HMI screen'],hmi:['Исходник HMI','HMI source'],target:['Цель развёртывания','Deployment target'],plugin:['Расширение','Extension'],file:['Файл','File']};
const shortRevision=(revision:string)=>revision.replace(/^sha256:/,'').slice(0,12)||'—';
const format=(v:unknown,locale:Locale)=>v===undefined||v===null?'—':typeof v==='number'?v.toLocaleString(locale,{maximumFractionDigits:4}):String(v);
/** Read-only projection of existing project, observations and source buffers. No authored state lives here. */
export function ResourceDetails(props:Props){
 const {project,snapshot,catalog,locale,connected,operator}=props,ru=locale==='ru',t=(a:string,b:string)=>ru?a:b;
 const [trail,setTrail]=useState<DetailTarget[]>([]),target=trail.at(-1)??props.target;
 const inspect=(kind:DetailTarget['kind'],id:string)=>setTrail(previous=>[...previous,{kind,id}]);
 const resource=catalog.resources.find(r=>target.kind==='project'?r.kind==='project':r.kind===target.kind&&(r.uri===target.id||r.entityId===target.id));
 const device=target.kind==='device'?project.equipment.find(e=>e.id===target.id):undefined;
 const signal=target.kind==='signal'?project.signals[target.id]??Object.values(project.signals).find(s=>s.id===target.id):undefined;
 const report=target.kind==='report'?project.reports?.find(r=>r.id===target.id):undefined;
 const edge=target.kind==='connection'?[...project.pipes,...project.cables??[]].find(c=>c.id===target.id):undefined;
 const alarm=target.kind==='alarm'?project.alarms.find(a=>a.id===target.id):undefined;
 const screens=[...(project.hmi?[{...project.hmi,id:'default',label:t('Экран контроллера','Controller screen')}]:[]),...project.hmis??[]];
 const screen=target.kind==='screen'?screens.find(s=>s.id===target.id):undefined;
 const owner=signal?.owner?.kind==='equipment'?catalog.resources.find(r=>r.kind==='device'&&r.entityId===signal.owner!.id):undefined;
 const source=resource?.source??owner?.source,sourceOnly=!!resource&&['plugin','target','hmi','file'].includes(resource.kind);
 const semanticId=signal?.semanticId??device?.semanticId??resource?.semanticId;
 const name=device?text(device.label,locale):signal?text(signal.label??signal.id,locale):report?text(report.label,locale):alarm?text(alarm.label,locale):screen?text(screen.label??screen.id,locale):resource?.name[locale]??target.id;
 const fields=(items:readonly (readonly [string,ReactNode])[])=><dl className="detail-fields">{items.map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value??'—'}</dd></div>)}</dl>;
 const hasContent=(children:ReactNode):boolean=>Children.toArray(children).some(child=>isValidElement<{children?:ReactNode}>(child)&&typeof child.type==='symbol'?hasContent(child.props.children):true);
 const section=(title:string,children:ReactNode)=><section className="detail-section"><h3>{title}</h3>{hasContent(children)?children:<p className="detail-note">{t('Не заданы','None defined')}</p>}</section>;
 const link=(kind:DetailTarget['kind'],id:string,label=id,meta?:ReactNode)=><button key={kind+':'+id} className="detail-link" onClick={()=>inspect(kind,id)}><span>{label}</span>{meta&&<small>{meta}</small>}<ResourceIcon icon="chevron-right" size={14}/></button>;
 const signalLink=(s:Signal)=>link('signal',s.id,s.id,<>{connected&&snapshot.samples[s.id]?.quality==='good'?format(snapshot.samples[s.id]?.value,locale):'—'} {s.unit}</>);
 const sourceBuffer=source?props.documents.get(source.path):undefined;
 const observation=(s:Signal)=>{const sample=snapshot.samples[s.id],quality=!connected?'offline':sample?.quality??'missing';return <>{fields([[t('Значение','Value'),quality==='good'?`${format(sample?.value,locale)} ${s.unit??''}`:'—'],[t('Качество','Quality'),<span className={'detail-quality '+quality}>{({good:t('Достоверно','Good'),stale:t('Устарело','Stale'),bad:t('Недостоверно','Bad'),offline:t('Нет связи','Offline'),missing:t('Нет измерений','No observations')})[quality]}</span>],[t('Время измерения','Observed'),sample?new Date(sample.at).toLocaleString(locale):'—']])}{quality!=='good'&&sample&&<p className="detail-note">{t('Последнее известное значение','Last known value')}: {format(sample.value,locale)} {s.unit}</p>}</>;};
 const unknown=!resource&&!device&&!signal&&!report&&!edge&&!alarm&&!screen;
 return <aside className="inspector resource-details" aria-label={t('Свойства объекта','Resource properties')}>
   <div className="pane-heading">{trail.length>0&&<button className="icon-button" aria-label={t('Назад по связям','Back through relations')} onClick={()=>setTrail(previous=>previous.slice(0,-1))}>←</button>}<strong>{labels[target.kind][ru?0:1]}</strong><button className="icon-button" aria-label={t('Закрыть свойства','Close inspector')} onClick={props.close}><ResourceIcon icon="close" size={16}/></button></div>
   <div className="inspector-body"><header className="detail-identity"><h2>{name}</h2><code>{device?.id??signal?.id??report?.id??edge?.id??alarm?.id??screen?.id??resource?.source?.path??project.id}</code></header>
   {unknown?<p className="detail-note" role="status">{t('Объект больше не существует в текущей модели.','This object is no longer present in the current model.')}</p>:<>
   <p className="detail-context">{sourceOnly?t('Исходник проекта','Project source'):<>{t('Модель исполнения','Runtime model')} <code title={props.revision}>{shortRevision(props.revision)}</code></>}</p>
   {device&&<>
    {device.knowledge.summary&&<p>{text(device.knowledge.summary,locale)}</p>}
    {section(t('Параметры','Parameters'),fields([[t('Тип','Type'),device.kind],[t('Положение','Position'),`${device.x}, ${device.y}`],[t('Сигналов','Signals'),equipmentSignals(device).length],[t('Портов','Ports'),Object.keys(device.ports).length]]))}
    {equipmentSignals(device).filter(s=>s.writable).map(s=><div className="detail-control" key={s.id}><strong>{text(s.label??s.id,locale)}</strong><Control signal={s} sample={snapshot.samples[s.id]} locale={locale} enabled={connected} send={props.send}/></div>)}
    {section(t('Сигналы','Signals'),equipmentSignals(device).map(signalLink))}
    {section(t('Соединения','Connections'),[...project.pipes,...project.cables??[]].filter(e=>[e.from,e.to].some(end=>isAttached(end)&&end.device===device.id)).map(e=>link('connection',e.id,e.id,`${endLabel(e.from)} → ${endLabel(e.to)}`)))}
    {section(t('Интерфейсы','Interfaces'),Object.values(device.ports).map(port=><details className="detail-disclosure" key={port.port} data-interface={port.terminal.interfaceId??port.terminal.family}><summary>{port.port}<small>{port.terminal.family}</small></summary>{fields([[t('Профиль','Profile'),port.terminal.interfaceId?interfaceProfile(port.terminal.interfaceId).label:port.terminal.family],[t('Направление','Direction'),port.terminal.role],[t('Среда','Medium'),port.terminal.medium],[t('Тип значения','Value type'),port.terminal.valueType],[t('Единица','Unit'),port.terminal.unit],[t('Максимум соединений','Max connections'),port.terminal.max]])}</details>))}
    {!!device.knowledge.constraints?.length&&section(t('Ограничения','Constraints'),device.knowledge.constraints.map(c=><p key={c.id} className={c.severity}><strong>{text(c.label,locale)}</strong>{c.description&&<small className="detail-note">{text(c.description,locale)}</small>}</p>))}
    {section(t('Отчёты и тревоги','Reports and alarms'),<>{(project.reports??[]).filter(r=>reportSignals(r).some(s=>equipmentSignals(device).some(d=>d.id===s.id))).map(r=>link('report',r.id,text(r.label,locale)))}{project.alarms.filter(a=>equipmentSignals(device).some(s=>s.id===a.signal.id)).map(a=>link('alarm',a.id,text(a.label,locale)))}</>)}
    {!operator&&props.deviceEditId===device.id&&props.deviceEdit&&<details className="detail-disclosure"><summary>{t('Изменить tag / ID','Change tag / ID')}</summary>{props.deviceEdit}</details>}
   </>}
   {signal&&<>
    {signal.description&&<p>{text(signal.description,locale)}</p>}{section(t('Наблюдение','Observation'),observation(signal))}
    {section(t('Контракт','Contract'),fields([[t('Тип','Type'),typeof signal.initial],[t('Единица','Unit'),signal.unit],[t('Размерность','Dimension'),signal.dimension],[t('Доступ','Access'),signal.writable?t('Чтение и команда','Read and command'):t('Только чтение','Read only')],[t('Начальное значение','Initial value'),format(signal.initial,locale)],[t('Диапазон','Range'),`${signal.min??'—'} … ${signal.max??'—'}`],[t('Срок актуальности','Freshness'),`${signal.staleAfter??5000} ms`]]))}
    {signal.writable&&<Control signal={signal} sample={snapshot.samples[signal.id]} locale={locale} enabled={connected} send={props.send}/>}
    <button className="detail-link" onClick={()=>props.signal(signal.id)}><ResourceIcon icon="signals"/>{t('История измерений','Observation history')}</button>
    {section(t('Источник','Origin'),fields([[t('Владелец','Owner'),signal.owner?`${signal.owner.kind} · ${signal.owner.id}`:'—'],[t('Происхождение','Origin'),signal.origin?.kind],[t('Протокол','Protocol'),signal.binding?.protocol],[t('Адрес','Address'),signal.binding?.address],[t('Опрос','Polling'),signal.binding?.pollMs?`${signal.binding.pollMs} ms`:'—']]))}
    {signal.origin&&'dependencies' in signal.origin&&section(t('Зависит от','Dependencies'),signal.origin.dependencies.map(id=>link('signal',id)))}
    {section(t('Используется','Used by'),<>{owner&&link('device',owner.entityId!,owner.name[locale])}{(project.reports??[]).filter(r=>reportSignals(r).some(s=>s.id===signal.id)).map(r=>link('report',r.id,text(r.label,locale)))}{project.alarms.filter(a=>a.signal.id===signal.id).map(a=>link('alarm',a.id,text(a.label,locale)))}</>)}
    {snapshot.samples[signal.id]?.provenance&&section(t('Версия измерения','Observation version'),fields([['Run',snapshot.samples[signal.id]!.provenance!.id],['Build',snapshot.samples[signal.id]!.provenance!.build],['Git',snapshot.samples[signal.id]!.provenance!.sourceRevision]]))}
   </>}
   {edge&&<>{section(t('Параметры','Parameters'),fields([[t('Вид','Kind'),edge.kind],[t('Состояние','State'),isConnected(edge)?t('Соединён в модели','Connected in model'):t('Свободный конец','Free end')],[t('Точки маршрута','Route points'),edge.via?.length??0]]))}{section(t('Концы соединения','Endpoints'),<>{isAttached(edge.from)?link('device',edge.from.device,endLabel(edge.from)):<span key="from">{endLabel(edge.from)}</span>}{isAttached(edge.to)?link('device',edge.to.device,endLabel(edge.to)):<span key="to">{endLabel(edge.to)}</span>}</>)}{section(t('Сигнал','Signal'),edge.kind==='pipe'?signalLink(edge.flow):edge.signal?signalLink(edge.signal):<p className="detail-note">{t('Сигнал не назначен','No signal assigned')}</p>)}</>}
   {alarm&&<>{section(t('Состояние','State'),fields([[t('Активность','Activity'),!connected?t('Нет связи','Offline'):!snapshot.alarms[alarm.id]?t('Нет наблюдений','No observations'):snapshot.alarms[alarm.id]?.active?t('Активна','Active'):t('Не активна','Inactive')],[t('Квитирование','Acknowledgement'),!connected?'—':snapshot.alarms[alarm.id]?.acknowledged?t('Квитирована','Acknowledged'):'—'],[t('Порог','Threshold'),`${alarm.above} ${alarm.signal.unit??''}`],[t('Гистерезис','Hysteresis'),alarm.hysteresis??0]]))}{signalLink(alarm.signal)}<p className="detail-note">{t('Квитирование и журнал доступны в Уведомлениях.','Acknowledgement and event history are available in Notifications.')}</p></>}
   {report&&<>
    {'sql' in report&&report.description&&<p>{text(report.description,locale)}</p>}
    {section(t('Параметры','Parameters'),fields([[t('Расчёт','Calculation'),'sql' in report?'SQL':t('Агрегация по времени','Time aggregation')],[t('Окно','Window'),`${('sql' in report?report.window:report.bucketMs)/1000} s`],[t('Колонок','Columns'),Object.keys(report.columns).length],[t('Форматы','Formats'),'XLSX · CSV · HTML · '+t('Печать','Print')]]))}
    {section(t('Колонки','Columns'),'sql' in report?report.columns.map(c=><div className="detail-column" key={c.key}><strong>{text(c.title,locale)}</strong><code>{c.key} · {report.schema[c.key]?.type}</code><small>{c.unit??report.schema[c.key]?.unit}</small></div>):Object.entries(report.columns).map(([key,c])=><div className="detail-column" key={key}><strong>{text(c.label,locale)}</strong><code>{key} · {c.aggregate} · {c.unit??c.signal.unit}</code>{signalLink(c.signal)}</div>))}
    {section(t('Расписание','Schedule'),report.schedule?.length?report.schedule.map((s,i)=><div className="detail-column" key={i}><code>{s.cron}</code><span>{s.timeZone} · {s.periodMs/1000} s</span></div>):<p className="detail-note">{t('Ручной запуск','Manual execution')}</p>)}
    {'sql' in report&&<>{section(t('Входные параметры','Inputs'),Object.entries(report.inputs??{}).map(([key,d])=><div className="detail-column" key={key}><strong>{text(d.label??key,locale)}</strong><span>{d.min} … {d.max} · {t('по умолчанию','default')} {d.default}</span></div>))}{section(t('Листы XLSX','XLSX sheets'),report.excel?.sheets.map(s=><details className="detail-disclosure" key={s.name}><summary>{s.name}<small>{s.columns.length}</small></summary>{fields([[t('Сортировка','Sort'),s.sort?.map(v=>`${v.key} ${v.direction}`).join(', ')||'—'],[t('Закрепление строк','Frozen rows'),s.freezeRows??0],[t('Фильтр','Filter'),s.autoFilter?t('Включён','Enabled'):t('Выключен','Disabled')]])}{s.columns.map(c=><p key={c.key}><code>{c.key}</code> · {c.format??t('Общий формат','General')} · {c.width??22}</p>)}</details>)??<p className="detail-note">{t('Стандартный лист','Default sheet')}</p>)}<details className="detail-disclosure"><summary>SQL</summary><pre>{report.sql}</pre></details>{section(t('Исходные сигналы','Input signals'),report.signals.map(signalLink))}</>}
    {resource&&!(props.editor==='reports'&&props.target.id===report.id)&&<button className="detail-link" onClick={()=>props.open(resource,'reports')}><ResourceIcon icon="report"/>{t('Открыть отчёт','Open report')}</button>}
   </>}
   {screen&&<>{section(t('Параметры','Parameters'),fields([[t('Размер экрана','Screen size'),`${screen.width} × ${screen.height}`],[t('Оборудование','Equipment'),screen.equipment.length]]))}{section(t('Оборудование','Equipment'),screen.equipment.map(e=>link('device',e.id,text(e.label,locale))))}<a className="detail-link" href={`/hmi?screen=${encodeURIComponent(screen.id)}`} target="_blank" rel="noreferrer">{t('Открыть экран оператора','Open operator screen')} ↗</a></>}
   {target.kind==='project'&&<>
    {section(t('Состав проекта','Project contents'),fields([[t('Оборудование','Equipment'),project.equipment.length],[t('Сигналы','Signals'),Object.keys(project.signals).length],[t('Соединения','Connections'),project.pipes.length+(project.cables?.length??0)],[t('Тревоги','Alarms'),project.alarms.length],[t('Отчёты','Reports'),project.reports?.length??0],['HMI',screens.length]]))}
    {section(t('Оборудование','Equipment'),project.equipment.map(e=>link('device',e.id,text(e.label,locale))))}
    {section(t('Отчёты','Reports'),project.reports?.map(r=>link('report',r.id,text(r.label,locale))))}
    {section('HMI',screens.map(s=>link('screen',s.id,text(s.label??s.id,locale))))}
    {section(t('Тревоги','Alarms'),project.alarms.map(a=>link('alarm',a.id,text(a.label,locale))))}
   </>}
   {resource&&['plugin','target','hmi','file'].includes(resource.kind)&&<>
    {section(t('Файл проекта','Project file'),fields([[t('Изменения','Changes'),sourceBuffer?.error?sourceBuffer.error:sourceBuffer?.saving?t('Сохраняется','Saving'):sourceBuffer&&sourceBuffer.draft!==sourceBuffer.source?t('Не сохранены','Unsaved'):t('Нет несохранённого буфера','No unsaved buffer')],[t('Редактор','Editor'),source?.path.endsWith('.ts')||source?.path.endsWith('.tsx')?'TypeScript':source?.path.split('.').at(-1)]]))}
    {resource.kind==='plugin'&&<>{props.plugins.filter(p=>source?.path.startsWith('plugins/'+p.name+'/')).map(p=>section(t('Версия расширения','Extension version'),fields([['Git',p.repository],[t('Ветка / тег','Branch / tag'),p.ref],[t('Ревизия','Revision'),p.revision],[t('Обновление','Update'),p.error??(p.update?p.latest:t('Нет обновлений','Up to date'))],[t('Локальные изменения','Local modifications'),p.modified?t('Есть','Present'):t('Нет','None')]])))}<p className="detail-note">{t('Исходники принадлежат проекту и подключаются обычным import.','Sources belong to the project and are connected through ordinary imports.')}</p></>}
    {resource.kind==='target'&&<p className="detail-note">{t('План и команды определяются в этом исходнике. Состояние применения сборки показано в Развёртывании.','The plan and commands are defined in this source. Applied build state is shown in Deployment.')}</p>}
    {resource.kind==='hmi'&&section(t('Экраны модели','Model screens'),screens.map(s=>link('screen',s.id,text(s.label??s.id,locale))))}
    {section(t('Связанные объекты','Related resources'),catalog.resources.filter(r=>r.uri!==resource.uri&&(r.parent===resource.uri||resource.related.includes(r.uri))).map(r=>link(r.kind,r.entityId??r.uri,r.name[locale])))}
   </>}
   {section(t('Происхождение и код','Provenance and source'),<>{fields([[t('Проверенная модель','Checked model'),<code title={catalog.revision}>{shortRevision(catalog.revision)}</code>],...(semanticId?[[t('Семантический ID','Semantic ID'),semanticId] as const]:[])])}{source?<>{!sourceOnly&&<code className="detail-source-path">{source.path}</code>}{!operator&&!(props.editor==='source'&&props.activeSource===source.path)&&<button className="detail-link" onClick={()=>{const r=resource?.source?resource:owner;if(r)props.open(r,'source');}}><ResourceIcon icon="source"/>{t('Показать в коде','Show in code')}</button>}</>:<p className="detail-note">{t('Однозначное место объявления не найдено.','No unambiguous declaration location found.')}</p>}</>)}
   </>}
   </div>
 </aside>;
}
