import {useState} from 'react';
import {text,type Locale,type Project,type Snapshot} from '../core';
export function SignalsSurface({project,snapshot,locale,connected,selected,select}:{project:Project;snapshot:Snapshot;locale:Locale;connected:boolean;selected?:string;select:(id:string)=>void}){
 const ru=locale==='ru',[query,setQuery]=useState(''),[filter,setFilter]=useState('all');
 const signals=Object.values(project.signals),quality=(id:string)=>!connected?'offline':snapshot.samples[id]?.quality??'missing';
 const labels={good:ru?'Достоверно':'Good',stale:ru?'Устарело':'Stale',bad:ru?'Недостоверно':'Bad',offline:ru?'Нет связи':'Offline',missing:ru?'Нет измерений':'No observations'};
 const shown=signals.filter(s=>`${s.id} ${text(s.label??'',locale)} ${s.owner?.id??''} ${s.unit??''}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())&&(filter==='all'||filter==='writable'&&s.writable||filter==='attention'&&quality(s.id)!=='good'));
 return <section className="signals-surface"><div className="signals-controls"><input type="search" aria-label={ru?'Поиск сигналов':'Search signals'} placeholder={ru?'Сигнал, владелец, единица…':'Signal, owner, unit…'} value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label={ru?'Фильтр сигналов':'Signal filter'} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{ru?'Все сигналы':'All signals'}</option><option value="writable">{ru?'Доступна команда':'Writable'}</option><option value="attention">{ru?'Требуют внимания':'Need attention'}</option></select><small role="status">{shown.length} / {signals.length}</small></div><div className="table-scroll"><table><thead><tr><th>{ru?'Сигнал':'Signal'}</th><th>{ru?'Значение':'Value'}</th><th>{ru?'Качество':'Quality'}</th><th>{ru?'Доступ':'Access'}</th><th>{ru?'Получен':'Observed'}</th></tr></thead><tbody>{shown.map(s=>{const sample=snapshot.samples[s.id],q=quality(s.id);return <tr key={s.id} className={selected===s.id?'active':''}><td><button className="text-button" aria-pressed={selected===s.id} onClick={()=>select(s.id)}><code>{s.id}</code></button>{s.label&&<small>{text(s.label,locale)}</small>}<small>{s.owner?.id??(ru?'Проект':'Project')} · {typeof s.initial}</small></td><td>{q==='good'?(typeof sample?.value==='number'?sample.value.toLocaleString(locale,{maximumFractionDigits:3}):String(sample?.value)):'—'} <span className="muted">{s.unit}</span></td><td className={q}>{labels[q]}</td><td>{s.writable?(ru?'Команда':'Writable'):(ru?'Чтение':'Read only')}</td><td><time title={sample?new Date(sample.at).toISOString():undefined}>{sample?new Date(sample.at).toLocaleTimeString(locale):'—'}</time></td></tr>;})}</tbody></table>{!shown.length&&<div className="empty-state"><h2>{ru?'Сигналы не найдены':'No matching signals'}</h2><p>{ru?'Измените поиск или фильтр.':'Change the search or filter.'}</p></div>}</div></section>;
}
