export interface ReportSchedule {cron:string;timeZone:string;periodMs:number}
function fields(cron:string){if(typeof cron!=='string'||cron.length>120)throw new Error('Invalid cron');const parts=cron.trim().split(/\s+/),limits=[[0,59],[0,23],[1,31],[1,12],[0,7]];if(parts.length!==5)throw new Error('Cron requires five fields');return parts.map((part,i)=>{const [min,max]=limits[i]! as [number,number],values=new Set<number>();for(const item of part.split(',')){const m=/^(\*|\d+(?:-\d+)?)(?:\/(\d+))?$/.exec(item);if(!m)throw new Error('Invalid cron field');let from=min,to=max;if(m[1]!=='*'){const range=m[1]!.split('-').map(Number);from=range[0]!;to=range[1]??(m[2]?max:from);}const step=Number(m[2]??1);if(from<min||to>max||from>to||step<1||step>max-min+1)throw new Error('Invalid cron range');for(let n=from;n<=to;n+=step)values.add(i===4&&n===7?0:n);}return values;});}
export function validateSchedule(schedule:ReportSchedule){fields(schedule.cron);new Intl.DateTimeFormat('en',{timeZone:schedule.timeZone}).format();if(!schedule.timeZone||!Number.isSafeInteger(schedule.periodMs)||schedule.periodMs<1000||schedule.periodMs>31*86400000)throw new Error('Invalid scheduled report period');}
/** Five-field cron, explicit IANA timezone, traditional DOM/DOW semantics; slots are UTC minutes. */
export function cronMatches(cron:string,at:number,timeZone='UTC'){
  const f=fields(cron),p=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone,minute:'numeric',hour:'numeric',hourCycle:'h23',day:'numeric',month:'numeric',weekday:'short'}).formatToParts(at).map(p=>[p.type,p.value]));
  const values=[Number(p.minute),Number(p.hour),Number(p.day),Number(p.month),['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(p.weekday!)];
  if(!f[0]!.has(values[0]!)||!f[1]!.has(values[1]!)||!f[3]!.has(values[3]!))return false;const parts=cron.trim().split(/\s+/),dom=f[2]!.has(values[2]!),dow=f[4]!.has(values[4]!);return parts[2]!.startsWith('*')||parts[4]!.startsWith('*')?dom&&dow:dom||dow;
}
