import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {chromium} from 'playwright';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StreamableHTTPClientTransport} from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import type {CallToolResult} from '@modelcontextprotocol/sdk/types.js';
import {fixture} from '../tests/helpers';
import {createApp} from '../src/host/dev';
import {createAppsHost} from '../src/host/apps';
const artifacts=resolve('artifacts/apps-recording');mkdirSync(artifacts,{recursive:true});
const work=fixture();
await Bun.write(join(work.root,'reports/flow.ts'),await Bun.file('examples/reports/flow.ts').text());
const authored=await Bun.file(join(work.root,'project.ts')).text();await Bun.write(join(work.root,'project.ts'),"import {flowReport} from './reports/flow';\n"+authored.replace('reports: [hourlyWater]','reports: [hourlyWater,flowReport(booster.flow)]'));
const app=await createApp({projectDir:work.root,dataDir:work.dir,databaseUrl:':memory:',port:0,preview:'simulation'});
const apps=await createAppsHost({workspaceUrl:String(app.server.url),projectDir:work.root,dataDir:join(work.dir,'apps'),port:0});
const built=await Bun.build({entrypoints:[resolve('scripts/helpers/apps-host-browser.ts')],target:'browser',outdir:join(work.dir,'bridge'),minify:true});assert.ok(built.success);
const bridgeJS=await built.outputs[0]!.text();
const host=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(request){
  const url=new URL(request.url);
  if(url.pathname==='/rpc')return fetch(new URL('/mcp',apps.server.url),{method:'POST',headers:{'content-type':'application/json',accept:'application/json, text/event-stream'},body:await request.text()});
  if(url.pathname==='/ui')return new Response(apps.assets.html,{headers:{'content-type':'text/html','content-security-policy':"default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: blob:; font-src data:; connect-src 'none'; frame-src 'none'"}});
  if(url.pathname==='/bridge.js')return new Response(bridgeJS,{headers:{'content-type':'text/javascript'}});
  return new Response(`<!doctype html><html><body data-uri="${apps.assets.uri}" style="margin:0;background:#eef1f6;font:14px system-ui"><header style="padding:12px">MCP Apps acceptance host · official AppBridge</header><iframe id="saturn" title="Saturn App" style="width:100%;height:850px;border:0" sandbox="allow-scripts allow-same-origin allow-downloads allow-modals"></iframe><details open><summary>Acceptance controls</summary><textarea id="view"></textarea><button id="navigate">Navigate</button><button id="close">Close App</button><pre id="context"></pre><pre id="link"></pre></details><script type="module" src="/bridge.js"></script></body></html>`,{headers:{'content-type':'text/html'}});
}});
const client=new Client({name:'apps-browser-test',version:'1.0.0'});await client.connect(new StreamableHTTPClientTransport(new URL('/mcp',apps.server.url)));
const call=async(name:string,args:Record<string,unknown>={})=>await client.callTool({name,arguments:args}) as CallToolResult;
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1500,height:950},recordVideo:{dir:artifacts}}),page=await context.newPage(),errors:string[]=[];
page.on('pageerror',error=>errors.push(error.message));
try{
  await page.goto(String(host.url));const view=page.frameLocator('#saturn');
  await view.locator('.scene3d[data-frames]').waitFor({timeout:30000});
  const scene=view.locator('.scene3d');
  await scene.evaluate(node=>{node.setAttribute('data-retained','true');});
  await page.waitForFunction(()=>document.getElementById('context')?.textContent?.includes('P-01'));
  assert.equal(await view.locator('.chat-region').count(),0);
  const before=await scene.evaluate(node=>({objects:JSON.parse((node as HTMLElement).dataset.equipmentObjects??'{}') as Record<string,string>,frames:Number((node as HTMLElement).dataset.frames),camera:(node as HTMLElement).dataset.cameraPose}));
  await page.screenshot({path:join(artifacts,'01-apps-3d.png')});
  const file=(await call('saturn_read_source',{path:'equipment/P-01.device.ts'})).structuredContent! as {path:string;source:string;version:string};
  const source=file.source.replace('Booster pump','Pump edited in ChatGPT');assert.notEqual(source,file.source);
  const saved=await call('saturn_save_sources',{files:[{...file,source}]});assert.ok(!saved.isError,JSON.stringify(saved));
  await view.getByText('Pump edited in ChatGPT').first().waitFor({timeout:20000});
  assert.equal(await scene.getAttribute('data-retained'),'true');
  const after=await scene.evaluate(node=>({frames:Number((node as HTMLElement).dataset.frames),camera:(node as HTMLElement).dataset.cameraPose}));assert.ok(after.frames>before.frames);assert.equal(after.camera,before.camera);
  const preview=await call('saturn_create_device',{template:'tank',id:'TK-02',label:'Added from ChatGPT'});assert.ok(!preview.isError,JSON.stringify(preview));
  const created=await call('saturn_create_device',{template:'tank',id:'TK-02',label:'Added from ChatGPT',apply:true,projectVersion:preview.structuredContent!.projectVersion});assert.ok(!created.isError,JSON.stringify(created));
  await page.waitForFunction(()=>{const node=document.querySelector<HTMLIFrameElement>('#saturn')?.contentDocument?.querySelector<HTMLElement>('.scene3d');return JSON.parse(node?.dataset.equipmentObjects??'{}')['TK-02'];});
  const added=await scene.evaluate(node=>({objects:JSON.parse((node as HTMLElement).dataset.equipmentObjects??'{}') as Record<string,string>,camera:(node as HTMLElement).dataset.cameraPose}));
  // Adding equipment retains every unchanged device mesh; the edited pump was rebuilt once for its label.
  for(const id of ['TK-01','V-01','PLC-01'])assert.equal(added.objects[id],before.objects[id],id+' mesh should survive hot reload');
  assert.equal(added.camera,before.camera);assert.equal(await scene.getAttribute('data-retained'),'true');
  await page.screenshot({path:join(artifacts,'02-hot-reload.png')});
  const projectSource=(await call('saturn_read_source',{path:'project.ts'})).structuredContent! as {path:string;source:string;version:string};
  const renamedProject=projectSource.source.replace('Pumping station','Station edited from Apps');assert.notEqual(renamedProject,projectSource.source);
  assert.ok(!(await call('saturn_save_sources',{files:[{...projectSource,source:renamedProject}]})).isError);
  await page.waitForFunction(old=>{const node=document.querySelector<HTMLIFrameElement>('#saturn')?.contentDocument?.querySelector<HTMLElement>('.scene3d');return JSON.parse(node?.dataset.equipmentObjects??'{}')['PLC-01']!==old;},added.objects['PLC-01']);
  const rebound=await scene.evaluate(node=>JSON.parse((node as HTMLElement).dataset.equipmentObjects??'{}') as Record<string,string>);
  for(const id of ['P-01','TK-01','V-01','TK-02'])assert.equal(rebound[id],added.objects[id],id+' survives changed display context');
  const navigate=async(surface:string,extra:Record<string,unknown>={})=>{const result=await call('saturn_open',{surface,...extra});await page.locator('#view').fill(JSON.stringify({_meta:result._meta,content:[]}));await page.locator('#navigate').click();};
  await navigate('source',{file:file.path});await view.locator('.cm-editor').first().waitFor();
  assert.ok((await view.locator('.cm-editor').first().innerText()).includes('Pump edited in ChatGPT'));
  await page.screenshot({path:join(artifacts,'03-source.png')});
  await navigate('hmi');await view.locator('.hmi-gallery').waitFor();assert.equal(await view.locator('.hmi-gallery iframe').count(),0);assert.ok(await view.locator('.hmi').count()>0);
  await page.screenshot({path:join(artifacts,'04-hmi.png')});
  await navigate('reports');await view.getByRole('button',{name:'Generate',exact:true}).click();await view.locator('.report-page,.report-document').waitFor({timeout:15000});
  await view.getByLabel('Report',{exact:true}).selectOption('flow-detail');await view.getByRole('button',{name:'Generate',exact:true}).click();await view.locator('[data-report-document=inline]').waitFor();await view.getByRole('heading',{name:'Flow · typed report'}).waitFor();
  await view.getByRole('button',{name:'Export report',exact:true}).click();const downloadPromise=page.waitForEvent('download');await view.getByRole('menuitem',{name:'Excel (.xlsx)',exact:true}).click();const download=await downloadPromise;await download.saveAs(join(artifacts,'report.xlsx'));assert.equal((await Bun.file(join(artifacts,'report.xlsx')).bytes())[0],80);
  assert.equal(await view.locator('iframe').count(),0);
  await page.screenshot({path:join(artifacts,'05-report.png')});
  await navigate('diagram',{dimension:'3d',device:'P-01',port:'outlet'});await page.waitForFunction(()=>document.querySelector<HTMLIFrameElement>('#saturn')?.contentDocument?.querySelector<HTMLElement>('.scene3d')?.dataset.selectedPort==='P-01.outlet');
  await page.screenshot({path:join(artifacts,'05-port-3d.png')});
  await navigate('diagram',{dimension:'2d',device:'V-01'});await view.locator('svg.scene').waitFor();
  await navigate('diagram',{dimension:'2d',device:'P-01',port:'outlet'});await view.locator('[data-equipment="P-01"] [data-port=outlet][data-selected=true]').waitFor();
  await navigate('diagram',{dimension:'2d',device:'V-01'});
  await view.locator('#apps-open').click();await page.waitForFunction(()=>document.getElementById('link')?.textContent?.includes('device=V-01'));
  const latest=(await call('saturn_read_source',{path:file.path})).structuredContent!;
  await call('saturn_save_sources',{files:[{...latest,source:'export const = ;'}]});
  await page.waitForFunction(()=>document.querySelector<HTMLIFrameElement>('#saturn')?.contentDocument?.body.textContent?.includes('Project issues:'));
  await page.screenshot({path:join(artifacts,'06-failed-source.png')});
  const invalid=(await call('saturn_read_source',{path:file.path})).structuredContent!;await call('saturn_save_sources',{files:[{...invalid,source}]});
  await app.close();
  await page.waitForFunction(()=>document.querySelector<HTMLIFrameElement>('#saturn')?.contentDocument?.body.textContent?.includes('Disconnected'));
  await page.screenshot({path:join(artifacts,'07-disconnected.png')});
  await page.locator('#close').click();await view.locator('#apps-status').filter({hasText:'Closed'}).waitFor();
  await page.screenshot({path:join(artifacts,'08-closed.png')});
  assert.deepEqual(errors,[]);
  writeFileSync(join(artifacts,'evidence.json'),JSON.stringify({runtime:Bun.version,platform:process.platform,architecture:process.arch,checks:['official AppBridge initialization','actual existing 2D/3D/source/HMI/report UI','no nested network frames','no own agent UI','CAS source edits','camera/canvas retained','unchanged equipment meshes retained on add','changed HMI context rebuilds display only','view model context and local deep link','2D/3D port selection','real XLSX download through Apps','typed report without nested iframe','failed draft','workspace disconnected','app teardown'],errors},null,2));
  console.log('Apps browser acceptance passed',artifacts);
}catch(error){await page.screenshot({path:join(artifacts,'failure.png')}).catch(()=>{});writeFileSync(join(artifacts,'failure.txt'),JSON.stringify({error:String(error),errors,body:await page.frameLocator('#saturn').locator('body').innerText().catch(()=>'' )},null,2));throw error;}finally{await context.close();await browser.close();await client.close();host.stop(true);await apps.close();await app.close();work.clean();}
