import { toggleShellDetails } from './helpers/shell-details';
import { prepareInterface, setInterfaceTheme } from './helpers/interface-preferences';
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { chromium, expect } from 'playwright/test';
import { fixture } from '../tests/helpers';
import { createApp } from '../src/host/dev';
import { ResourceIcon, shellIconNames } from '../src/shell/icons';

const evidence='artifacts/central-shell';mkdirSync(evidence,{recursive:true});
const work=fixture(),app=await createApp({projectDir:work.root,dataDir:work.dir,databaseUrl:':memory:',port:0,preview:'simulation'});
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1600,height:1000},locale:'ru-RU',permissions:['clipboard-read','clipboard-write'],recordVideo:{dir:join(evidence,'recording')}});
const page=await context.newPage(),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
const rail=page.getByRole('navigation',{name:'Рабочие области'}),chat=page.getByRole('region',{name:'Инженерная задача'});
const destination=async(id:string)=>{if(await page.evaluate(()=>matchMedia('(max-width:760px), (pointer:coarse) and (max-width:1024px)').matches)){await page.getByRole('button',{name:'Главное меню',exact:true}).click();await page.getByRole('dialog',{name:'Главное меню'}).getByRole('button',{name:id==='plugins'?'Плагины':id==='source'?'Код':id==='home'?'Главная':'Состояние объекта',exact:true}).click();}else await rail.locator(`[data-rail-section="${id}"]`).click();await expect(chat).toBeHidden();};
const shot=async(name:string)=>page.screenshot({path:join(evidence,name+'.png')});
try {
  await prepareInterface(context);
  await page.goto(app.server.url.href);await expect(page.locator('svg.scene')).toBeVisible();await expect(chat).toBeHidden();
  await expect(rail.locator('.rail-destination').first()).toHaveAttribute('data-rail-section','home');
  await expect(rail.locator('.rail-destination').last()).toHaveAttribute('data-rail-section','threads');
  await expect(page.locator('.explorer-heading button[aria-label="Действия проводника"]')).toHaveCount(1);
  assert.equal(await page.locator('.explorer-layout-trigger,.explorer-mode-trigger').count(),0);
  const sceneBox=(await page.locator('.diagram-workspace').boundingBox())!;assert.ok(sceneBox.width>1100,'main diagram must own center');
  const diagramBounds=(await page.locator('svg.scene').boundingBox())!;await page.mouse.move(diagramBounds.x+10,diagramBounds.y+10);await page.mouse.down();await page.mouse.move(diagramBounds.x+55,diagramBounds.y+35,{steps:5});await page.mouse.up();
  await expect.poll(()=>new URL(page.url()).searchParams.has('viewBox')).toBe(true);
  const box=await page.locator('svg.scene').getAttribute('viewBox');await expect.poll(()=>new URL(page.url()).searchParams.get('viewBox')).toBe(box!.split(' ').map(value=>Number(Number(value).toFixed(4))).join(','));const boxLink=page.url();const boxPage=await context.newPage();await boxPage.goto(boxLink);await expect(boxPage.locator('svg.scene')).toBeVisible();await expect.poll(()=>boxPage.locator('svg.scene').getAttribute('viewBox')).toBe(new URL(boxLink).searchParams.get('viewBox')!.split(',').join(' '));const restoredBox=(await boxPage.locator('svg.scene').getAttribute('viewBox'))!.split(' ').map(Number);const originalBox=box!.split(' ').map(Number);assert.ok(restoredBox.every((value,index)=>Math.abs(value-originalBox[index]!)<.001),'2D viewport URL restore');await boxPage.close();await shot('object-2d');
  await page.getByRole('button',{name:'3D',exact:true}).click();await expect(page.locator('.scene3d canvas')).toBeVisible({timeout:30000});
  await page.waitForFunction(()=>Number(document.querySelector<HTMLElement>('.scene3d')?.dataset.frames)>3);await shot('object-3d');
  await expect.poll(()=>new URL(page.url()).searchParams.has('camera')).toBe(true);
  const originalPose=await page.locator('.scene3d').getAttribute('data-camera-pose');
  const link=page.url();assert.match(link,/dimension=3d/);
  const linked=await context.newPage();linked.on('pageerror',error=>errors.push(error.message));await linked.goto(link);
  await expect(linked.locator('.scene3d canvas')).toBeVisible({timeout:30000});await expect(linked.getByRole('region',{name:'Инженерная задача'})).toBeHidden();await linked.waitForFunction(()=>!!document.querySelector('.scene3d')?.getAttribute('data-camera-pose'));
  const restoredPose=JSON.parse((await linked.locator('.scene3d').getAttribute('data-camera-pose'))!) as number[];const original=JSON.parse(originalPose!) as number[];assert.ok(restoredPose.every((value,index)=>Math.abs(value-original[index]!)<.001),'3D camera URL restore');await linked.close();
  await destination('source');await expect(page.locator('.code-pane')).toBeVisible();await expect(page.locator('.explorer-heading .context-heading')).toHaveText('Код');
  await page.locator('[data-tree-id="file:equipment/P-01.device.ts"]').click();await expect(page.locator('.cm-content')).toContainText('pump');await shot('code');
  const sourceLink=page.url(),cm=page.locator('.cm-content');assert.match(sourceLink,/file=equipment/);
  const sourcePage=await context.newPage();await sourcePage.goto(sourceLink);await expect(sourcePage.locator('.code-pane .pane-heading')).toContainText('P-01.device.ts');await expect(sourcePage.getByRole('region',{name:'Инженерная задача'})).toBeHidden();await sourcePage.close();
  await cm.click();await page.keyboard.press('ControlOrMeta+End');await page.keyboard.type('\n// central shell draft');
  await destination('monitor');await expect(page.getByRole('region',{name:'Состояние объекта',exact:true})).toBeVisible();await shot('monitor');
  await page.goBack();await expect(page.locator('.cm-content')).toContainText('central shell draft');await expect(chat).toBeHidden();
  await page.goForward();await expect(page.getByRole('region',{name:'Состояние объекта',exact:true})).toBeVisible();await expect(chat).toBeHidden();
  await destination('environment');await expect(page.locator('.environment-surface')).toBeVisible();
  await toggleShellDetails(page,'properties');await expect(page.locator('.shell-body > .shell-details-slot > .resource-details')).toBeVisible();
  assert.equal(await page.locator('.surface-layout .resource-details,.workbench .resource-details').count(),0,'sidebar belongs to shell');await shot('environment-sidebar');
  await toggleShellDetails(page,'properties');
  await destination('plugins');const plugins=page.getByRole('region',{name:'Плагины проекта'});await expect(plugins).toBeVisible();
  await expect(plugins).toContainText('example-extension');await shot('plugins');
  await plugins.getByRole('textbox',{name:'Поиск плагинов'}).fill('no-such-extension');await expect(plugins).toContainText('Совпадений нет');
  await plugins.getByRole('textbox',{name:'Поиск плагинов'}).fill('');await plugins.getByRole('button',{name:'Добавить',exact:true}).click();
  await expect(plugins.getByRole('textbox',{name:'GitHub HTTPS'})).toBeVisible();await shot('plugins-add');
  await plugins.getByRole('button',{name:'Добавить',exact:true}).click();
  await plugins.getByRole('button',{name:'Открыть исходник',exact:true}).first().click();await expect(page.locator('.cm-content')).toContainText('export const');await expect(chat).toBeHidden();
  await rail.locator('[data-rail-section="threads"]').click();await expect(chat).toBeVisible();
  const request=page.getByRole('textbox',{name:'Запрос для внешнего агента'});await request.fill('Запрос удалённой поддержки');
  await destination('home');await expect(page.locator('svg.scene')).toBeVisible();
  await rail.locator('[data-rail-section="threads"]').click();await expect(request).toHaveValue('Запрос удалённой поддержки');
  await destination('source');await page.getByRole('button',{name:'Действия страницы',exact:true}).click();await page.getByRole('menuitem',{name:'Копировать ссылку на вид',exact:true}).click();
  assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),page.url());
  await destination('home');await setInterfaceTheme(page,'dark');await shot('object-dark');
  await page.setViewportSize({width:390,height:844});await shot('object-mobile');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await destination('plugins');await expect(plugins).toBeVisible();await shot('plugins-mobile');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  // Inspect every SVG definition at all supported sizes, separately from the real application frames.
  const gallery=await context.newPage();await gallery.setViewportSize({width:1200,height:1000});
  await gallery.setContent('<style>body{font:13px system-ui;margin:24px;color:#25272c}main{display:grid;grid-template-columns:repeat(8,1fr);gap:18px}article{padding:10px;border:1px solid #ddd;border-radius:10px}section{display:flex;align-items:center;gap:8px;height:46px}small{display:block}</style><main>'+shellIconNames.map(icon=>'<article><small>'+icon+'</small><section>'+[16,20,24].map(size=>renderToStaticMarkup(createElement(ResourceIcon,{icon,size}))).join('')+'</section></article>').join('')+'</main>');
  const bounds=await gallery.locator('svg').evaluateAll(nodes=>nodes.map(node=>{const svg=node as SVGSVGElement,b=svg.getBBox();return {icon:svg.dataset.icon,x:b.x,y:b.y,right:b.x+b.width,bottom:b.y+b.height,width:b.width,height:b.height};}));
  for(const b of bounds){assert.ok(b.width>0&&b.height>0,JSON.stringify(b));assert.ok(b.x>=0&&b.y>=0&&b.right<=24&&b.bottom<=24,'SVG clipping: '+JSON.stringify(b));}
  await gallery.screenshot({path:join(evidence,'icons-light.png')});await gallery.addStyleTag({content:'body{background:#1b1c20;color:#e0e3e9}article{border-color:#373b43}'});await gallery.screenshot({path:join(evidence,'icons-dark.png')});await gallery.close();
  assert.deepEqual(errors,[]);console.log('PASS central shell: default real 2D/3D; one rail destination and explorer menu; central code/monitor/plugins; shell-owned sidebar; URL reload/back/forward/copy; drafts retained; project plugin source/add/search; mobile/dark; all SVG bounds at 16/20/24; no page errors.');
} catch(error){await shot('failure');console.error('Browser errors:',errors);throw error;} finally {await context.close();await browser.close();await app.close();work.clean();}
