import {chromium,expect} from 'playwright/test';
import assert from 'node:assert/strict';
import {fixture} from '../tests/helpers';
import {createApp} from '../src/host/dev';
import {join} from 'node:path';
import {deploymentSource,initialDeployment} from '../src/workspace/deployment';
import {chooseExplorerMode} from './helpers/explorer-mode';
const f=fixture();await Bun.write(join(f.root,'targets/deployment.ts'),deploymentSource({...initialDeployment,id:'reviewed-plan',steps:initialDeployment.steps.map(s=>({...s,label:'Проверенный · '+s.label}))}));
const app=await createApp({projectDir:f.root,dataDir:f.dir,port:0});const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']}),context=await browser.newContext({viewport:{width:1440,height:1050},recordVideo:{dir:'artifacts/details-recording'}}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(app.server.url.href);await page.locator('.shell').waitFor();const nav=page.getByRole('tree',{name:'Структура проекта'}),rail=page.getByRole('navigation',{name:'Рабочие области'}),details=page.getByRole('complementary',{name:'Свойства объекта'});await chooseExplorerMode(page,'Код');await rail.getByRole('button',{name:'Объект',exact:true}).click();
 await page.locator('[data-equipment="P-01"]').click();await page.getByRole('button',{name:'Свойства',exact:true}).click();await expect(details.getByRole('heading',{name:'Параметры',exact:true})).toBeVisible();await expect(details.getByRole('heading',{name:'Интерфейсы',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Свойства',exact:true})).toHaveCount(1);await page.screenshot({path:'artifacts/details-device.png'});
 await details.getByRole('button',{name:/^discharge /}).click();await expect(details.getByRole('heading',{name:'Концы соединения',exact:true})).toBeVisible();await page.screenshot({path:'artifacts/details-connection.png'});await details.getByRole('button',{name:'Назад по связям',exact:true}).click();
 await details.getByRole('button',{name:/^P-01.pressure /}).click();await expect(details.getByRole('heading',{name:'Контракт',exact:true})).toBeVisible();await details.getByRole('button',{name:/Высокое давление/}).click();await expect(details.getByRole('heading',{name:'Состояние',exact:true})).toBeVisible();await page.screenshot({path:'artifacts/details-alarm.png'});
 await rail.getByRole('button',{name:'Мониторинг',exact:true}).click();await page.getByRole('button',{name:'V-01.opening',exact:true}).click();await details.getByRole('spinbutton',{name:'V-01.opening'}).fill('63');await page.waitForTimeout(1300);await expect(details.getByRole('spinbutton',{name:'V-01.opening'})).toHaveValue('63');await page.screenshot({path:'artifacts/details-signal.png'});
 await rail.getByRole('button',{name:'Отчёты',exact:true}).click();await expect(details.getByRole('heading',{name:'Колонки',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Экспорт отчёта',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Сформировать',exact:true}).click();await expect(page.getByRole('button',{name:'Экспорт отчёта',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Экспорт отчёта',exact:true}).click();await expect(page.getByRole('menuitem',{name:'Excel (.xlsx)',exact:true})).toBeVisible();await page.screenshot({path:'artifacts/details-report-export.png'});await page.keyboard.press('Escape');
 await rail.getByRole('button',{name:'Объект',exact:true}).click();await chooseExplorerMode(page,'Объекты');await nav.getByRole('treeitem',{name:'HMI',exact:true}).click();await page.locator('.hmi-gallery').getByRole('button',{name:'Экран контроллера',exact:true}).click();await expect(details.getByText('Размер экрана',{exact:true})).toBeVisible();await page.screenshot({path:'artifacts/details-hmi.png'});
 await rail.getByRole('button',{name:'Среда',exact:true}).click();await expect(page.locator('.deployment-steps article')).toHaveCount(4);await expect(page.locator('.deployment-steps')).toContainText('Проверенный ·');await page.screenshot({path:'artifacts/details-deployment.png'});assert(await page.locator('.deployment-steps').evaluate(el=>el.scrollWidth<=el.clientWidth),'Deployment cards overflow');
 await page.getByRole('button',{name:'Изменить в коде',exact:true}).click();await expect(details.getByRole('heading',{name:'Файл проекта',exact:true})).toBeVisible();await expect(details).toContainText('targets/deployment.ts');await page.screenshot({path:'artifacts/details-target.png'});
 await nav.getByRole('treeitem',{name:'README.md',exact:true}).click();await expect(details.getByRole('heading',{name:'Файл проекта',exact:true})).toBeVisible();await expect(details).toContainText('README.md');await expect(details.getByRole('button',{name:'Показать в коде',exact:true})).toHaveCount(0);await page.screenshot({path:'artifacts/details-file.png'});
 await page.getByRole('textbox',{name:'Фильтр панели'}).fill('simulation.ts');await nav.getByRole('treeitem',{name:'simulation.ts',exact:true}).click();await expect(details).toContainText('Расширение');await expect(details).toContainText('Исходники принадлежат проекту');await page.screenshot({path:'artifacts/details-plugin.png'});await page.getByRole('textbox',{name:'Фильтр панели'}).fill('');await nav.getByRole('treeitem',{name:'deployment.ts',exact:true}).click();
 await page.getByRole('button',{name:'Тёмная тема',exact:true}).click();await page.screenshot({path:'artifacts/details-dark.png'});await page.setViewportSize({width:390,height:844});await expect(details).toBeVisible();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'artifacts/details-phone.png'});await details.getByRole('button',{name:'Закрыть свойства',exact:true}).click();await expect(details).toHaveCount(0);await page.screenshot({path:'artifacts/details-closed-phone.png'});
 await page.setViewportSize({width:1440,height:1050});await rail.getByRole('button',{name:'Объект',exact:true}).click();await nav.getByRole('treeitem',{name:'Документация',exact:true}).click();await page.getByRole('button',{name:'Свойства',exact:true}).click();await expect(details.getByRole('heading',{name:'Состав проекта',exact:true})).toBeVisible();await page.screenshot({path:'artifacts/details-project.png'});
 await rail.getByRole('button',{name:'Мониторинг',exact:true}).click();await page.getByRole('button',{name:'V-01.opening',exact:true}).click();await app.close();await expect(page.locator('.sim-badge')).toHaveClass(/offline/);await expect(page.locator('.sim-badge')).toHaveText('ОФЛАЙН');await expect(details).toContainText('Нет соединения с runtime');await expect(details).toContainText('Устарело');await expect(details.getByRole('spinbutton',{name:'V-01.opening'})).toBeDisabled();await expect(details).toContainText('Последнее полученное значение');await page.screenshot({path:'artifacts/details-offline.png'});
 assert.deepEqual(errors,[]);console.log('PASS real browser consistent device/signal/connection/alarm/report/HMI/target/plugin/file/project details, draft-preserving command input, real authored deployment, export menu and dark/mobile/closed/offline states');
}catch(e){await page.screenshot({path:'artifacts/details-failure.png'});throw e;}finally{await context.close();await browser.close();await app.close();f.clean();}
