import { prepareInterface, setInterfaceTheme } from './helpers/interface-preferences';
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { chromium, expect } from 'playwright/test';
import { fixture } from '../tests/helpers';
import { createApp } from '../src/host/dev';
import { execute } from '../src/workspace/git';

const evidence='artifacts/engineering-shell';mkdirSync(evidence,{recursive:true});
const work=fixture();
const git=(...args:string[])=>execute(['git',...args],work.root);
await git('init','-b','main');await git('config','user.name','Shell test');await git('config','user.email','shell@example.test');await git('add','.');await git('commit','-m','Reference');
const app=await createApp({projectDir:work.root,dataDir:work.dir,databaseUrl:':memory:',port:0,preview:'simulation'});
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1600,height:1000},locale:'ru-RU',permissions:['clipboard-read','clipboard-write'],recordVideo:{dir:join(evidence,'recording')}});
const page=await context.newPage(),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
const snap=(name:string)=>page.screenshot({path:join(evidence,`${name}.png`),animations:'disabled'});
const rail=page.getByRole('navigation',{name:'Рабочие области'});
try {
  await prepareInterface(context);
  await page.goto(app.server.url.href+'?page=chat');
  const chat=page.getByRole('region',{name:'Инженерная задача'}),drawer=page.locator('#artifact-drawer');
  await expect(chat).toBeVisible();await expect(drawer).toHaveAttribute('inert','');await snap('closed');
  await page.getByRole('button',{name:'Новая задача',exact:true}).click();
  const request=page.getByRole('textbox',{name:'Запрос для внешнего агента'});
  await request.fill('Проверь давление P-01 и связи проекта.');
  await page.getByRole('button',{name:'Копировать запрос',exact:true}).click();await expect(page.getByRole('button',{name:'Скопировано',exact:true})).toBeVisible();
  assert.match(await page.evaluate(()=>navigator.clipboard.readText()),/Проверь давление P-01/);
  await chat.getByRole('button',{name:'Открыть схему',exact:true}).click();
  await expect(drawer).toHaveAttribute('aria-hidden','false');await expect(page.locator('svg.scene')).toBeVisible();
  assert.ok(await page.locator('[data-anatomy="saturn-pump"] circle').count()>=10);assert.equal(await page.locator('[data-cable]').count(),2);
  await page.locator('svg.scene').evaluate(node=>node.setAttribute('data-retention-test','same-scene'));
  await snap('diagram-split');
  await page.getByRole('button',{name:'Скрыть правую панель',exact:true}).click();
  await expect(drawer).toHaveAttribute('inert','');await expect(request).toHaveValue('Проверь давление P-01 и связи проекта.');
  await page.getByRole('button',{name:'Показать правую панель',exact:true}).click();await expect(page.locator('svg.scene')).toBeVisible();
  assert.equal(await page.locator('svg.scene').getAttribute('data-retention-test'),'same-scene');
  await page.getByRole('button',{name:'3D',exact:true}).click();await expect(page.locator('.scene3d canvas')).toBeVisible({timeout:30000});
  await page.waitForFunction(()=>Number(document.querySelector<HTMLElement>('.scene3d')?.dataset.frames)>3);
  await page.locator('.scene3d canvas').evaluate(node=>node.setAttribute('data-retention-test','same-canvas'));
  await snap('3d-split');
  await page.getByRole('button',{name:'Новая вкладка',exact:true}).click();await expect(page.getByRole('region',{name:'Новая вкладка'})).toBeVisible();await snap('new-tab');
  await page.getByRole('button',{name:'Скрыть правую панель',exact:true}).click();await page.getByRole('button',{name:'Показать правую панель',exact:true}).click();
  await expect(page.getByRole('region',{name:'Новая вкладка'})).toBeVisible();
  await page.getByRole('button',{name:'Схема и 3D',exact:false}).click();await expect(page.locator('.scene3d canvas')).toBeVisible();
  assert.equal(await page.locator('.scene3d canvas').getAttribute('data-retention-test'),'same-canvas');
  await page.getByRole('button',{name:'2D',exact:true}).click();
  await page.getByRole('button',{name:'Сводка проекта',exact:true}).click();const summary=page.getByRole('dialog',{name:'Сводка проекта'});
  await expect(summary).toBeVisible();await expect(summary).toContainText('Checked');await expect(summary).toContainText('Published');await expect(summary).toContainText('Applied');await snap('summary');
  await page.keyboard.press('Escape');await expect(summary).toBeHidden();await expect(page.getByRole('button',{name:'Сводка проекта',exact:true})).toBeFocused();
  const width=page.getByRole('separator',{name:'Ширина правой панели'});const before=Number(await width.getAttribute('aria-valuenow'));await width.focus();await page.keyboard.press('ArrowLeft');await expect(width).toHaveAttribute('aria-valuenow',String(Math.min(900,before+24)));
  await page.getByRole('button',{name:'Полный вид',exact:true}).click();await expect(chat).toBeHidden();await expect(page.locator('svg.scene')).toBeVisible();await snap('full-view');
  await page.getByRole('button',{name:'Выйти из полного вида',exact:true}).click();await expect(chat).toBeVisible();
  await chat.getByRole('button',{name:'Изучить код',exact:true}).click();await expect(page.locator('.code-pane')).toBeVisible();
  const cm=page.locator('.cm-content');await cm.click();await page.keyboard.press('ControlOrMeta+End');await page.keyboard.type('\n// retained shell draft');
  const authoredText=()=>cm.evaluate(node=>Array.from(node.querySelectorAll('.cm-line')).map(line=>{const copy=line.cloneNode(true) as HTMLElement;copy.querySelectorAll('.cm-live-value').forEach(widget=>widget.remove());return copy.textContent;}).join('\n'));
  const cmText=await authoredText();await cm.evaluate(node=>node.setAttribute('data-retention-test','same-editor'));
  const terminal=page.getByRole('tab',{name:'Терминал',exact:true});await terminal.click();
  const terminalInput=page.locator('.command-input-row input');await terminalInput.fill('help');
  await page.getByRole('button',{name:'Скрыть правую панель',exact:true}).click();await page.getByRole('button',{name:'Показать правую панель',exact:true}).click();
  await expect(terminalInput).toHaveValue('help');assert.equal(await cm.getAttribute('data-retention-test'),'same-editor');assert.equal(await authoredText(),cmText);
  await page.getByRole('button',{name:'Новая вкладка',exact:true}).click();
  const search=page.getByRole('textbox',{name:'Найти инструмент или ресурс'});await search.fill('P-01');await expect(page.locator('.new-tool-tab')).toContainText('P-01.device.ts');await search.fill('');
  await page.getByRole('button',{name:'Ещё инструменты',exact:true}).click();await expect(page.getByRole('button',{name:'Среда исполнения Source',exact:false})).toBeVisible();
  await page.getByRole('button',{name:'Терминал Команды',exact:false}).click();await expect(terminalInput).toHaveValue('help');
  await rail.getByRole('button',{name:'Чат и поддержка',exact:true}).click();await page.getByRole('button',{name:'Показать правую панель',exact:true}).click();
  await page.getByRole('button',{name:'Действия задачи',exact:true}).click();await snap('task-menu');
  await page.getByRole('menuitem',{name:'Закрепить',exact:true}).click();
  await page.getByRole('button',{name:'Действия задачи',exact:true}).click();await page.getByRole('menuitem',{name:'В архив',exact:true}).click();
  await page.getByRole('button',{name:'Архив задач',exact:true}).click();await expect(page.locator('.thread-row')).toHaveCount(1);
  await setInterfaceTheme(page,'dark');await rail.getByRole('button',{name:'Чат и поддержка',exact:true}).click();await page.getByRole('button',{name:'Показать правую панель',exact:true}).click();await snap('dark');
  await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Главное меню',exact:true}).click();await page.getByRole('dialog',{name:'Главное меню'}).getByRole('button',{name:'Чат и поддержка',exact:true}).click();await expect(chat).toBeVisible();await snap('mobile-closed');
  await chat.getByRole('button',{name:'Открыть инструменты',exact:true}).click();await expect(page.getByRole('region',{name:'Новая вкладка'})).toBeVisible();await snap('mobile-new-tab');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile overflow');
  await page.keyboard.press('Escape');await expect(drawer).toHaveAttribute('inert','');
  await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await drawer.evaluate(node=>getComputedStyle(node).transitionDuration),'0s');
  await page.setViewportSize({width:1440,height:960});
  await page.getByRole('button',{name:'Показать правую панель',exact:true}).click();await search.fill('Код');await page.getByRole('button',{name:'Код и файлы TypeScript',exact:false}).click();
  await page.route('**/api/releases',route=>route.fulfill({status:503,body:JSON.stringify({error:'Release status unavailable'})}));
  await page.getByRole('button',{name:'Сводка проекта',exact:true}).click();await snap('summary-dark');await page.keyboard.press('Escape');
  await Bun.write(join(work.root,'project.ts'),'broken TypeScript {');await expect(page.locator('.shell-alert')).toBeVisible({timeout:20000});await snap('failed-build');
  await app.close();await expect(page.locator('.environment-chip')).toHaveClass(/offline/,{timeout:15000});
  await page.getByRole('button',{name:'Сводка проекта',exact:true}).click();await expect(summary).toContainText('Нет связи');await snap('offline');
  assert.deepEqual(errors,[]);
  console.log('PASS engineering shell: real host/driver, drawer close/reopen and 3D/editor/terminal retention, new tab search/tools, summary/menu/focus/resize/full view, failed/offline, 390px/dark/reduced motion, no page errors.');
} finally {await context.close();await browser.close();await app.close();work.clean();}
