import { prepareInterface, setInterfaceTheme } from './helpers/interface-preferences';
import {chromium,expect} from 'playwright/test';
import assert from 'node:assert/strict';
import {fixture} from '../tests/helpers';
import {createApp} from '../src/host/dev';
import {execute} from '../src/workspace/git';
import {join} from 'node:path';
import {mkdirSync} from 'node:fs';
import {chooseExplorerLayout,chooseExplorerMode} from './helpers/explorer-mode';
const f=fixture(),git=(...args:string[])=>execute(['git',...args],f.root);
mkdirSync('artifacts',{recursive:true});
await git('init','-b','main');await git('config','user.name','Project Engineer');await git('config','user.email','engineer@example.test');await git('add','.');await git('commit','-m','Initial station');
const source=await Bun.file(join(f.root,'equipment/P-01.device.ts')).text();await Bun.write(join(f.root,'equipment/P-01.device.ts'),source.replace(/x:\s*-?\d+(?:\.\d+)?/,'x: 160'));await git('commit','-am','Move pump on the diagram');
const app=await createApp({projectDir:f.root,dataDir:f.dir,port:0}),browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']}),context=await browser.newContext({viewport:{width:1440,height:1050},recordVideo:{dir:'artifacts/explorer-git-recording'}}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
try{
  await prepareInterface(context);
 await page.goto(app.server.url.href);await page.locator('.shell').waitFor();const nav=page.getByRole('tree',{name:'Структура проекта'});
 await expect(page.getByRole('button',{name:'Режим навигатора'})).toContainText('Объект');await expect(nav).toHaveClass(/explorer-objects/);await expect(nav.getByRole('treeitem',{name:'Исходники',exact:true})).toHaveCount(0);const pump=nav.locator('[data-tree-id^="object:"][data-resource-id="P-01"]');await expect(pump).toContainText('Повысительный насос');await expect(pump.locator('[data-icon="pump"]')).toBeVisible();await pump.click();await expect(page.locator('[data-equipment="P-01"]')).toHaveClass(/selected/);await page.screenshot({path:'artifacts/explorer-objects.png'});
 await chooseExplorerLayout(page,'Значки');await expect(pump).toHaveClass(/tree-tile/);await pump.focus();await page.keyboard.press('ArrowRight');assert.notEqual(await page.evaluate(()=>document.activeElement?.getAttribute('data-resource-id')),'P-01');await page.screenshot({path:'artifacts/explorer-icons.png'});
 await chooseExplorerMode(page,'Код');await expect(page.getByRole('button',{name:'Режим навигатора'})).toContainText('Исходники');await chooseExplorerLayout(page,'Список файлов');await expect(nav.locator('[data-tree-id="directory:equipment"]')).toHaveCount(0);await expect(nav.getByRole('treeitem',{name:/^P-01.device.ts/})).toContainText('equipment/P-01.device.ts');await nav.getByRole('treeitem',{name:/^P-01.device.ts/}).click();await expect(page.locator('.cm-content')).toContainText('pump');await page.screenshot({path:'artifacts/explorer-flat.png'});
 await chooseExplorerLayout(page,'Папки');await expect(nav.getByRole('treeitem',{name:'equipment',exact:true})).toBeVisible();await expect(nav.getByRole('treeitem',{name:'P-01.device.ts',exact:true})).toBeVisible();await page.reload();await expect(nav).toHaveClass(/explorer-folders/);await page.screenshot({path:'artifacts/explorer-folders.png'});
 await page.getByRole('navigation',{name:'Рабочие области'}).getByRole('button',{name:'Изменения',exact:true}).click();await page.locator('.git-commit').first().click();await expect(page.locator('.git-meaning')).toContainText('Положение X');await expect(page.locator('.git-meaning')).toContainText('160');await expect(page.locator('.git-diff-line.added').first()).toBeVisible();await expect(page.locator('.git-diff-line.removed').first()).toBeVisible();await expect(page.locator('.git-diff .diff-number').first()).toBeVisible();await expect(page.getByRole('button',{name:'Восстановить новым коммитом'})).toHaveCount(0);await page.screenshot({path:'artifacts/git-ast-diff.png'});
 await page.locator('.git-commit').last().click();await page.getByRole('button',{name:'Сравнить с текущей для восстановления…',exact:true}).click();await expect(page.getByRole('button',{name:'Восстановить новым коммитом'})).toBeEnabled();await expect(page.getByRole('region',{name:'Изменения восстановления'})).toBeVisible();await page.screenshot({path:'artifacts/git-restore-diff.png'});
 await setInterfaceTheme(page,'dark');await page.locator('.git-commit').first().click();await expect(page.locator('.git-meaning')).toContainText('Положение X');await page.screenshot({path:'artifacts/git-ast-dark.png'});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'artifacts/git-ast-phone.png'});
 await page.setViewportSize({width:1440,height:1050});await page.getByRole('navigation',{name:'Рабочие области'}).getByRole('button',{name:'Мониторинг',exact:true}).click();await nav.getByRole('treeitem',{name:'Сигналы',exact:true}).click();await page.getByRole('button',{name:'P-01.pressure',exact:true}).click();await expect(page.locator('.history')).toBeVisible();await expect(page.locator('.version-comparison')).toHaveCount(0);await page.screenshot({path:'artifacts/history-without-comparison.png'});
 assert.deepEqual(errors,[]);console.log('PASS object/icons/flat/folder explorer, persisted view, keyboard navigation, real AST commit review and colored diff, distinct restore preview, dark/mobile and removed A/B block');
}catch(e){await page.screenshot({path:'artifacts/explorer-git-failure.png'});throw e;}finally{await context.close();await browser.close();await app.close();f.clean();}
