import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { chromium } from 'playwright';
import { fixture } from '../tests/helpers';
import { createApp } from '../src/host/dev';
import { routeConnections } from '../src/topology';

mkdirSync('artifacts/free-end-collision', { recursive: true });
const work = fixture(), app = await createApp({ projectDir: work.root, dataDir: work.dir, databaseUrl: ':memory:', port: 0, preview: 'simulation' });
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
const wait = async (check: () => Promise<boolean>, message: string) => { for (let i = 0; i < 100; i++) { if (await check().catch(() => false)) return; await page.waitForTimeout(100); } throw new Error(message); };
try {
  await page.goto(app.server.url.toString());
  const pump = page.locator('.scene [data-equipment="P-01"]'); await pump.waitFor();
  await page.getByRole('button', { name: 'Правка', exact: true }).click();
  const before = app.state().project.equipment.find(item => item.id === 'P-01')!.x;
  const box = await pump.boundingBox(); assert(box);
  const x = box.x + box.width / 2, y = box.y + box.height / 2;
  await page.mouse.move(x, y); await page.mouse.down(); await page.mouse.move(x + 35, y - 12, { steps: 6 }); await page.mouse.up();
  await wait(async () => app.state().project.equipment.find(item => item.id === 'P-01')!.x !== before, 'Pump drag did not save');
  const moved = app.state().project.equipment.find(item => item.id === 'P-01')!;
  assert(moved.x - before >= 29, `Drag did not reach the free-end clearance: ${moved.x - before}`);
  const route = routeConnections(app.state().project).find(item => item.id === 'run-command');
  assert(route); assert.equal(route.valid, false); assert.equal(route.error, 'Free end overlaps equipment clearance');
  await wait(async () => await page.locator('.scene [data-cable="run-command"]').getAttribute('data-route-valid') === 'false', '2D did not mark the cable invalid');
  const notice=page.locator('.scene-frame [data-route-issue="true"]');
  assert.match(await notice.textContent() ?? '', /run-command[\s\S]*Свободный конец попал в зону оборудования/);
  assert.match(await notice.innerText(),/Свободный конец/);
  assert.equal(await page.locator('.scene [data-cable="run-command"] [data-route-diagnostic="true"]').count(),1);
  const initialView=await page.locator('.scene').getAttribute('viewBox');
  await notice.getByRole('button',{name:'Показать свободный конец',exact:true}).focus();await page.keyboard.press('Enter');
  await wait(async()=>await page.locator('.scene').getAttribute('viewBox')!==initialView,'2D diagnostic action did not focus free end');
  assert.equal(await notice.getAttribute('open'),null,'2D route details should collapse after focus');
  const focusedView=await page.locator('.scene').getAttribute('viewBox');
  await notice.locator('summary').click();
  assert.equal(await page.locator('.scene').getAttribute('viewBox'),focusedView,'Reopening details changed 2D focus');
  await notice.getByRole('button',{name:'Показать свободный конец',exact:true}).click();
  await page.screenshot({ path: 'artifacts/free-end-collision/blocked-2d.png' });
  await page.getByRole('button', { name: '3D', exact: true }).click();
  await wait(async () => Number(await page.locator('.scene3d').getAttribute('data-frames')) > 5, '3D did not render');
  assert.equal(await page.locator('.scene3d').getAttribute('data-invalid-routes'), '1');
  assert.match(await page.locator('.scene3d-route-issue').innerText(), /run-command[\s\S]*Свободный конец попал в зону оборудования/);
  await page.locator('.scene3d-route-issue').getByRole('button',{name:'Показать свободный конец',exact:true}).click();
  assert.equal(await page.locator('.scene3d').getAttribute('data-focused-route'),'run-command');
  assert.equal(await page.locator('.scene3d').getAttribute('data-focused-route-part'),'free-end');
  assert.equal(await page.locator('.scene3d-route-issue').getAttribute('open'),null,'3D route details should collapse after focus');
  await page.screenshot({ path: 'artifacts/free-end-collision/blocked-3d.png' });
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(100);
  const noticeBounds=await page.locator('.scene3d-route-issue').boundingBox();assert(noticeBounds&&noticeBounds.x>=0&&noticeBounds.x+noticeBounds.width<=390);
  const phoneNotice=page.locator('.scene3d-route-issue');
  assert(noticeBounds.height<70,'Collapsed warning still covers the target on phone');
  await phoneNotice.locator('summary').click();
  assert(await phoneNotice.getByRole('button',{name:'Показать соединение',exact:true}).isVisible());
  assert.equal(await page.locator('.scene3d').getAttribute('data-focused-route'),'run-command','Reopening details lost focused connection');
  await phoneNotice.getByRole('button',{name:'Показать свободный конец',exact:true}).click();
  assert.equal(await phoneNotice.getAttribute('open'),null);
  await page.screenshot({path:'artifacts/free-end-collision/blocked-3d-phone.png'});
  assert.deepEqual(errors, []);
  console.log(`PASS persisted pump drag +${moved.x - before} encloses the authored free cable end; 2D/3D show the exact red cause; no page errors`);
} finally { await browser.close(); await app.close(); work.clean(); }
