import { isAttached, type ConnectionEnd } from '../src/core';
const attachedPort = (end:ConnectionEnd|undefined) => end && isAttached(end) ? end.port : undefined;
const attachedDevice = (end:ConnectionEnd|undefined) => end && isAttached(end) ? end.device : undefined;
const isFree = (end:ConnectionEnd|undefined) => !!end && !isAttached(end);
import { chromium } from 'playwright';
import { mkdirSync } from 'node:fs';
import { fixture } from '../tests/helpers';
import { createApp } from '../src/host/dev';
const fixtureProject=fixture(),app=await createApp({projectDir:fixtureProject.root,dataDir:fixtureProject.dir,databaseUrl:':memory:',port:0});
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:960},deviceScaleFactor:1});
const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
function assert(condition:unknown,message:string):asserts condition {if(!condition)throw new Error(message);}
const until=async(check:()=>Promise<boolean>,message:string)=>{for(let i=0;i<100;i++){if(await check().catch(()=>false))return;await Bun.sleep(150);}throw new Error(message);};
const center=async(selector:string)=>{const box=await page.locator(selector).boundingBox();assert(box,`Missing ${selector}`);return {x:box.x+box.width/2,y:box.y+box.height/2};};
try{
  mkdirSync('artifacts',{recursive:true});await page.goto(app.server.url.toString());await page.locator('[data-equipment="P-01"]').waitFor();
  await page.locator('.shell-panel').waitFor();assert(await page.locator('.equipment-strip').count()===0,'Old equipment strip still occupies the scene');
  await page.getByRole('tab',{name:'Терминал',exact:true}).click();
  const command=page.getByRole('combobox',{name:'Команда оболочки'});await command.fill('help');await command.press('Enter');await page.locator('.shell-terminal-log').getByText('set <signal> <value>',{exact:false}).waitFor();
  assert(await page.locator('.shell-terminal-row[data-level="info"]').count()>0,'Terminal info output missing');
  await command.fill('unknown');await command.press('Enter');await page.locator('.shell-terminal-row[data-level="warn"]').getByText('Неизвестная команда',{exact:false}).waitFor();
  await command.fill('set P-01.run invalid');await command.press('Enter');await until(async()=>await page.locator('.shell-terminal-row[data-level="error"]').count()>0,'Terminal error output missing');
  await page.locator('.shell-terminal-filters button[data-level="error"]').click();assert(await page.locator('.shell-terminal-row[data-level="error"]').count()===0,'Error filter did not hide error output');await page.locator('.shell-terminal-filters button[data-level="error"]').click();
  await command.fill('set P-01.run false');await command.press('Enter');await until(async()=>app.state().snapshot.samples['P-01.run']?.value===false,'CMD stop command did not reach the simulator');
  await command.fill('set P-01.run true');await command.press('Enter');await until(async()=>app.state().snapshot.samples['P-01.run']?.value===true,'CMD start command did not reach the simulator');
  await until(async()=>await command.inputValue()==='','CMD input did not clear after submitting');
  await page.locator('[data-equipment="PLC-01"] .equipment-id').click();
  await until(async()=>await page.locator('.shell-terminal-signals').getByText('V-01.opening').count()>0,'Related PLC command missing from terminal');
  await command.fill('set V-01.opening 0');await command.press('Enter');
  await until(async()=>app.state().snapshot.alarms['high-pressure']?.active===true,'High-pressure alarm did not activate');
  await page.locator('.shell-terminal-row[data-level="warn"]').getByText('Тревога:',{exact:false}).waitFor();
  await command.fill('set V-01.opening 75');await command.press('Enter');
  await until(async()=>app.state().snapshot.alarms['high-pressure']?.active===false,'High-pressure alarm did not clear');
  await page.locator('.shell-terminal-row[data-level="info"]').getByText('Тревога снята:',{exact:false}).waitFor();
  await page.screenshot({path:'artifacts/diagram-dock-terminal.png'});
  await page.getByRole('tab',{name:'Оборудование',exact:true}).click();
  await page.locator('[data-equipment="PLC-01"] .equipment-id').click();await page.getByRole('tab',{name:/^Графики/}).click();
  await until(async()=>Number(await page.locator('.multi-trend').getAttribute('data-series-count'))>=2,'PLC boolean readings missing from graph');
  assert(await page.locator('.multi-trend [data-unit="0 / 1"]').count()===1,'PLC digital readings have no own scale');
  await page.screenshot({path:'artifacts/diagram-dock-plc-signals.png'});
  await page.locator('[data-equipment="P-01"]').click();await page.locator('[data-equipment="TK-01"]').click({modifiers:['Shift']});
  await until(async()=>await page.locator('.equipment.selected').count()===2,'2D multiselect failed');
  await until(async()=>Number(await page.locator('.multi-trend').getAttribute('data-series-count'))>=2,'Combined live trend missing');
  await page.getByRole('tab',{name:/^Графики/}).waitFor({state:'visible'});await until(async()=>await page.getByRole('tab',{name:/^Графики/}).getAttribute('aria-selected')==='true','Multi-select did not open graphs tab');
  await page.screenshot({path:'artifacts/select-trend-2d.png'});
  await page.getByRole('button',{name:'Развернуть панель'}).click();assert((await page.locator('.shell-panel').boundingBox())!.height>300,'Dock did not expand');await page.screenshot({path:'artifacts/select-trend-expanded.png'});await page.getByRole('button',{name:'Восстановить размер панели'}).click();
  const initialX=app.state().project.equipment.find(item=>item.id==='P-01')!.x;
  const selectedPump=await center('[data-equipment="P-01"]');await page.mouse.move(selectedPump.x,selectedPump.y);await page.mouse.down();await page.mouse.move(selectedPump.x+25,selectedPump.y+10,{steps:6});await page.mouse.up();
  assert(app.state().project.equipment.find(item=>item.id==='P-01')!.x===initialX,'Select mode moved equipment');
  await page.getByRole('button',{name:'Edit',exact:true}).click();await page.locator('[data-cable-plug="run-command.from"]').waitFor();
  const pump=await center('[data-equipment="P-01"]');await page.mouse.move(pump.x,pump.y);await page.mouse.down();await page.mouse.move(pump.x+35,pump.y+15,{steps:8});await page.mouse.up();
  await until(async()=>app.state().project.equipment.find(item=>item.id==='P-01')!.x!==initialX,'2D equipment drag did not save');
  const from=await center('[data-cable-plug="run-command.from"]'),to=await center('[data-equipment="PLC-01"] [data-port="DO2"]');
  await page.mouse.move(from.x,from.y);await page.mouse.down();await page.mouse.move(to.x,to.y,{steps:10});await page.mouse.up();
  await until(async()=>attachedPort(app.state().project.cables?.find(item=>item.id==='run-command')?.from)==='DO2','2D plug did not rewire');
  const connected2d=await center('[data-cable-plug="run-command.from"]');await page.mouse.move(connected2d.x,connected2d.y);await page.mouse.down();await page.mouse.move(1350,180,{steps:10});await page.mouse.up();
  await until(async()=>isFree(app.state().project.cables?.find(item=>item.id==='run-command')?.from),'2D unplug did not persist');
  const loose2d=await center('[data-cable-plug="run-command.from"]'),do2d=await center('[data-equipment="PLC-01"] [data-port="DO2"]');
  await page.mouse.move(loose2d.x,loose2d.y);await page.mouse.down();await page.mouse.move(do2d.x,do2d.y,{steps:10});await page.mouse.up();
  await until(async()=>!isFree(app.state().project.cables?.find(item=>item.id==='run-command')?.from)&&attachedPort(app.state().project.cables?.find(item=>item.id==='run-command')?.from)==='DO2','2D loose plug did not reconnect');
  await page.screenshot({path:'artifacts/select-edit-2d.png'});
  await page.getByRole('button',{name:'3D',exact:true}).click();await page.locator('.scene3d canvas').waitFor();await until(async()=>Number(await page.locator('.scene3d').getAttribute('data-frames'))>10,'3D scene did not render');
  const before3d=app.state().project.equipment.find(item=>item.id==='P-01')!.x;
  await until(async()=>!!(await page.locator('.scene3d').getAttribute('data-equipment-screens')),'3D projections missing');const initialEquipment=await page.locator('.scene3d').evaluate(node=>JSON.parse((node as HTMLElement).dataset.equipmentScreens??'[]') as {id:string;x:number;y:number}[]);
  const pump3d=initialEquipment.find(item=>item.id==='P-01');assert(pump3d,'3D pump projection missing');
  await page.mouse.move(pump3d.x,pump3d.y);await page.mouse.down();await page.mouse.move(pump3d.x+35,pump3d.y+10,{steps:10});await page.mouse.up();
  await until(async()=>app.state().project.equipment.find(item=>item.id==='P-01')!.x!==before3d,'3D equipment drag did not save');
  await page.screenshot({path:'artifacts/select-edit-3d.png'});
  const beforeFocus=await page.locator('.scene3d').evaluate(node=>JSON.parse((node as HTMLElement).dataset.equipmentScreens??'[]') as {id:string;x:number;y:number}[]),plc3d=beforeFocus.find(item=>item.id==='PLC-01');assert(plc3d,'3D PLC projection missing');
  await page.mouse.dblclick(plc3d.x,plc3d.y);await page.waitForTimeout(650);await page.screenshot({path:'artifacts/select-edit-3d-plc.png'});
  const projected=await page.locator('.scene3d').evaluate(node=>({plugs:JSON.parse((node as HTMLElement).dataset.cablePlugs??'[]') as {id:string;end:string;x:number;y:number}[],ports:JSON.parse((node as HTMLElement).dataset.portScreens??'[]') as {device:string;port:string;x:number;y:number}[]}));
  const plug=projected.plugs.find(item=>item.id==='run-command'&&item.end==='from'),socket=projected.ports.find(item=>item.device==='PLC-01'&&item.port==='DO1');assert(plug&&socket,'Missing projected 3D plug/port');
  await page.mouse.move(plug.x,plug.y);await page.mouse.down();await page.mouse.move(socket.x,socket.y,{steps:10});await page.mouse.up();
  await until(async()=>attachedPort(app.state().project.cables?.find(item=>item.id==='run-command')?.from)==='DO1','3D plug did not rewire');
  await until(async()=>await page.locator('.scene3d').evaluate(node=>{const plugs=JSON.parse((node as HTMLElement).dataset.cablePlugs??'[]') as {id:string;end:string;x:number;y:number}[],ports=JSON.parse((node as HTMLElement).dataset.portScreens??'[]') as {device:string;port:string;x:number;y:number}[];const plug=plugs.find(item=>item.id==='run-command'&&item.end==='from'),port=ports.find(item=>item.device==='PLC-01'&&item.port==='DO1');return !!plug&&!!port&&Math.hypot(plug.x-port.x,plug.y-port.y)<5;}),'3D plug projection did not update after rewire');
  const connected=await page.locator('.scene3d').evaluate(node=>JSON.parse((node as HTMLElement).dataset.cablePlugs??'[]') as {id:string;end:string;x:number;y:number}[]);
  const currentPlug=connected.find(item=>item.id==='run-command'&&item.end==='from');assert(currentPlug,'Connected 3D plug missing');
  await page.mouse.move(currentPlug.x,currentPlug.y);await page.mouse.down();await page.mouse.move(850,240,{steps:14});await page.mouse.up();
  await until(async()=>isFree(app.state().project.cables?.find(item=>item.id==='run-command')?.from),'3D unplug on empty ground did not persist');
  await until(async()=>await page.locator('.scene3d').evaluate(node=>{const plugs=JSON.parse((node as HTMLElement).dataset.cablePlugs??'[]') as {id:string;end:string;x:number;y:number}[];const plug=plugs.find(item=>item.id==='run-command'&&item.end==='from');return !!plug&&Math.hypot(plug.x-850,plug.y-240)<25;}),'3D loose plug projection did not update');
  const free=await page.locator('.scene3d').evaluate(node=>({plugs:JSON.parse((node as HTMLElement).dataset.cablePlugs??'[]') as {id:string;end:string;x:number;y:number}[],ports:JSON.parse((node as HTMLElement).dataset.portScreens??'[]') as {device:string;port:string;x:number;y:number}[]}));
  const loosePlug=free.plugs.find(item=>item.id==='run-command'&&item.end==='from'),do2=free.ports.find(item=>item.device==='PLC-01'&&item.port==='DO2');assert(loosePlug&&do2,'Loose 3D plug or DO2 missing');
  await page.mouse.move(loosePlug.x,loosePlug.y);await page.mouse.down();await page.mouse.move(do2.x,do2.y,{steps:14});await page.mouse.up();
  await until(async()=>!isFree(app.state().project.cables?.find(item=>item.id==='run-command')?.from)&&attachedPort(app.state().project.cables?.find(item=>item.id==='run-command')?.from)==='DO2','3D loose plug did not reconnect');
  await page.getByRole('button',{name:'S · Select'}).click();await page.getByRole('button',{name:'Действия',exact:true}).click();await page.getByRole('menuitem',{name:'Вписать схему',exact:true}).click();
  await until(async()=>await page.locator('.scene3d').evaluate(node=>{const equipment=JSON.parse((node as HTMLElement).dataset.equipmentScreens??'[]') as {id:string;x:number;y:number}[];return ['P-01','TK-01'].every(id=>{const item=equipment.find(candidate=>candidate.id===id);return !!item&&item.x>235&&item.x<1400&&item.y>100&&item.y<790;});}),'3D fit did not put equipment in view');
  const equipmentScreens=await page.locator('.scene3d').evaluate(node=>JSON.parse((node as HTMLElement).dataset.equipmentScreens??'[]') as {id:string;x:number;y:number}[]);
  const pumpPoint=equipmentScreens.find(item=>item.id==='P-01'),tankPoint=equipmentScreens.find(item=>item.id==='TK-01');assert(pumpPoint&&tankPoint,'3D equipment projections missing');
  await page.mouse.click(pumpPoint.x,pumpPoint.y);await until(async()=>(await page.locator('.scene3d').getAttribute('data-selected-equipment'))==='P-01','3D pump selection missing');
  await page.keyboard.down('Shift');await page.mouse.click(tankPoint.x,tankPoint.y);await page.keyboard.up('Shift');
  await until(async()=>{const ids=(await page.locator('.scene3d').getAttribute('data-selected-equipment'))?.split(',')??[];return ids.includes('P-01')&&ids.includes('TK-01')&&Number(await page.locator('.multi-trend').getAttribute('data-series-count'))>=4;},'3D multiselect trend missing');
  await page.waitForTimeout(1000);
  await page.screenshot({path:'artifacts/select-trend-3d.png'});
  assert(errors.length===0,`Browser errors: ${errors.join('; ')}`);
  console.log('PASS 2D multiselect/live trend, 2D and 3D equipment drag, 2D and 3D plug rewire, persisted unplug and reconnect; no page errors');
}finally{await browser.close();await app.close();fixtureProject.clean();}
