import assert from 'node:assert/strict';
import { cpSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { chromium } from 'playwright';
import { createApp } from '../src/host/dev';

const root = resolve(import.meta.dir, '..');
const out = join(root, 'artifacts', 'performance-dashboard');
const temp = mkdtempSync(join(root, '.saturn', 'performance-dashboard-'));
const projectDir = join(temp, 'project');
mkdirSync(out, { recursive: true });
cpSync(join(root, 'tests', 'fixtures', 'monitoring-project'), projectDir, { recursive: true });
const app = await createApp({ projectDir, dataDir: join(temp, 'data'), databaseUrl: ':memory:', port: 0, preview: 'simulation' });
let browser: Awaited<ReturnType<typeof chromium.launch>> | undefined;
let appClosed = false;
let manualApp: Awaited<ReturnType<typeof createApp>> | undefined;
try {
  assert.deepEqual(app.state().problems, [], JSON.stringify(app.state().problems));
  browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 950 }, colorScheme: 'dark', reducedMotion: 'reduce', recordVideo: { dir: join(out, 'recording'), size: { width: 1440, height: 950 } } });
  const page = await context.newPage();
  const errors: string[] = [];
  let hourHistoryRequests = 0;
  let dayHistoryRequests = 0;
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { const url = new URL(request.url()); if (url.pathname !== '/api/history/range') return; const range = Number(url.searchParams.get('to')) - Number(url.searchParams.get('from')); if (range === 3600_000) hourHistoryRequests++; if (range === 86400_000) dayHistoryRequests++; });
  await page.addInitScript(() => { localStorage.setItem('saturn.locale', 'ru'); localStorage.setItem('saturn.theme', 'system'); });
  await page.goto(app.server.url.toString());
  await page.getByRole('button', { name: 'Мониторинг', exact: true }).first().click();
  await page.getByRole('treeitem', { name: 'Состояние объекта', exact: true }).click();
  await page.locator('section.performance').waitFor();
  await page.keyboard.press('Control+j');
  await page.waitForFunction(() => document.querySelectorAll('.perf-monitor-group').length === 2);
  await page.waitForFunction(() => document.querySelector('.perf-monitor-group.warning') && document.querySelector('[data-current-value]')?.textContent !== '—');
  await page.waitForFunction(() => document.querySelector('.perf-line')?.getAttribute('d')?.includes('L'));
  assert.equal(await page.locator('.perf-monitor-group').count(), 2);
  assert.equal(await page.locator('.perf-monitor-metrics button').count(), 3);
  assert.match(await page.locator('.perf-overview').innerText(), /симулятор/i);
  assert.match(await page.locator('.perf-monitor-group.warning').innerText(), /Насос P-101/);
  assert.equal(await page.locator('.perf-title h2').innerText(), 'Состояние объекта');
  assert.equal(await page.locator('[data-kpi="runtime-alarms"] > strong').innerText(), '0');
  assert.equal(await page.locator('[data-kpi="rule-breaches"] > strong').innerText(), '1');
  const measurements = await page.locator('.perf-resources').boundingBox();
  assert(measurements && measurements.y + measurements.height < 950, 'current measurements must appear without scrolling on desktop');
  await page.getByRole('searchbox', { name: 'Поиск сигнала' }).fill('no-matching-signal');
  await page.getByText('Нет измеряемого сигнала', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Проверить тренд' }).click();
  assert.equal(await page.getByRole('searchbox', { name: 'Поиск сигнала' }).inputValue(), '');
  await page.waitForFunction(() => document.querySelector('.perf-chart')?.getAttribute('data-chart-signal') === 'P-101.pressure');
  await page.waitForFunction(() => (document.querySelector('.perf-body')?.scrollTop ?? 0) > 50);
  await page.locator('.perf-body').evaluate(element => { element.scrollTop = 0; });
  await page.waitForTimeout(300);
  await page.screenshot({ path: join(out, '1440-dark.png'), fullPage: true });

  await page.getByRole('button', { name: /Давление на выходе/ }).click();
  await page.waitForFunction(() => document.querySelector('.perf-chart')?.getAttribute('data-chart-signal') === 'P-101.pressure');
  await page.waitForFunction(() => (document.querySelector('.perf-body')?.scrollTop ?? 0) > 50);
  const fiveMinuteResponse = page.waitForResponse(response => response.url().includes('/api/history/range') && response.url().includes('P-101.pressure') && response.status() === 200);
  await page.getByRole('combobox', { name: 'Период графика' }).selectOption('300000');
  await fiveMinuteResponse;
  const hourResponse = page.waitForResponse(response => response.url().includes('/api/history/range') && response.url().includes('P-101.pressure') && response.status() === 200);
  await page.getByRole('combobox', { name: 'Период графика' }).selectOption('3600000');
  await hourResponse;
  await page.waitForTimeout(2400);
  assert.equal(hourHistoryRequests, 1, 'one-hour history auto-polled at display cadence');
  const dayResponse = page.waitForResponse(response => response.url().includes('/api/history/range') && response.url().includes('P-101.pressure') && response.status() === 200);
  await page.getByRole('combobox', { name: 'Период графика' }).selectOption('86400000');
  await dayResponse;
  await page.locator('.perf-trend-panel').scrollIntoViewIfNeeded();
  await page.screenshot({ path: join(out, '1440-day-manual.png'), fullPage: true });
  await page.waitForTimeout(2400);
  assert.equal(dayHistoryRequests, 1, '24-hour history auto-polled at display cadence');
  const manualResponse = page.waitForResponse(response => response.url().includes('/api/history/range') && response.url().includes('P-101.pressure') && response.status() === 200);
  await page.getByRole('button', { name: /Обновить историю/ }).click();
  await manualResponse;
  assert.equal(dayHistoryRequests, 2, 'manual refresh did not request history');
  await page.getByRole('combobox', { name: 'Период графика' }).selectOption('300000');
  await page.locator('.perf-trend-panel').scrollIntoViewIfNeeded();
  await page.screenshot({ path: join(out, '1440-pressure-drilldown.png'), fullPage: true });
  await page.getByRole('button', { name: /Открыть сигнал/ }).click();
  await page.getByText('P-101.pressure', { exact: true }).first().waitFor();
  await page.getByRole('treeitem', { name: 'Состояние объекта', exact: true }).click();
  await page.locator('section.performance').waitFor();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Пауза', exact: true }).click();
  assert.equal(await page.locator('section.performance').getAttribute('data-paused'), 'true');
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click();
  await page.getByRole('tab', { name: 'Источники и runtime' }).click();
  await page.getByText('Процесс Saturn').waitFor();
  await page.screenshot({ path: join(out, '1440-sources.png'), fullPage: true });
  await page.getByRole('tab', { name: 'Обзор и сигналы' }).click();
  await page.route('**/api/history/range?**', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"error":"test archive outage"}' }));
  await page.getByRole('combobox', { name: 'Период графика' }).selectOption('900000');
  await page.getByText('Архив недоступен', { exact: true }).waitFor();
  await page.locator('.perf-trend-panel').scrollIntoViewIfNeeded();
  await page.screenshot({ path: join(out, '1440-history-unavailable.png'), fullPage: true });
  await page.getByRole('tab', { name: 'Источники и runtime' }).click();
  await page.getByText('Процесс Saturn').waitFor();
  assert.equal(await page.getByText('Диагностика не обновляется.', { exact: false }).count(), 0);
  await page.unroute('**/api/history/range?**');
  await page.getByRole('tab', { name: 'Обзор и сигналы' }).click();
  await page.getByRole('combobox', { name: 'Период графика' }).selectOption('60000');

  for (const [scheme, width] of [['light', 1440], ['dark', 390], ['light', 390]] as const) {
    await page.emulateMedia({ colorScheme: scheme });
    await page.setViewportSize({ width, height: width === 390 ? 844 : 950 });
    await page.locator('.perf-body').evaluate(element => { element.scrollTop = 0; });
    await page.waitForTimeout(200);
    const dimensions = await page.evaluate(() => ({ viewport: innerWidth, document: document.documentElement.scrollWidth, surface: document.querySelector('section.performance')?.scrollWidth }));
    assert(dimensions.document <= dimensions.viewport + 1, JSON.stringify(dimensions));
    assert((dimensions.surface ?? 0) <= dimensions.viewport + 1, JSON.stringify(dimensions));
    await page.screenshot({ path: join(out, `${width}-${scheme}.png`), fullPage: true });
    if (width === 390) {
      const title = page.locator('.perf-title h2');
      assert(await title.evaluate(element => element.scrollWidth <= element.clientWidth + 1), 'page heading truncated at 390px');
      const reading = await page.locator('.perf-resource b').first().boundingBox();
      const footer = await page.locator('.perf-footer').boundingBox();
      assert(reading && footer && reading.y + reading.height < footer.y, 'first current reading hidden under footer at 390px');
      await page.locator('.perf-monitor-group').first().scrollIntoViewIfNeeded();
      await page.screenshot({ path: join(out, `390-${scheme}-monitoring.png`), fullPage: true });
      await page.locator('.perf-trend-panel').scrollIntoViewIfNeeded();
      await page.screenshot({ path: join(out, `390-${scheme}-history.png`), fullPage: true });
    }
  }
  await page.getByRole('button', { name: 'Пауза', exact: true }).click();
  const frozenValue = await page.locator('[data-current-value]').innerText();
  await app.close(); appClosed = true;
  await page.locator('section.performance .perf-notice.warning').filter({ hasText: 'Связь с runtime потеряна.' }).waitFor({ timeout: 12000 });
  assert.equal(await page.locator('[data-current-value]').innerText(), frozenValue, 'paused display lost its as-of reading after runtime disconnected');
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click();
  assert.match(await page.locator('.perf-monitor-group').first().getAttribute('class') ?? '', /unknown/);
  await page.screenshot({ path: join(out, '390-offline.png'), fullPage: true });
  manualApp = await createApp({ projectDir, dataDir: join(temp, 'manual-data'), databaseUrl: ':memory:', port: 0, preview: 'manual' });
  await page.setViewportSize({ width: 1440, height: 950 });
  await page.goto(manualApp.server.url.toString());
  await page.getByRole('button', { name: 'Мониторинг', exact: true }).first().click();
  await page.getByRole('treeitem', { name: 'Состояние объекта', exact: true }).click();
  await page.getByText('Применённой сборки нет.', { exact: false }).waitFor();
  assert.match(await page.locator('.perf-live').innerText(), /Нет исполнения/);
  assert.equal(await page.locator('.perf-kpi').first().locator('strong').innerText(), '—');
  assert.equal(await page.locator('.perf-monitor-group.unknown').count(), 2);
  await page.screenshot({ path: join(out, '1440-not-applied.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: join(out, '390-not-applied.png'), fullPage: true });
  assert.deepEqual(errors, []);
  writeFileSync(join(out, 'verification.json'), JSON.stringify({ runtime: Bun.version, platform: process.platform, checks: ['real project-owned monitor import', 'simulation observations', 'threshold warning distinct from zero runtime alarms', 'summary breach direct trend', 'desktop measurements above fold', 'metric to canonical signal', 'history period', '1h slower refresh', '24h one-time load and manual refresh', 'inspect', 'display pause', 'runtime tab', 'history 503 independent diagnostics', '1440 and 390 light/dark', 'offline unknown quality', 'manual preview no-applied no-live state'], hourHistoryRequests, dayHistoryRequests, errors }, null, 2));
  await context.close();
  console.log('PASS: project-owned monitoring → live dashboard, drilldown, period, pause, sources, light/dark/mobile/offline.');
} finally {
  await browser?.close();
  await manualApp?.close();
  if (!appClosed) await app.close();
  rmSync(temp, { recursive: true, force: true });
}
