import assert from 'node:assert/strict';
import {mkdirSync} from 'node:fs';
import {chromium} from 'playwright';
import {fixture} from '../tests/helpers';
import {createApp} from '../src/host/dev';
import {routeConnections} from '../src/topology';

mkdirSync('artifacts/pipe-visual-recording',{recursive:true});
const work=fixture(),app=await createApp({projectDir:work.root,dataDir:work.dir,databaseUrl:':memory:',port:0,preview:'simulation'});
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1440,height:960},recordVideo:{dir:'artifacts/pipe-visual-recording'}}),page=await context.newPage();
const errors:string[]=[],record:Record<string,unknown>={};page.on('pageerror',error=>errors.push(error.message));
const until=async(check:()=>Promise<boolean>,message:string)=>{const end=Date.now()+20000;while(Date.now()<end){if(await check().catch(()=>false))return;await page.waitForTimeout(80);}throw new Error(message);};
const routes=()=>routeConnections(app.state().project).map(route=>({id:route.id,kind:route.kind,valid:route.valid,error:route.error,points:route.points.map(point=>({x:point.x,y:point.y,z:point.z}))}));
const browserPipes=()=>page.locator('.scene [data-pipe]').evaluateAll(nodes=>nodes.map(node=>({id:(node as HTMLElement).dataset.pipe,valid:(node as HTMLElement).dataset.routeValid,path:node.querySelector('path')?.getAttribute('d')})));
const validPipes=()=>routes().filter(route=>route.kind==='pipe').every(route=>route.valid);
try{
  await page.goto(app.server.url.toString());await page.locator('[data-equipment="P-01"]').waitFor();
  await page.getByRole('button',{name:'Правка',exact:true}).click();
  const pump=page.locator('.scene [data-equipment="P-01"]'),rect=await pump.boundingBox();assert(rect);
  const start={x:rect.x+rect.width/2,y:rect.y+rect.height/2},move={x:start.x+80,y:start.y-45},beforeX=app.state().project.equipment.find(e=>e.id==='P-01')!.x;
  record.before2d={routes:routes(),browserPipes:await browserPipes()};
  assert(await page.locator('.scene [data-pipe] .pipe-fluid').count()>0,'2D fluid layer is missing');
  assert.equal(await page.locator('.scene [data-pipe] path').first().getAttribute('stroke-width'),'22','2D pipe body lost its readable diameter');
  assert((await browserPipes()).some(pipe=>pipe.path?.includes('Q')),'2D pipe bends are not rounded');
  await page.screenshot({path:'artifacts/pipe-before-2d.png'});
  await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(move.x,move.y,{steps:12});await page.waitForTimeout(150);
  record.during2d={routes:routes(),browserPipes:await browserPipes()};
  assert((await browserPipes()).every(pipe=>pipe.valid==='true'),'pipe preview became invalid during a clear 2D drag');
  await page.screenshot({path:'artifacts/pipe-during-2d.png'});
  await page.mouse.up();await until(async()=>app.state().project.equipment.find(e=>e.id==='P-01')!.x!==beforeX,'2D drop did not save pump position');
  record.after2d={routes:routes(),browserPipes:await browserPipes()};
  assert(validPipes(),'clear 2D drop produced an invalid physical pipe');
  assert((await browserPipes()).every(pipe=>pipe.valid==='true'),'browser pipe became invalid after 2D drop');
  assert.deepEqual((record.after2d as {browserPipes:unknown}).browserPipes,(record.during2d as {browserPipes:unknown}).browserPipes,'a rendered 2D pipe changed shape at drop');
  await page.screenshot({path:'artifacts/pipe-after-2d.png'});

  await page.getByRole('button',{name:'3D',exact:true}).click();const scene=page.locator('.scene3d');await scene.waitFor();
  await until(async()=>Number(await scene.getAttribute('data-frames'))>8,'3D did not render');
  assert.equal(Number(await scene.getAttribute('data-pipe-shells')),routes().filter(route=>route.kind==='pipe'&&route.valid).length,'3D pipe shells are missing');
  assert.equal(await scene.getAttribute('data-pipe-liquids'),await scene.getAttribute('data-pipe-shells'),'3D liquid layer is missing');
  const labels=await scene.locator('.scene3d-equipment-label').evaluateAll(nodes=>nodes.map(node=>({text:node.textContent,hidden:(node as HTMLElement).hidden,style:(node as HTMLElement).getAttribute('style')})));
  assert(await scene.locator('.scene3d-equipment-label:visible').count()>0,`3D equipment labels are not visible: ${JSON.stringify(labels)}`);
  const screen=await scene.evaluate(node=>JSON.parse((node as HTMLElement).dataset.equipmentScreens??'[]') as {id:string;x:number;y:number}[]);
  const target=screen.find(item=>item.id==='P-01');assert(target);
  record.before3d={routes:routes(),equipmentBuilds:await scene.getAttribute('data-equipment-builds'),routeBuilds:await scene.getAttribute('data-route-builds')};
  await page.screenshot({path:'artifacts/pipe-before-3d.png'});
  await page.mouse.move(target.x,target.y);await page.mouse.down();await page.mouse.move(target.x-30,target.y+10,{steps:10});
  await until(async()=>await scene.getAttribute('data-drag-kind')==='equipment','3D drag did not capture equipment');
  await page.waitForTimeout(150);record.during3d={routes:routes(),invalidRoutes:await scene.getAttribute('data-invalid-routes'),equipmentBuilds:await scene.getAttribute('data-equipment-builds'),routeBuilds:await scene.getAttribute('data-route-builds')};
  await page.screenshot({path:'artifacts/pipe-during-3d.png'});
  const oldX=app.state().project.equipment.find(e=>e.id==='P-01')!.x;await page.mouse.up();
  await until(async()=>app.state().project.equipment.find(e=>e.id==='P-01')!.x!==oldX,'3D drop did not save pump position');
  record.after3d={routes:routes(),equipmentBuilds:await scene.getAttribute('data-equipment-builds'),routeBuilds:await scene.getAttribute('data-route-builds'),invalidRoutes:await scene.getAttribute('data-invalid-routes')};
  assert(validPipes(),'clear 3D drop produced an invalid physical pipe');
  await page.screenshot({path:'artifacts/pipe-after-3d.png'});

  const positions=await scene.evaluate(node=>JSON.parse((node as HTMLElement).dataset.equipmentScreens??'[]') as {id:string;x:number;y:number}[]);
  const pumpAfter=positions.find(item=>item.id==='P-01'),controller=positions.find(item=>item.id==='PLC-01');assert(pumpAfter&&controller);
  const beforeBlocked=app.state().project.equipment.find(e=>e.id==='P-01')!.x;
  await page.mouse.move(pumpAfter.x,pumpAfter.y);await page.mouse.down();await page.mouse.move(controller.x,controller.y,{steps:12});await page.mouse.up();
  await until(async()=>app.state().project.equipment.find(e=>e.id==='P-01')!.x!==beforeBlocked,'blocked 3D drop did not save position');
  record.blocked3d={routes:routes(),invalidRoutes:await scene.getAttribute('data-invalid-routes')};
  assert(routes().some(route=>route.kind==='pipe'&&!route.valid),'intentional equipment overlap did not report a blocked pipe');
  const routeIssue=scene.locator('.scene3d-route-issue');
  assert(await routeIssue.isVisible(),'blocked 3D route has no visible explanation');
  assert((await routeIssue.innerText()).includes('Вывод порта пересекает оборудование'),'blocked 3D route does not explain the port collision');
  await page.screenshot({path:'artifacts/pipe-blocked-3d.png'});
  await page.getByRole('button',{name:'2D',exact:true}).click();
  const diagramIssue=page.locator('.diagram-canvas [data-route-issue="true"]');await diagramIssue.waitFor();
  assert((await diagramIssue.textContent())?.includes('Вывод порта пересекает оборудование'),'blocked 2D route does not explain the port collision');
  await page.screenshot({path:'artifacts/pipe-blocked-2d.png'});
  assert.deepEqual(errors,[]);await Bun.write('artifacts/pipe-visual-routes.json',JSON.stringify(record,null,2));
  console.log('PASS clear 2D/3D drag keeps physical pipes valid during preview and after drop; intentional equipment overlap reports invalid pipes; screenshots and route points recorded; no page errors');
}finally{await context.close();await browser.close();await app.close();work.clean();}
