import {chromium,expect} from 'playwright/test';
import assert from 'node:assert/strict';
import {fixture} from '../tests/helpers';
import {createApp} from '../src/host/dev';
import {join} from 'node:path';
const f=fixture();await Bun.write(join(f.root,'reports/flow.ts'),await Bun.file('examples/reports/flow.ts').text());
const source=await Bun.file(join(f.root,'project.ts')).text();await Bun.write(join(f.root,'project.ts'),"import {flowReport} from './reports/flow';\n"+source.replace('reports: [hourlyWater]','reports: [hourlyWater,flowReport(booster.flow)]'));
const app=await createApp({projectDir:f.root,dataDir:f.dir,port:0});const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']}),context=await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir:'artifacts/report-recording'}}),page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await Bun.sleep(2200);await page.goto(app.server.url.href);await page.locator('.shell').waitFor();await page.getByRole('tree',{name:'Структура проекта'}).getByRole('treeitem',{name:'Отчёты',exact:true}).click();
 await page.getByRole('button',{name:'Сформировать',exact:true}).click();await expect(page.locator('.report-table tbody tr').first()).toBeVisible();await page.screenshot({path:'artifacts/report-aggregate-migrated.png'});
 await page.getByLabel('Отчёт',{exact:true}).selectOption('flow-detail');await page.getByLabel('scale',{exact:true}).fill('2');await page.getByRole('button',{name:'Сформировать',exact:true}).click();
 const doc=page.frameLocator('.report-document');await expect(doc.getByRole('heading',{name:'Расход · типизированный отчёт'})).toBeVisible();await expect(doc.locator('tbody tr').first()).toBeVisible();await expect(doc.getByRole('img',{name:'Расход и пропуски'})).toBeVisible();await expect(doc.locator('td').filter({hasText:'—'}).first()).toBeVisible();
 await page.getByRole('button',{name:'Экспорт отчёта',exact:true}).click();const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('menuitem',{name:'Excel (.xlsx)',exact:true}).click()]);await download.saveAs('artifacts/report-browser.xlsx');assert.equal((await Bun.file('artifacts/report-browser.xlsx').bytes())[0],80);
 await page.getByRole('button',{name:'Экспорт отчёта',exact:true}).click();const [htmlDownload]=await Promise.all([page.waitForEvent('download'),page.getByRole('menuitem',{name:'HTML',exact:true}).click()]);await htmlDownload.saveAs('artifacts/report-browser.html');const html=await Bun.file('artifacts/report-browser.html').text();const printPage=await context.newPage();await printPage.setContent(html);await printPage.emulateMedia({media:'print'});await printPage.screenshot({path:'artifacts/report-print.png',fullPage:true});await printPage.close();
 const before=await Bun.file('artifacts/report-browser.xlsx').bytes();await Bun.sleep(1100);await page.getByRole('button',{name:'Экспорт отчёта',exact:true}).click();const [again]=await Promise.all([page.waitForEvent('download'),page.getByRole('menuitem',{name:'Excel (.xlsx)',exact:true}).click()]);const againPath=await again.path();assert(againPath);assert.deepEqual(await Bun.file(againPath).bytes(),before);
 await page.getByRole('button',{name:'Скрыть панель',exact:true}).click();await page.screenshot({path:'artifacts/report-typed.png'});await doc.locator('footer').scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/report-typed-table.png'});await page.getByRole('button',{name:'Тёмная тема',exact:true}).click();await page.screenshot({path:'artifacts/report-typed-dark.png'});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/report-typed-phone.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.getByLabel('scale',{exact:true}).fill('100');await expect(page.getByRole('button',{name:'Сформировать',exact:true})).toBeDisabled();await expect(page.getByRole('alert').filter({hasText:'границах'})).toBeVisible();await expect(page.locator('.report-document')).toHaveCount(0);await page.screenshot({path:'artifacts/report-failed.png'});
 assert.deepEqual(errors,[]);console.log('PASS checked project typed report → snapshot SQL → live browser table/chart/gaps, inputs, real XLSX download, repeat bytes, light/dark/phone and failed state');
}catch(e){await page.screenshot({path:'artifacts/report-browser-failure.png'});throw e;}finally{await context.close();await browser.close();await app.close();f.clean();}
