import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { chromium, expect } from 'playwright/test';
import { fixture } from '../tests/helpers';
import { createApp } from '../src/host/dev';
import { execute } from '../src/workspace/git';
import { chooseExplorerMode } from './helpers/explorer-mode';

mkdirSync('artifacts/review-pane-recording', { recursive: true });
const work = fixture(), git = (...args:string[]) => execute(['git',...args],work.root);
await git('init','-b','main');await git('config','user.name','Project Engineer');await git('config','user.email','engineer@example.test');
await git('add','.');await git('commit','-m','Baseline station');
const sourceHead=(await git('rev-parse','HEAD')).trim();
await Bun.write(join(work.root,'project.ts'),(await Bun.file(join(work.root,'project.ts')).text())+'\n// Review fixture: a saved source change.\n');
await Bun.write(join(work.root,'README.md'),(await Bun.file(join(work.root,'README.md')).text())+'\nReview fixture note.\n');
const app=await createApp({projectDir:work.root,dataDir:work.dir,databaseUrl:':memory:',port:0,preview:'simulation'});
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1440,height:960},locale:'ru-RU',recordVideo:{dir:'artifacts/review-pane-recording'}});
const page=await context.newPage(),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
try{
  await page.goto(app.server.url.toString());
  const review=page.getByRole('complementary',{name:'Ревью проекта'});
  const diagram=page.locator('.diagram-workspace'),source=page.locator('.code-pane');
  await diagram.waitFor();
  await page.getByRole('button',{name:'Ревью',exact:true}).click();
  await expect(review).toHaveAttribute('data-review-state','ready');
  await expect(page.locator('.unified-sidebar')).toBeVisible();
  await expect(diagram).toBeVisible();
  await expect(review.locator('.review-identity-details .review-identities')).toContainText('Checked');
  await expect(review.locator('.review-identity-details .review-identities')).toContainText('Published');
  await expect(review.locator('.review-identity-details .review-identities')).toContainText('Applied');
  await expect(review.locator('.review-files button')).toHaveCount(2);
  await review.locator('.review-files button').filter({hasText:'README.md'}).click();
  await expect(review.locator('.review-path').last()).toHaveText('README.md');
  await expect(diagram).toBeVisible();
  await review.locator('.review-files button').filter({hasText:'project.ts'}).click();
  await expect(review.locator('.git-diff')).toContainText('Review fixture: a saved source change.');
  await expect(diagram).toBeVisible();
  await page.screenshot({path:'artifacts/review-pane-diagram-light.png'});

  const devicePath=join(work.root,'equipment/P-01.device.ts'),deviceBefore=await Bun.file(devicePath).text();
  await page.getByRole('button',{name:'Правка',exact:true}).click();
  const pump=await page.locator('[data-equipment="P-01"]').boundingBox();assert(pump,'2D pump missing before Review refresh regression');
  const pumpX=pump.x+pump.width/2,pumpY=pump.y+pump.height/2;
  await page.mouse.move(pumpX,pumpY);await page.mouse.down();await page.mouse.move(pumpX+24,pumpY+8,{steps:8});await page.mouse.up();
  await expect.poll(async()=>await Bun.file(devicePath).text(),{timeout:20_000}).not.toBe(deviceBefore);
  await expect(review.locator('.review-files button')).toHaveCount(3,{timeout:20_000});
  await review.locator('.review-files button').filter({hasText:'P-01.device.ts'}).click();
  await expect(review.locator('.git-diff')).toContainText('equipment/P-01.device.ts');
  await expect(diagram).toBeVisible();
  await page.screenshot({path:'artifacts/review-pane-after-diagram-drag.png'});
  const firstDeviceDiff=await review.locator('.git-diff').textContent(),firstDeviceSource=await Bun.file(devicePath).text();
  const firstGitStatus=await page.evaluate(async()=>((await (await fetch('/api/git')).json()) as {status:string}).status);
  const movedPump=await page.locator('[data-equipment="P-01"]').boundingBox();assert(movedPump,'2D pump missing before second Review refresh');
  const movedX=movedPump.x+movedPump.width/2,movedY=movedPump.y+movedPump.height/2;
  await page.mouse.move(movedX,movedY);await page.mouse.down();await page.mouse.move(movedX+16,movedY+6,{steps:8});await page.mouse.up();
  await expect.poll(async()=>await Bun.file(devicePath).text(),{timeout:20_000}).not.toBe(firstDeviceSource);
  await expect.poll(async()=>{const next=await review.locator('.git-diff').textContent().catch(()=>null);return !!next&&next!==firstDeviceDiff;},{timeout:20_000}).toBe(true);
  const secondGitStatus=await page.evaluate(async()=>((await (await fetch('/api/git')).json()) as {status:string}).status);
  assert.equal(secondGitStatus,firstGitStatus,'second drag should update diff without changing Git status paths');
  await page.screenshot({path:'artifacts/review-pane-after-repeat-drag.png'});
  await page.getByRole('button',{name:'Выбор',exact:true}).click();

  await page.getByRole('button',{name:'3D',exact:true}).click();
  const scene=page.locator('.scene3d');await scene.waitFor({timeout:30000});
  await page.waitForFunction(()=>Number(document.querySelector<HTMLElement>('.scene3d')?.dataset.frames)>4);
  await page.locator('.scene3d canvas').evaluate(canvas=>(canvas as HTMLElement).dataset.reviewSentinel='mounted');
  const before=Number(await scene.getAttribute('data-frames'));
  await page.getByRole('button',{name:'Свойства',exact:true}).click();
  await expect(page.getByRole('complementary',{name:'Свойства объекта'})).toBeVisible();
  await page.getByRole('button',{name:'Ревью',exact:true}).click();
  await expect(review).toBeVisible();
  assert.equal(await page.locator('.scene3d canvas').getAttribute('data-review-sentinel'),'mounted','switching right pane remounted 3D');
  await page.waitForFunction(previous=>Number(document.querySelector<HTMLElement>('.scene3d')?.dataset.frames)>previous,before);
  await page.screenshot({path:'artifacts/review-pane-3d.png'});

  await page.getByRole('button',{name:'Закрыть ревью',exact:true}).click();
  const rail=page.getByRole('navigation',{name:'Рабочие области'});
  await rail.getByRole('button',{name:'Изменения',exact:true}).click();
  await expect(page.locator('.git-surface')).toBeVisible();
  await expect(review).toBeVisible();
  await page.getByRole('button',{name:'Тёмная тема',exact:true}).click();
  await page.screenshot({path:'artifacts/review-pane-git-dark.png'});
  await rail.getByRole('button',{name:'Среда',exact:true}).click();
  const environment=page.locator('.environment-surface');await expect(environment).toBeVisible();
  await expect(environment.locator(`dd[title="${sourceHead}"]`)).toContainText(sourceHead.slice(0,12));
  await expect(environment).toContainText('Checked');await expect(environment).toContainText('Published');await expect(environment).toContainText('Applied');
  await page.screenshot({path:'artifacts/review-pane-environment-dark.png'});
  await environment.locator(`dd[title="${sourceHead}"]`).scrollIntoViewIfNeeded();
  await expect(environment.locator(`dd[title="${sourceHead}"]`)).toBeVisible();
  await page.screenshot({path:'artifacts/review-pane-environment-identities.png'});
  await rail.getByRole('button',{name:'Мониторинг',exact:true}).click();
  const signalList=page.locator('.signals-surface>.table-scroll');await expect(signalList).toBeVisible();
  const signalListBounds=await signalList.boundingBox();assert(signalListBounds&&signalListBounds.height>=150,'signal table collapsed beneath diagnostics');
  await signalList.getByRole('button',{name:'P-01.pressure',exact:true}).click();
  await expect(page.locator('.signals-surface>.inspector-body')).toContainText('P-01.pressure');
  await expect(page.getByRole('complementary',{name:'Свойства объекта'})).toBeVisible();
  await expect(review).toHaveCount(0);
  await page.getByRole('button',{name:'Ревью',exact:true}).click();
  await expect(review).toBeVisible();
  await page.screenshot({path:'artifacts/review-pane-signals.png'});
  await rail.getByRole('button',{name:'Объект',exact:true}).click();
  await chooseExplorerMode(page,'Код');
  await page.getByRole('tree',{name:'Структура проекта'}).locator('[data-tree-id="file:project.ts"]').click();
  await expect(source).toBeVisible();
  await expect(review.locator('.review-path').first()).toHaveText('project.ts');
  await source.locator('.cm-content').click();await page.keyboard.press(process.platform==='darwin'?'Meta+ArrowDown':'Control+End');await page.keyboard.insertText('\n// Unsaved review draft.');
  await expect(review.locator('.review-file-state')).toContainText('Черновик не сохранён');
  await expect(review.locator('.git-diff')).not.toContainText('Unsaved review draft');
  await source.locator('.cm-content').evaluate(node=>(node as HTMLElement).dataset.reviewSentinel='mounted');
  await page.getByRole('button',{name:'Ревью',exact:true}).click();
  await expect(review).toHaveCount(0);
  await page.getByRole('button',{name:'Ревью',exact:true}).click();
  await expect(review).toBeVisible();
  assert.equal(await source.locator('.cm-content').getAttribute('data-review-sentinel'),'mounted','closing review remounted Source editor');
  await expect(source.locator('.cm-content')).toContainText('Unsaved review draft');
  await expect(review.locator('.review-files button[aria-current="true"]')).toContainText('P-01.device.ts');
  await page.screenshot({path:'artifacts/review-pane-source-draft.png'});

  await page.setViewportSize({width:390,height:844});
  const bounds=await review.boundingBox();assert(bounds&&bounds.x>=0&&bounds.x+bounds.width<=390,'mobile review drawer exceeds viewport');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile review caused horizontal overflow');
  await page.screenshot({path:'artifacts/review-pane-phone.png'});
  await page.getByRole('button',{name:'Закрыть ревью',exact:true}).focus();
  await page.keyboard.press('Escape');
  await expect(review).toHaveCount(0);
  await page.setViewportSize({width:1440,height:960});

  await page.route('**/api/git/review*',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Review fixture failure'})}));
  await page.getByRole('button',{name:'Ревью',exact:true}).click();
  await expect(review).toHaveAttribute('data-review-state','failed');
  const reviewFailure=review.getByText('Не удалось прочитать изменения:',{exact:false});
  await expect(reviewFailure).toContainText('Review fixture failure');
  await reviewFailure.scrollIntoViewIfNeeded();
  await page.screenshot({path:'artifacts/review-pane-failed.png'});
  await page.getByRole('button',{name:'Закрыть ревью',exact:true}).click();
  await page.unroute('**/api/git/review*');
  const releaseState=await page.evaluate(async()=>await (await fetch('/api/releases')).json()) as Record<string,unknown>;
  await page.route('**/api/releases',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({...releaseState,phase:'faulted',error:'Previous driver did not stop; replacement was not started'})}));
  await page.getByRole('button',{name:'Ревью',exact:true}).click();
  await expect(review).toHaveAttribute('data-review-state','faulted');
  await expect(review.locator('.review-release-error')).toContainText('Previous driver did not stop');
  await page.screenshot({path:'artifacts/review-pane-runtime-faulted.png'});
  await page.getByRole('button',{name:'Закрыть ревью',exact:true}).click();
  await page.unroute('**/api/releases');
  await page.getByRole('button',{name:'Ревью',exact:true}).click();
  await expect(review).toHaveAttribute('data-review-state','ready');
  await app.close();
  await page.waitForFunction(()=>document.querySelector('.sim-badge')?.textContent==='ОФЛАЙН');
  await expect(review).toHaveAttribute('data-review-state','offline');
  await expect(review.locator('.review-files button')).toHaveCount(3);
  await page.screenshot({path:'artifacts/review-pane-offline.png'});
  assert.deepEqual(errors,[]);
  console.log('PASS navigation + central Diagram/Source/Git + one contextual Review slot, live Git diff after 2D drag, file selection stays in pane, 3D/editor mounted across pane switches, identities and unsaved draft distinct, mobile drawer, failed/offline states; no page errors');
}catch(error){console.error('Browser page errors:',errors);await page.screenshot({path:'artifacts/review-pane-failure.png'});throw error;}
finally{await context.close();await browser.close();await app.close();work.clean();}
