import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { chromium, expect } from 'playwright/test';
import { createApp } from '../src/host/dev';

const root=resolve(import.meta.dir,'..'),output=join(root,'artifacts/system-grouping');mkdirSync(output,{recursive:true});
const temporary=mkdtempSync(join(root,'.saturn/system-grouping-')),projectDir=join(temporary,'project');mkdirSync(projectDir);
writeFileSync(join(projectDir,'project.ts'),`import {device,project,system} from '@saturn/core';
const bank=device({id:'bank',icon:'bank',ports:{}});
export default project({id:'grouped-installation',label:'Grouped installation',systems:[system('site','Площадка'),system('water','Водоснабжение','site'),system('power','Электроснабжение','site')],equipment:[bank('W1',{label:'Водяной узел 1',system:'water',x:120,y:180}),bank('W2',{label:'Водяной узел 2',system:'water',x:340,y:180}),bank('P1',{label:'Электрощит 1',system:'power',x:900,y:180})],pipes:[]});`);
const app=await createApp({projectDir,dataDir:join(temporary,'data'),port:0,preview:'simulation'});
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']}),context=await browser.newContext({viewport:{width:1280,height:800}}),page=await context.newPage(),errors:string[]=[];
page.on('pageerror',error=>errors.push(error.message));await page.addInitScript(()=>localStorage.setItem('saturn.locale','ru'));
try{
  assert.deepEqual(app.state().problems,[]);
  assert.equal(app.state().project.systems?.length,3);
  assert.deepEqual(app.state().project.equipment.map(e=>e.system),['water','water','power']);
  await page.goto(String(app.server.url));
  const scene=page.locator('.scene');await expect(scene.locator('[data-system]')).toHaveCount(3);
  const full=(await scene.getAttribute('viewBox'))!.split(' ').map(Number);
  await page.locator('[data-tree-id="system:water"]').click();
  await expect(scene.locator('[data-system="water"]')).toHaveAttribute('data-focused','true');
  await expect(page.locator('[data-tree-id="system:water"]')).toHaveAttribute('aria-selected','true');
  const focused=(await scene.getAttribute('viewBox'))!.split(' ').map(Number);
  assert(focused[2]!<full[2]!&&focused[3]!<full[3]!,`System did not focus: ${JSON.stringify({full,focused})}`);
  await page.screenshot({path:join(output,'2d-system.png'),fullPage:true});
  await page.getByRole('button',{name:'Правка',exact:true}).click();
  const plate=scene.locator('[data-system="water"] .scene-system-plate'),beforeX=Number(await plate.getAttribute('x'));
  const equipment=scene.locator('[data-equipment="W1"]'),rect=await equipment.boundingBox();assert(rect);
  const x=rect.x+rect.width/2,y=rect.y+rect.height/2;
  await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+55,y,{steps:7});await page.mouse.up();
  await expect.poll(async()=>Number(await plate.getAttribute('x')),{timeout:10_000}).toBeGreaterThan(beforeX);
  await page.screenshot({path:join(output,'2d-after-drag.png'),fullPage:true});
  await page.keyboard.press('Meta+s');
  await expect.poll(()=>Number(readFileSync(join(projectDir,'project.ts'),'utf8').match(/bank\('W1',\{[^}]*x:(\d+)/)?.[1]??0),{timeout:10_000}).toBeGreaterThan(120);
  await page.reload();
  await expect.poll(async()=>Number(await page.locator('.scene [data-system="water"] .scene-system-plate').getAttribute('x')),{timeout:10_000}).toBeGreaterThan(beforeX);
  await page.locator('[data-tree-id="system:water"]').click();
  await page.getByRole('button',{name:'3D',exact:true}).click();
  await page.waitForFunction(()=>Number(document.querySelector<HTMLElement>('.scene3d')?.dataset.frames)>3);
  await expect(page.locator('.scene3d')).toHaveAttribute('data-system-count','3');
  const pose=await page.locator('.scene3d').getAttribute('data-camera-pose');assert(pose);
  await page.screenshot({path:join(output,'3d-system.png'),fullPage:true});
  await page.getByRole('button',{name:'2D',exact:true}).click();
  await page.locator('[data-tree-id="system:power"]').click();
  await page.locator('.scene-system[data-system="power"] .scene-system-heading').click();
  await expect(page.locator('.scene [data-system="power"]')).toHaveAttribute('data-focused','true');
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'Открыть навигацию'}).click();
  await expect(page.locator('[data-tree-id="system:site"]')).toBeVisible();
  await page.locator('[data-tree-id="system:water"]').click();
  await expect(page.locator('.scene [data-system="water"]')).toHaveAttribute('data-focused','true');
  const width=await page.evaluate(()=>({viewport:innerWidth,document:document.documentElement.scrollWidth}));
  assert(width.document<=width.viewport+1,`Mobile grouped diagram overflow: ${JSON.stringify(width)}`);
  await page.screenshot({path:join(output,'mobile-system.png'),fullPage:true});
  assert.deepEqual(errors,[]);
  console.log(`PASS: authored hierarchy survived Builder/Runtime; sidebar and plate focus work in 2D; group bounds followed saved source-backed drag and reload; 3D rendered 3 group plates; mobile focus has no overflow. Frames: ${output}`);
}finally{await context.close();await browser.close();await app.close();rmSync(temporary,{recursive:true,force:true});}
